function FileData_Pairs(x)
{
x.t("trend","analysis");
x.t("formula","utilization");
x.t("summary","report");
x.t("forecast","formula");
x.t("forecast","report");
x.t("formulas","quantities");
x.t("analyze","compare");
x.t("comparison","forecast");
x.t("forecasting","formulas");
x.t("forecasting","reports");
x.t("minimum","maximum");
x.t("maximum","report");
x.t("quantities","comparison");
x.t("report","forecast");
x.t("report","forecasting");
x.t("report","minimum");
x.t("report","dynamic");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("reports","analyze");
x.t("reports","forecasting");
x.t("reports","activant");
x.t("reports","following");
x.t("dynamic","trend");
x.t("activant","solutions");
x.t("utilization","report");
x.t("following","reports");
x.t("866-878-0574","972-403-3150");
x.t("compare","forecasting");
x.t("analysis","summary");
}
