function FileData_Pairs(x)
{
x.t("line","product");
x.t("line","entering");
x.t("line","freight");
x.t(":entering","freight");
x.t("hierarchy","determine");
x.t("rate","product");
x.t("rate","level");
x.t("rate","matrix");
x.t("rate","vendor");
x.t("product","line");
x.t("product","vendor");
x.t("product","warehouse");
x.t("entering","freight");
x.t("maintain","percent");
x.t("estimating","freight");
x.t("determine","freight");
x.t("three","levels");
x.t("first","product");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("level","first");
x.t("matrix","product");
x.t("rates","entering");
x.t("rates","maintain");
x.t("rates","activant");
x.t("freight",":entering");
x.t("freight","rate");
x.t("freight","three");
x.t("freight","rates");
x.t("activant","solutions");
x.t("percent","estimating");
x.t("866-878-0574","972-403-3150");
x.t("vendor","line");
x.t("levels","hierarchy");
x.t("warehouse","entering");
}
