function FileData_Pairs(x)
{
x.t("available","blanket");
x.t("summary","report");
x.t(":blanket","purchase");
x.t("blanket","purchase");
x.t("expiration","report");
x.t("purchase","order");
x.t("report","blanket");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("reports","available");
x.t("reports","blanket");
x.t("reports","activant");
x.t("reports","following");
x.t("subsystem",":blanket");
x.t("subsystem","blanket");
x.t("activant","solutions");
x.t("order","summary");
x.t("order","expiration");
x.t("order","reports");
x.t("order","subsystem");
x.t("order","detail");
x.t("following","reports");
x.t("866-878-0574","972-403-3150");
x.t("detail","report");
}
