function FileData_Pairs(x)
{
x.t("available","accommodate");
x.t("inquiries","purchase");
x.t("refer","following");
x.t("orders","refer");
x.t("orders","costing");
x.t("orders","entering");
x.t("orders","purchase");
x.t("orders","flexible");
x.t("orders","activant");
x.t("costing","requirements");
x.t("costing","purchase");
x.t("sections","creating");
x.t("printing","costing");
x.t("printing","purchase");
x.t("entering","printing");
x.t("entering","purchase");
x.t("company\u2019s","purchasing");
x.t("requirements","information");
x.t("creating","purchase");
x.t("purchase","orders");
x.t("purchase","requisition");
x.t("purchase","order");
x.t("options","available");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("accommodate","company\u2019s");
x.t("information","entering");
x.t("flexible","purchasing");
x.t("requisition","purchase");
x.t("activant","solutions");
x.t("purchasing","costing");
x.t("purchasing","options");
x.t("order","inquiries");
x.t("order","printing");
x.t("following","sections");
x.t("866-878-0574","972-403-3150");
}
