function FileData_Pairs(x)
{
x.t("inquiries","available");
x.t("inquiries","activant");
x.t("inquiries","following");
x.t("inquiries","vendor");
x.t("available","vendor");
x.t(":vendor","rfq");
x.t("open","rfq");
x.t("inquiry","product");
x.t("inquiry","rfq");
x.t("inquiry","vendor");
x.t("product","open");
x.t("product","rfq");
x.t("rfq","inquiries");
x.t("rfq","inquiry");
x.t("rfq","buyer");
x.t("rfq","release");
x.t("rfq","subsystem");
x.t("rfq","history");
x.t("request","quote");
x.t("buyer","inquiry");
x.t("written","inquiry");
x.t("quote","subsystem");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("release","inquiry");
x.t("release","written");
x.t("release","history");
x.t("subsystem",":vendor");
x.t("subsystem","open");
x.t("history","inquiry");
x.t("activant","solutions");
x.t("following","inquiries");
x.t("866-878-0574","972-403-3150");
x.t("vendor","rfq");
x.t("vendor","request");
}
