function  WWHBookData_Files(P)
{
P.fA("Introduction","introduction.1.1.html");
P.fA("Prelude Module Overview","module%20overview.2.1.html");
P.fA("Order Processing","module%20overview.2.2.html");
P.fA("Setting up Customer Accounts","module%20overview.2.3.html");
P.fA("Setting up Customer Pricing","module%20overview.2.4.html");
P.fA("Identifying Sales Order Types","module%20overview.2.5.html");
P.fA("Entering Products","module%20overview.2.6.html");
P.fA("Handling Backorders","module%20overview.2.7.html");
P.fA("Printing Pick Tickets and Acknowledgements","module%20overview.2.8.html");
P.fA("Entering Quotations","module%20overview.2.9.html");
P.fA("Issuing RGAs &amp; Credit Memos","module%20overview.2.10.html");
P.fA("Using Administrative Holds for Sales Orders","module%20overview.2.11.html");
P.fA("Confirming and Invoicing Sales Orders","module%20overview.2.12.html");
P.fA("Order Processing Inquiries and Reports","module%20overview.2.13.html");
P.fA("Optional Order Processing Features","module%20overview.2.14.html");
P.fA("Gift Certificates","module%20overview.2.15.html");
P.fA("Credit Card Authorization","module%20overview.2.16.html");
P.fA("Commission Subsystem","module%20overview.2.17.html");
P.fA("Quality Inspection Subsystem","module%20overview.2.18.html");
P.fA("Point of Sale Subsystem","module%20overview.2.19.html");
P.fA("Manufacturer\u2019s Rep Subsystem","module%20overview.2.20.html");
P.fA("Manifest Subsystem","module%20overview.2.21.html");
P.fA("Lease Contract Subsystem","module%20overview.2.22.html");
P.fA("Sales Analysis","module%20overview.2.23.html");
P.fA("Purchasing","module%20overview.2.24.html");
P.fA("Setting up Vendors","module%20overview.2.25.html");
P.fA("Identifying Purchase Order Types","module%20overview.2.26.html");
P.fA("Replenishing Stock","module%20overview.2.27.html");
P.fA("Nightly Processing","module%20overview.2.28.html");
P.fA("Daily Processing","module%20overview.2.29.html");
P.fA("Using the Buyer Queue","module%20overview.2.30.html");
P.fA("Generating Quotes to Vendors","module%20overview.2.31.html");
P.fA("Issuing Blanket Purchase Orders","module%20overview.2.32.html");
P.fA("Purchasing Inquiries and Reports","module%20overview.2.33.html");
P.fA("Inventory","module%20overview.2.34.html");
P.fA("Setting up Products","module%20overview.2.35.html");
P.fA("Recording Product Usage","module%20overview.2.36.html");
P.fA("Receiving Stock","module%20overview.2.37.html");
P.fA("Transferring Stock","module%20overview.2.38.html");
P.fA("Entering Vendor Claims and Warranty Replacements","module%20overview.2.39.html");
P.fA("Counting Inventory","module%20overview.2.40.html");
P.fA("Cycle Counting","module%20overview.2.41.html");
P.fA("Physical Inventory","module%20overview.2.42.html");
P.fA("Running End-of-Month, End-of-Year Procedures","module%20overview.2.43.html");
P.fA("Inventory Inquiries and Reports","module%20overview.2.44.html");
P.fA("Accounts Receivable","module%20overview.2.45.html");
P.fA("Setting up Payment Terms","module%20overview.2.46.html");
P.fA("Receiving Customer Payments","module%20overview.2.47.html");
P.fA("Issuing Customer Rebates","module%20overview.2.48.html");
P.fA("Generating Service Charge Invoices","module%20overview.2.49.html");
P.fA("Printing Customer Statements","module%20overview.2.50.html");
P.fA("Collecting on Past Due Invoices","module%20overview.2.51.html");
P.fA("Using Credit Holds","module%20overview.2.52.html");
P.fA("Accounts Receivable Inquiries &amp; Reports","module%20overview.2.53.html");
P.fA("Accounts Payable","module%20overview.2.54.html");
P.fA("Reconciling Vendor Invoices","module%20overview.2.55.html");
P.fA("Paying Vendors","module%20overview.2.56.html");
P.fA("Reconciling Vendor Claims","module%20overview.2.57.html");
P.fA("Using Letters of Credit","module%20overview.2.58.html");
P.fA("Accounts Payable Inquiries &amp; Reports","module%20overview.2.59.html");
P.fA("General Ledger","module%20overview.2.60.html");
P.fA("Setting up the General Ledger Chart of Accounts","module%20overview.2.61.html");
P.fA("Creating Journal Entries","module%20overview.2.62.html");
P.fA("Balancing the General Ledger","module%20overview.2.63.html");
P.fA("Bank Reconciliation","module%20overview.2.64.html");
P.fA("Financial Report Manager","module%20overview.2.65.html");
P.fA("Using Multiple Currency","module%20overview.2.66.html");
P.fA("General Ledger Reports and Inquires","module%20overview.2.67.html");
P.fA("Optional Prelude Modules","module%20overview.2.68.html");
P.fA("Warehousing","module%20overview.2.69.html");
P.fA("Marketing","module%20overview.2.70.html");
P.fA("CRM","module%20overview.2.71.html");
P.fA("Advanced Forecasting","module%20overview.2.72.html");
P.fA("Shop Repair","module%20overview.2.73.html");
P.fA("Rental","module%20overview.2.74.html");
P.fA("Fixed Assets","module%20overview.2.75.html");
P.fA("Work Orders (Bill of Material)","module%20overview.2.76.html");
P.fA("E-Commerce","module%20overview.2.77.html");
P.fA("Job Accounting","module%20overview.2.78.html");
P.fA("Service","module%20overview.2.79.html");
P.fA("Belting","module%20overview.2.80.html");
P.fA("Prelude Procedures &amp; Functions","user%20functions.3.1.html");
P.fA("Using Prelude On-Line Documentation","user%20functions.3.2.html");
P.fA("Understanding Text Conventions","user%20functions.3.3.html");
P.fA("Identifying Icons","user%20functions.3.4.html");
P.fA("Understanding the Security Hierarchy","user%20functions.3.5.html");
P.fA("Logging In","user%20functions.3.6.html");
P.fA("Logging Out","user%20functions.3.7.html");
P.fA("Navigating Through Prelude","user%20functions.3.8.html");
P.fA("Using Menus","user%20functions.3.9.html");
P.fA("Using Hot Keys","user%20functions.3.10.html");
P.fA("Using Slash Commands","user%20functions.3.11.html");
P.fA("Using the Action Bar","user%20functions.3.12.html");
P.fA("Using the Toolbar","user%20functions.3.13.html");
P.fA("Using Function Buttons","user%20functions.3.14.html");
P.fA("Moving Through Screens","user%20functions.3.15.html");
P.fA("Closing Screens","user%20functions.3.16.html");
P.fA("Using the Location Retrieval Screen","user%20functions.3.17.html");
P.fA("Searching for Information","user%20functions.3.18.html");
P.fA("Searching for Products","user%20functions.3.19.html");
P.fA("Entering Dates","user%20functions.3.20.html");
P.fA("Using the Calculator","user%20functions.3.21.html");
P.fA("Entering Line Items","user%20functions.3.22.html");
P.fA("Inserting a Blank Line","user%20functions.3.23.html");
P.fA("Deleting a Line Item","user%20functions.3.24.html");
P.fA("Replacing a Line Item","user%20functions.3.25.html");
P.fA("Repeating a Line Item","user%20functions.3.26.html");
P.fA("Adding Comments to Transactions","user%20functions.3.27.html");
P.fA("Using Work Queues and Alerts","user%20functions.3.28.html");
P.fA("Toolbar Alerts and Inquiries","user%20functions.3.29.html");
P.fA("Prelude Notify","user%20functions.3.30.html");
P.fA("E-Mail Alerts","user%20functions.3.31.html");
P.fA("Running Reports","user%20functions.3.32.html");
P.fA("Entering Selection Criteria","user%20functions.3.33.html");
P.fA("Modifying Selection Criteria","user%20functions.3.34.html");
P.fA("Saving Report Parameters","user%20functions.3.35.html");
P.fA("Using Saved Report Parameters","user%20functions.3.36.html");
P.fA("Scheduling Reports","user%20functions.3.37.html");
P.fA("Viewing Report Output","user%20functions.3.38.html");
P.fA("Printing Documents","user%20functions.3.39.html");
P.fA("E-Mailing Documents","user%20functions.3.40.html");
P.fA("Faxing Documents","user%20functions.3.41.html");
P.fA("Appendix A - Glossary","AppB_terms.4.1.html");
}
