function FileData_Pairs(x)
{
x.t("overview","order");
x.t("features",":gift");
x.t("certificates","gift");
x.t("certificates","customers");
x.t("certificates","activant");
x.t("certificates","company");
x.t("certificate","prelude");
x.t("certificate","numbers");
x.t("gift","certificates");
x.t("gift","certificate");
x.t("issues","gift");
x.t("prelude","module");
x.t("processing","features");
x.t("processing","optional");
x.t("pre-printed","forms");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("customers","pay");
x.t("customers","system");
x.t("already","customers");
x.t("pay","merchandise");
x.t("generate","gift");
x.t("forms","numbers");
x.t("module","overview");
x.t("optional","order");
x.t("activant","solutions");
x.t("numbers","pre-printed");
x.t("numbers","already");
x.t("order","processing");
x.t(":gift","certificates");
x.t("system","generate");
x.t("866-878-0574","972-403-3150");
x.t("using","gift");
x.t("company","issues");
x.t("merchandise","using");
}
