function FileData_Pairs(x)
{
x.t("just","entered");
x.t("line","items");
x.t("line","prelude");
x.t("line","enter");
x.t("line","created");
x.t("line","item");
x.t("product","just");
x.t("product","previous");
x.t("want","enter");
x.t("items",":repeating");
x.t("repeating","line");
x.t("entering","line");
x.t("entered","move");
x.t("procedures","functions");
x.t("functions","entering");
x.t("next","line");
x.t("prelude","procedures");
x.t("move","cursor");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("cursor","next");
x.t("previous","line");
x.t("enter","line");
x.t(":repeating","line");
x.t("activant","solutions");
x.t("created","product");
x.t("866-878-0574","972-403-3150");
x.t("item","product");
x.t("item","want");
x.t("item","repeating");
x.t("item","activant");
}
