function FileData_Pairs(x)
{
x.t("dialog","box");
x.t("press","esc");
x.t(":logging","activant");
x.t("close","open");
x.t("close","prelude");
x.t("open","screens");
x.t("times","following");
x.t("box","appears");
x.t("logging","logging");
x.t("logging","log");
x.t("three","times");
x.t("procedures","functions");
x.t("functions",":logging");
x.t("esc","three");
x.t("appears","choose");
x.t("prelude","close");
x.t("prelude","procedures");
x.t("screens","press");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("choose","close");
x.t("activant","solutions");
x.t("following","dialog");
x.t("866-878-0574","972-403-3150");
x.t("log","prelude");
}
