function FileData_Pairs(x)
{
x.t("paying","vendors");
x.t("void","erroneous");
x.t("credit","card");
x.t("payments","prelude");
x.t("checks","void");
x.t("card","electronic");
x.t(":paying","vendors");
x.t("file","transfer");
x.t("check","credit");
x.t("overview","accounts");
x.t("(abd)","record");
x.t("vendors","paying");
x.t("vendors","check");
x.t("vendors","prelude");
x.t("vendors","activant");
x.t("manual","checks");
x.t("record","manual");
x.t("erroneous","payments");
x.t("payable",":paying");
x.t("automatic","bank");
x.t("prelude","pay");
x.t("prelude","module");
x.t("bank","deduction");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("pay","vendors");
x.t("transfer","(eft)");
x.t("module","overview");
x.t("deduction","(abd)");
x.t("activant","solutions");
x.t("electronic","file");
x.t("866-878-0574","972-403-3150");
x.t("(eft)","automatic");
x.t("accounts","payable");
}
