function FileData_Pairs(x)
{
x.t(":counting","inventory");
x.t("counting","physical");
x.t("counting","inventory");
x.t("physical","inventory");
x.t("inventory",":counting");
x.t("inventory","counting");
x.t("inventory","prelude");
x.t("inventory","depending");
x.t("inventory","activant");
x.t("inventory","using");
x.t("count","inventory");
x.t("overview","inventory");
x.t("cycle","counting");
x.t("methods","cycle");
x.t("procedures","count");
x.t("prelude","module");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("depending","company");
x.t("module","overview");
x.t("activant","solutions");
x.t("following","methods");
x.t("866-878-0574","972-403-3150");
x.t("using","following");
x.t("company","procedures");
}
