function FileData_Pairs(x)
{
x.t("method","user");
x.t("user","user");
x.t("user","identification");
x.t("queue","issues");
x.t("want","receive");
x.t("e-mail","notification");
x.t("e-mail","alerts");
x.t("queues","alerts");
x.t(":e-mail","alerts");
x.t("procedures","functions");
x.t("functions","using");
x.t("issues","notification");
x.t("prelude","procedures");
x.t("receive","e-mail");
x.t("maintenance","prelude");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("notification","method");
x.t("notification","work");
x.t("identification","maintenance");
x.t("alerts","want");
x.t("alerts","e-mail");
x.t("alerts",":e-mail");
x.t("alerts","activant");
x.t("activant","solutions");
x.t("work","queue");
x.t("work","queues");
x.t("866-878-0574","972-403-3150");
x.t("using","work");
}
