function FileData_Pairs(x)
{
x.t("line","items");
x.t("line","item");
x.t("delete","incorrect");
x.t("items",":replacing");
x.t("entering","line");
x.t("incorrect","line");
x.t(":replacing","line");
x.t("procedures","functions");
x.t("functions","entering");
x.t("prelude","procedures");
x.t("cannot","replace");
x.t("replace","line");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("enter","correct");
x.t("correct","line");
x.t("replacing","line");
x.t("activant","solutions");
x.t("866-878-0574","972-403-3150");
x.t("item","delete");
x.t("item","prelude");
x.t("item","cannot");
x.t("item","enter");
x.t("item","replacing");
x.t("item","activant");
}
