function FileData_Pairs(x)
{
x.t("years","lease");
x.t("payments","period");
x.t("customer","contract");
x.t("customer","pay");
x.t("contract","subsystem");
x.t("contract","information");
x.t("quarters","years");
x.t("need","customer");
x.t("overview","order");
x.t("features",":lease");
x.t("invoice","several");
x.t("lease","contract");
x.t(":lease","contract");
x.t("period","months");
x.t("prelude","module");
x.t("processing","features");
x.t("processing","optional");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("pay","invoice");
x.t("several","payments");
x.t("subsystem","customer");
x.t("subsystem","need");
x.t("subsystem","lease");
x.t("subsystem","activant");
x.t("information","prelude");
x.t("module","overview");
x.t("optional","order");
x.t("months","quarters");
x.t("activant","solutions");
x.t("order","processing");
x.t("866-878-0574","972-403-3150");
}
