function FileData_Pairs(x)
{
x.t("claim","report");
x.t("claim-by","warehouse");
x.t(":vendor","claims");
x.t("summary","report");
x.t("open","vendor");
x.t("allowed/disallowed","summary");
x.t("allowed/disallowed","report");
x.t("payable","reports");
x.t("report","open");
x.t("report","vendor");
x.t("report","accounts");
x.t("report","detail");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("reports",":vendor");
x.t("reports","include");
x.t("reports","activant");
x.t("reports","following");
x.t("reports","vendor");
x.t("include","information");
x.t("information","vendor");
x.t("activant","solutions");
x.t("following","accounts");
x.t("866-878-0574","972-403-3150");
x.t("vendor","claim");
x.t("vendor","claim-by");
x.t("vendor","claims");
x.t("warehouse","report");
x.t("accounts","payable");
x.t("claims","open");
x.t("claims","allowed/disallowed");
x.t("claims","reports");
x.t("detail","claims");
}
