function FileData_Pairs(x)
{
x.t("refer","following");
x.t("void","single");
x.t("void","reverse");
x.t("g/l","entries");
x.t("payments","refer");
x.t("payments","vendor");
x.t("open","accounts");
x.t("multiple","payments");
x.t("back","open");
x.t("single","payment");
x.t("range","payments");
x.t("place","invoices");
x.t("payment","void");
x.t("payment","range");
x.t("payment","mistake");
x.t("payment",":voiding");
x.t("payment","activant");
x.t("payment","voiding");
x.t("payable","balances");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("mistake","payment");
x.t(":voiding","payment");
x.t("activant","solutions");
x.t("reverse","g/l");
x.t("following","voiding");
x.t("866-878-0574","972-403-3150");
x.t("vendor","payment");
x.t("voiding","multiple");
x.t("voiding","payment");
x.t("invoices","back");
x.t("accounts","payable");
x.t("balances","void");
x.t("entries","place");
}
