function FileData_Pairs(x)
{
x.t("credit","register");
x.t("credit","report");
x.t("credit","reports");
x.t("credit","information");
x.t("register","open");
x.t("register","letter");
x.t("open","letter");
x.t("acceptance","cash");
x.t("requirements","report");
x.t("payable","reports");
x.t("report","l/c");
x.t("report","accounts");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("reports",":letters");
x.t("reports","include");
x.t("reports","activant");
x.t("reports","letters");
x.t("reports","following");
x.t(":letters","credit");
x.t("include","letter");
x.t("information","daily");
x.t("letter","credit");
x.t("activant","solutions");
x.t("letters","credit");
x.t("daily","letter");
x.t("cash","requirements");
x.t("following","accounts");
x.t("866-878-0574","972-403-3150");
x.t("l/c","acceptance");
x.t("accounts","payable");
}
