function FileData_Pairs(x)
{
x.t(":a/p","aging");
x.t("currency","a/p");
x.t("aging","report");
x.t("aging","reports");
x.t("aging","information");
x.t("multi","currency");
x.t("month","end");
x.t("payable","reports");
x.t("payable","month-end");
x.t("report","month");
x.t("report","accounts");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("reports",":a/p");
x.t("reports","include");
x.t("reports","a/p");
x.t("reports","activant");
x.t("reports","following");
x.t("end","multi");
x.t("end","a/p");
x.t("include","accounts");
x.t("information","month");
x.t("a/p","aging");
x.t("activant","solutions");
x.t("following","reports");
x.t("866-878-0574","972-403-3150");
x.t("month-end","aging");
x.t("accounts","payable");
}
