function  WWHBookData_Files(P)
{
P.fA("Maintenance Settings","opt_rnt.1.1.htm");
P.fA("Rental Sales Representatives","opt_rnt.1.2.htm");
P.fA("Rental Rate Method","opt_rnt.1.3.htm");
P.fA("Rental Start Date &amp; Time","opt_rnt.1.4.htm");
P.fA("Rental Lost/Damaged Quantity","opt_rnt.1.5.htm");
P.fA("Rental Contract Customer #","opt_rnt.1.6.htm");
P.fA("Rental Sales Tax","opt_rnt.1.7.htm");
P.fA("Rental Transactions","opt_rnt.1.8.htm");
P.fA("Returning Rentals to a Different Warehouse","opt_rnt.1.9.htm");
P.fA("Renting from a Vendor and Renting to a Customer","opt_rnt.1.10.htm");
P.fA("Partially Checking In a Rental Item","opt_rnt.1.11.htm");
P.fA("Exchanging Rental Items","opt_rnt.1.12.htm");
P.fA("Tracking Meter Readings","opt_rnt.1.13.htm");
P.fA("Rental Charges","opt_rnt.1.14.htm");
P.fA("Creating Codes","opt_rnt.1.15.htm");
P.fA("Environmental Charge Code Maintenance (/ECCM)","opt_rnt.1.16.htm");
P.fA("Fuel Type Maintenance (/FUTM)","opt_rnt.1.17.htm");
P.fA("Assigning Codes to Products","opt_rnt.1.18.htm");
P.fA("Assigning Codes to Customers","opt_rnt.1.19.htm");
P.fA("Assessing Charges in Rental Orders","opt_rnt.1.20.htm");
P.fA("Assessing Fuel Charges","opt_rnt.1.21.htm");
P.fA("Billing the Charges","opt_rnt.1.22.htm");
P.fA("Rental Equipment Subsystem","opt_rnt.1.23.htm");
P.fA("Entering Equipment Attachments (/EAE)","opt_rnt.1.24.htm");
P.fA("Maintenance Menu","opt_rnt.1.25.htm");
P.fA("Equipment Maintenance (/EM)","opt_rnt.1.26.htm");
P.fA("Equipment Statistical Information Maintenance (/ESIM)","opt_rnt.1.27.htm");
P.fA("Scheduled Maintenance Code Maintenance (/SMCM)","opt_rnt.1.28.htm");
P.fA("Inquiries","opt_rnt.1.29.htm");
P.fA("Fixed Assets Menu","opt_rnt.1.30.htm");
P.fA("Rental Financials","opt_rnt.1.31.htm");
P.fA("Product Maintenance (/PM)","opt_rnt.1.32.htm");
P.fA("Inventory Type Conversion Entry (/ITCE)","opt_rnt.1.33.htm");
P.fA("Asset Maintenance (/ASM)","opt_rnt.1.34.htm");
P.fA("Transfer Entry (/TE &amp; /ROE)","opt_rnt.1.35.htm");
P.fA("G/L Postings for Selling Rental Items","opt_rnt.1.36.htm");
P.fA("Rental Pre-Billing","opt_rnt.1.37.htm");
P.fA("Rental Parameters","opt_rnt.1.38.htm");
P.fA("Rental Order Entry (/ROE)","opt_rnt.1.39.htm");
P.fA("Release Confirmation (/RCE) &amp; Invoice Printing (/IP)","opt_rnt.1.40.htm");
P.fA("Rental Return \u2013 Rental Order Entry (/ROE)","opt_rnt.1.41.htm");
P.fA("Periodic Billing","opt_rnt.1.42.htm");
P.fA("Rental Parameters","opt_rnt.1.43.htm");
P.fA("Rental Order Entry (/ROE)","opt_rnt.1.44.htm");
P.fA("Periodic Billing","opt_rnt.1.45.htm");
P.fA("Periodic Billing Entry (/PBE)","opt_rnt.1.46.htm");
P.fA("Periodic Billing Report (/RENT.PERIODIC.RPT)","opt_rnt.1.47.htm");
P.fA("Invoice Processing (/IP)","opt_rnt.1.48.htm");
P.fA("Order Log Inquiry (/OLI)","opt_rnt.1.49.htm");
P.fA("Rental Rollup Billing","opt_rnt.1.50.htm");
P.fA("Rental Parameters","opt_rnt.1.51.htm");
P.fA("Rental Order Entry (/ROE)","opt_rnt.1.52.htm");
P.fA("Release Confirmation (/RCE) &amp; Invoice Printing (/IP)","opt_rnt.1.53.htm");
P.fA("Additional Rental Postings","opt_rnt.1.54.htm");
P.fA("Rent To Re-Rent Rental Order Posting","opt_rnt.1.55.htm");
}
