function FileData_Pairs(x)
{
x.t("inquiries","activant");
x.t("inquiries","following");
x.t("inquiries","vendor");
x.t("claim","inquiries");
x.t("claim","inquiry");
x.t("claim","history");
x.t("claim","log");
x.t(":vendor","claim");
x.t("open","vendor");
x.t("inquiry","vendor");
x.t("status","vendor");
x.t("warranty","replacements");
x.t("allow","view");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("view","status");
x.t("inquires","allow");
x.t("history","inquiry");
x.t("activant","solutions");
x.t("replacements",":vendor");
x.t("following","inquires");
x.t("866-878-0574","972-403-3150");
x.t("vendor","claim");
x.t("vendor","claims");
x.t("claims","open");
x.t("claims","warranty");
x.t("log","inquiry");
}
