function FileData_Pairs(x)
{
x.t("refer","following");
x.t("transfers","duplicating");
x.t("transfers","entering");
x.t("transfers","duplicate");
x.t("transfers",":duplicating");
x.t("transfers","activant");
x.t("open","transfer");
x.t("open","received");
x.t("duplicating","open");
x.t("duplicating","received");
x.t("duplicating","stock");
x.t("entering","stock");
x.t("duplicate","either");
x.t(":duplicating","stock");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("transfer","refer");
x.t("transfer","duplicating");
x.t("transfer","stock");
x.t("received","transfer");
x.t("received","stock");
x.t("activant","solutions");
x.t("stock","transfers");
x.t("stock","transfer");
x.t("either","open");
x.t("following","duplicating");
x.t("866-878-0574","972-403-3150");
}
