function FileData_Pairs(x)
{
x.t("tag","tag");
x.t("tag","inquiries");
x.t("tag","customer");
x.t("tag","inquiry");
x.t("tag","product");
x.t("tag","vendor");
x.t("inquiries","warranty");
x.t("inquiries","allow");
x.t("inquiries","activant");
x.t("inquiries","following");
x.t("inventory","warranty");
x.t("customer","inquiry");
x.t("inquiry","warranty");
x.t("inquiry","screen");
x.t("product","inquiry");
x.t(":warranty","tag");
x.t("products","warranty");
x.t("warranty","tag");
x.t("warranty","inventory");
x.t("warranty","replacements");
x.t("allow","view");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("view","detail");
x.t("screen","vendor");
x.t("information","products");
x.t("activant","solutions");
x.t("replacements",":warranty");
x.t("following","inquiries");
x.t("866-878-0574","972-403-3150");
x.t("vendor","inquiry");
x.t("vendor","claims");
x.t("claims","warranty");
x.t("detail","information");
}
