function FileData_Pairs(x)
{
x.t("inquiries","display");
x.t("inquiries","transfer");
x.t("inquiries","activant");
x.t("inquiries","following");
x.t("transfers",":transfer");
x.t("transfers","transfer");
x.t("product","quantity");
x.t("inquiry","transfer");
x.t("inquiry","stock");
x.t("display","product");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t(":transfer","inquiries");
x.t("transfer","inquiries");
x.t("transfer","inquiry");
x.t("transfer","history");
x.t("transfer","log");
x.t("information","transfers");
x.t("transaction","information");
x.t("history","inquiry");
x.t("activant","solutions");
x.t("stock","transfers");
x.t("following","transfer");
x.t("866-878-0574","972-403-3150");
x.t("log","inquiry");
x.t("quantity","transaction");
}
