function FileData_Pairs(x)
{
x.t(":counting","linked");
x.t("counted","linked");
x.t("refer","following");
x.t("asterisk","report");
x.t("counting","linked");
x.t("physical","inventory");
x.t("physical","linked");
x.t("inventory",":counting");
x.t("inventory","counted");
x.t("inventory","refer");
x.t("inventory","counting");
x.t("inventory","linked");
x.t("inventory","adjusting");
x.t("inventory","activant");
x.t("sections","adjust");
x.t("items","during");
x.t("during","physical");
x.t("non-stock","items");
x.t("linked","asterisk");
x.t("linked","inventory");
x.t("linked","non-stock");
x.t("linked","nonstock");
x.t("adjust","inventory");
x.t("adjusting","inventory");
x.t("report","physical");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("activant","solutions");
x.t("following","sections");
x.t("866-878-0574","972-403-3150");
x.t("nonstock","item");
x.t("item","physical");
}
