function FileData_Pairs(x)
{
x.t("counting","cycle");
x.t("counting",":setting");
x.t("counting","appropriate");
x.t("counting","activant");
x.t("counting","setting");
x.t("inventory","parameters");
x.t("count","control");
x.t("flags","following");
x.t("cycle","counting");
x.t("cycle","count");
x.t("parameters","warehouse");
x.t("programs","inventory");
x.t("cost","tolerance");
x.t("control","maintenance");
x.t("maintenance","cycle");
x.t("maintenance","programs");
x.t("maintenance","cost");
x.t("maintenance","bin");
x.t("maintenance","zone");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t(":setting","system");
x.t("bin","location");
x.t("tolerance","maintenance");
x.t("location","maintenance");
x.t("appropriate","flags");
x.t("zone","maintenance");
x.t("activant","solutions");
x.t("system","cycle");
x.t("following","maintenance");
x.t("866-878-0574","972-403-3150");
x.t("setting","system");
x.t("warehouse","maintenance");
}
