function FileData_Pairs(x)
{
x.t("inquiries","warranty");
x.t("inquiries","allow");
x.t("inquiries","activant");
x.t("inquiries","following");
x.t("open","updated");
x.t("suspended","warranty");
x.t("inquiry","suspended");
x.t("inquiry","completed");
x.t(":warranty","replacement");
x.t("warranty","replacement");
x.t("warranty","replacements");
x.t("completed","warranty");
x.t("allow","view");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("view","open");
x.t("replacement","inquiries");
x.t("replacement","inquiry");
x.t("replacement","entries");
x.t("history","inquiry");
x.t("activant","solutions");
x.t("replacements",":warranty");
x.t("replacements","history");
x.t("following","warranty");
x.t("866-878-0574","972-403-3150");
x.t("vendor","claims");
x.t("claims","warranty");
x.t("entries","warranty");
x.t("entries","vendor");
x.t("updated","warranty");
}
