function FileData_Pairs(x)
{
x.t("lists","open");
x.t("lists","delete");
x.t("lists","select");
x.t("lists",":deleting");
x.t("deleting","campaign");
x.t("press","enter");
x.t("marketing","campaigns");
x.t("marketing","campaign");
x.t("open","campaign");
x.t("delete","press");
x.t("delete","list");
x.t("delete","campaign");
x.t("list","deleting");
x.t("list","delete");
x.t("list","enter");
x.t("list","deletion");
x.t("list","activant");
x.t("campaigns","creating");
x.t("creating","marketing");
x.t("creating","campaign");
x.t("campaign","lists");
x.t("campaign","list");
x.t("campaign","system");
x.t("select","marketing");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("enter","delete");
x.t("enter","creating");
x.t("deletion","screen");
x.t("screen","delete");
x.t("activant","solutions");
x.t("system","campaign");
x.t("866-878-0574","972-403-3150");
x.t(":deleting","campaign");
}
