function  WWHBookData_Files(P)
{
P.fA("Purchasing Overview","Purchasing_Overview.1.1.htm");
P.fA("Purchase Orders","Entering_Purchase_Orders.2.1.htm");
P.fA("Creating a Purchase Order","Entering_Purchase_Orders.2.2.htm");
P.fA("Purchase Order Types","Entering_Purchase_Orders.2.3.htm");
P.fA("Starting or Editing a Purchase Order","Entering_Purchase_Orders.2.4.htm");
P.fA("Entering Purchase Order Header Information","Entering_Purchase_Orders.2.5.htm");
P.fA("Entering Products","Entering_Purchase_Orders.2.6.htm");
P.fA("Entering Comments","Entering_Purchase_Orders.2.7.htm");
P.fA("Manually Linking an Item","Entering_Purchase_Orders.2.8.htm");
P.fA("Splitting Line Items for Delivery Dates","Entering_Purchase_Orders.2.9.htm");
P.fA("Entering Line Item Thaw Dates","Entering_Purchase_Orders.2.10.htm");
P.fA("Merging With a Suspended Purchase Order","Entering_Purchase_Orders.2.11.htm");
P.fA("Completing a Purchase Order","Entering_Purchase_Orders.2.12.htm");
P.fA("Duplicating a Purchase Order","Entering_Purchase_Orders.2.13.htm");
P.fA("Duplicating Open Purchase Orders","Entering_Purchase_Orders.2.14.htm");
P.fA("Duplicating Received Purchase Orders","Entering_Purchase_Orders.2.15.htm");
P.fA("Deleting A Purchase Order","Entering_Purchase_Orders.2.16.htm");
P.fA("Printing Purchase Orders","pop.htm");
P.fA("Costing Purchase Orders","Entering_Purchase_Orders.2.18.htm");
P.fA("Identifying Purchase Order Source Codes","Entering_Purchase_Orders.2.19.htm");
P.fA("Setting up Discount Break Tables","Entering_Purchase_Orders.2.20.htm");
P.fA("Using Discount Tables in Vendor Line Maintenance","Entering_Purchase_Orders.2.21.htm");
P.fA("Re-costing Purchase Orders","Entering_Purchase_Orders.2.22.htm");
P.fA("Entering a Purchase Requisition","Entering_Purchase_Orders.2.23.htm");
P.fA("Purchase Order Inquiries","Entering_Purchase_Orders.2.24.htm");
P.fA("Purchase Order Inquiry","poi.htm");
P.fA("Purchase Order History Inquiry","pohi.htm");
P.fA("Purchase Order Log Inquiry","pli.htm");
P.fA("Nightly Processing","Nightly_Processing.3.1.htm");
P.fA("Setup Requirements for Nightly Processing","Nightly_Processing.3.2.htm");
P.fA("Including Future Price Increases","Nightly_Processing.3.3.htm");
P.fA("Rounding to Package Quantities","Nightly_Processing.3.4.htm");
P.fA("Rounding to Package Quantities on Transfers","Nightly_Processing.3.5.htm");
P.fA("Faxing Vendor Expedite Reports","Nightly_Processing.3.6.htm");
P.fA("Assigning a Primary Vendor","Nightly_Processing.3.7.htm");
P.fA("Defining Nightly Purchasing Reports to Print","Nightly_Processing.3.8.htm");
P.fA("Assigning Printers For Nightly Processing","Nightly_Processing.3.9.htm");
P.fA("Setting the Warehouse Sequence for Displays","Nightly_Processing.3.10.htm");
P.fA("Including Suspended, Linked Sales Orders","Nightly_Processing.3.11.htm");
P.fA("Setting the Maximum Number of Lead Time Days","Nightly_Processing.3.12.htm");
P.fA("Nightly Processing Procedures","Nightly_Processing.3.13.htm");
P.fA("Running Nightly Processing","Nightly_Processing.3.14.htm");
P.fA("Scheduling Nightly Processing","Nightly_Processing.3.15.htm");
P.fA("Daily Processing Procedures","Nightly_Processing.3.16.htm");
P.fA("Running Daily Processing","Nightly_Processing.3.17.htm");
P.fA("Scheduling Daily Processing","Nightly_Processing.3.18.htm");
P.fA("Nightly Processing Inquiries","Nightly_Processing.3.19.htm");
P.fA("Line Buy Discount Inquiry","line_buy_disc_inq.htm");
P.fA("Product Discount Inquiry","prod_disc_inq.htm");
P.fA("Nightly Processing Inquiry","np_inq.htm");
P.fA("Nightly Processing Process Inquiry","np_process_inq.htm");
P.fA("Nightly Processing Reports","Nightly_Processing_Reports.4.1.htm");
P.fA("Future Commitment Now Committed Report","future_commit_rpt.htm");
P.fA("Manual Purchasing Requirements Report","nonstk_misc_rpt.htm");
P.fA("Manual Work Order Requirements Report","man_wo_req_rpt.htm");
P.fA("Line Buy Target Audit Report","line_buy_excpt.htm");
P.fA("Recommended Purchase Order Action Report","po_act_rpt.htm");
P.fA("Family Replenishment Report","family_report.htm");
P.fA("Recommended P/O Report","rec_po_rpt.htm");
P.fA("Recommended Drop Ship P/O Report","rec_po_ds_rpt.htm");
P.fA("Recommended Stock Transfer Report","rec_trn_rpt.htm");
P.fA("Recommended Work Order Report","rec_wo_rpt.htm");
P.fA("Recommended Maintenance Work Order Report","rec_wm_rpt.htm");
P.fA("Low Level Expedite Report","exp_1_rpt.htm");
P.fA("High Level Expedite Report","Nightly_Processing_Reports.4.14.htm");
P.fA("Work Order Expedite Report","wo_exp_rpt.htm");
P.fA("Nightly Negative Onhand Report","neg_oh_nightly_rpt.htm");
P.fA("Nightly Processing Error Report","error_report.htm");
P.fA("Pending Override Cancellation Report","week_pend_can_rpt.htm");
P.fA("Faxing the Vendor Expedite Report","Nightly_Processing_Reports.4.19.htm");
P.fA("PrePrice Increase Report","preprice_rpt.htm");
P.fA("Buyer Queue Inquiry","Buyer_Functions.5.1.htm");
P.fA("Setting Up a Buyer","Buyer_Functions.5.2.htm");
P.fA("Buyer Queue Inquiry","bqi.htm");
P.fA("Emergency/Direct Line Items","emg_dir_line_items.htm");
P.fA("Recommended Purchase Orders","recommended_purchase_orders.htm");
P.fA("Suspended Purchase Orders","susp_po.htm");
P.fA("Purchase Order Expedite","po_expedite_items.htm");
P.fA("Recommended Work Orders","recommended_wo.htm");
P.fA("Recommended Stock Transfers","recommended_stock_transfer_inq.htm");
P.fA("Vendor Claims","vendor_claim_inq.htm");
P.fA("Purchase Requisitions","purch_req_conv.htm");
P.fA("Vendor Request for Quotes","bqi_vrfq_buyer_inq.htm");
P.fA("Product Alerts","product_alerts.htm");
P.fA("Purchase Hold Release","purch_hold_rel_inq.htm");
P.fA("Purchase Parameters Skipped","purch_param_skipped_items.htm");
P.fA("Accounts Payable Discrepancy Inquiry","ap_discr_inq.htm");
P.fA("Stock Receipts Discrepancy","stock_rec_discr_inq.htm");
P.fA("EDI Freight Invoice","edi_frt_inv_inq.htm");
P.fA("Linked P/O Changes","linked_po_inq.htm");
P.fA("Vendors","Vendors.6.1.htm");
P.fA("Vendor Maintenance","vm.htm");
P.fA("Vendor Maintenance Screen","Vendors.6.3.htm");
P.fA("Additional Information Screen","vm_add_info.htm");
P.fA("Additional Keywords Screen","vm_add_keywords.htm");
P.fA("Warranty Information Screen","vm_warranty_info.htm");
P.fA("Vendor Return Rules Screen","vm_vend_ret_rules.htm");
P.fA("Import Information Screen","vm_import_info.htm");
P.fA("Vendor Currency Screen","vm_vend_currency.htm");
P.fA("Rebate Maintenance Screen","vend_rebate_mnt.htm");
P.fA("A/P Information Screen","vm_ap_info.htm");
P.fA("Vendor G/L Information Screen","vm_vendor_gl_info.htm");
P.fA("Cash Discount G/L Information Screen","vm_cash_disc_gl_info.htm");
P.fA("Current Year 1099 Information Screen","vm_current_yr_1099.htm");
P.fA("Previous Year 1099 Information Screen","vm_prev_yr_1099.htm");
P.fA("Vendor Contacts Screen","vm_vend_contacts.htm");
P.fA("Vendor Additional Contacts Screen","vm_vend_add_contacts.htm");
P.fA("Vendor Statistics Screen","vm_vend_statistics.htm");
P.fA("Contact Vendor Entry screen","contact_vendor_entry.htm");
P.fA("Label Information Screen","vm_label_info.htm");
P.fA("Vendor Product Types Screen","vm_vendor_prod_types.htm");
P.fA("Bank Information Screen","vm_bank_info.htm");
P.fA("Instructions Screen","vm_instructions.htm");
P.fA("Vendor VIA Properties Screen","vm_ecom_info.htm");
P.fA("Vendor Ship-From Maintenance","vsfm.htm");
P.fA("Vendor Ship-To Maintenance","vstm.htm");
P.fA("Vendor Line Maintenance","vlm.htm");
P.fA("Vendor Line Maintenance Screen","Vendors.6.28.htm");
P.fA("Vendor Line Target Parameters Screen","vlm_targ_param.htm");
P.fA("Vendor Line Targets - Additional Information Screen","vlm_add_info.htm");
P.fA("Vendor Line Statistics Screen","vlm_statistics.htm");
P.fA("Vendor Line Comments Inquiry","vend_line_comm_inq.htm");
P.fA("Creating and Assigning Vendor Type Codes","Vendors.6.33.htm");
P.fA("Creating and Assigning Vendor Product Types","Vendors.6.34.htm");
P.fA("Creating and Assigning Vendor Discount Codes","Vendors.6.35.htm");
P.fA("Creating On-Discount Codes","Vendors.6.36.htm");
P.fA("Creating Off-Discount Codes","Vendors.6.37.htm");
P.fA("Maintaining Vendor Keywords","Vendors.6.38.htm");
P.fA("Maintaining Import Cost Factors","Vendors.6.39.htm");
P.fA("Tracking Vendor Performance","Vendors.6.40.htm");
P.fA("Rebuilding Vendor Performance Statistics","Vendors.6.41.htm");
P.fA("Vendor Performance Inquiry","vend_perf_inq.htm");
P.fA("Vendor Cost/Delivery Comparison Inquiry","vend_cost_del_comp_inq.htm");
P.fA("Freight","Freight.7.1.htm");
P.fA("Allocating Inbound Freight to Average Cost","Freight.7.2.htm");
P.fA("Estimating Average Cost for Freight Charges","Freight.7.3.htm");
P.fA("Applying Estimated Freight to P/Os and Receivers","Freight.7.4.htm");
P.fA("Entering Freight Rates","Freight.7.5.htm");
P.fA("Entering a Freight Rate for a Product","Freight.7.6.htm");
P.fA("Entering a Freight Rate for a Vendor Line","Freight.7.7.htm");
P.fA("Entering a Freight Rate Matrix For a Product Line","Freight.7.8.htm");
P.fA("Freight Matrix Inquiry","fmi.htm");
P.fA("Entering Freight Terms Codes","Freight.7.10.htm");
P.fA("Vendor Request for Quote Subsystem","Vendor_RFQ_Subsystem.8.1.htm");
P.fA("Entering a Vendor RFQ","Vendor_RFQ_Subsystem.8.2.htm");
P.fA("Starting or Editing a Vendor RFQ","Vendor_RFQ_Subsystem.8.3.htm");
P.fA("Entering Products on a Vendor RFQ","Vendor_RFQ_Subsystem.8.4.htm");
P.fA("Generating a Vendor Release","Vendor_RFQ_Subsystem.8.5.htm");
P.fA("Printing a Vendor RFQ","Vendor_RFQ_Subsystem.8.6.htm");
P.fA("Entering Responses from Vendor RFQs","Vendor_RFQ_Subsystem.8.7.htm");
P.fA("Comparing Vendor Quotes","vrfq_compare_rpt.htm");
P.fA("Converting a Vendor RFQ to a Purchase Order","Vendor_RFQ_Subsystem.8.9.htm");
P.fA("Creating a Vendor RFQ From a Sales Quote","Vendor_RFQ_Subsystem.8.10.htm");
P.fA("Vendor RFQ Inquiries","Vendor_RFQ_Subsystem.8.11.htm");
P.fA("Open RFQ Inquiry by Product","open_rfq_inq_by_prod.htm");
P.fA("RFQ History Inquiry by Product","vrfq_hist_inq_by_prod.htm");
P.fA("Open RFQ Release Inquiry","open_rfq_rel_inq.htm");
P.fA("RFQ Release History Inquiry","vrfq_rel_hist_inq.htm");
P.fA("Vendor RFQ Release By Written By Inquiry","vrfq_rel_by_written_inq.htm");
P.fA("Vendor RFQ By Buyer Inquiry","vrfq_by_buyer_inq.htm");
P.fA("Blanket Purchase Order Subsystem","Blanket_Purchase_Order_Subsystem.9.1.htm");
P.fA("Entering a Blanket Purchase Order","Blanket_Purchase_Order_Subsystem.9.2.htm");
P.fA("Duplicating a Blanket Purchase Order","Blanket_Purchase_Order_Subsystem.9.3.htm");
P.fA("Printing Blanket Purchase Orders","blpop.htm");
P.fA("Using Blanket P/Os in Purchase Order Entry","Blanket_Purchase_Order_Subsystem.9.5.htm");
P.fA("Blanket Purchase Order Reports","Blanket_Purchase_Order_Subsystem.9.6.htm");
P.fA("Blanket Purchase Order Detail Report","bl_po_dtl_rpt.htm");
P.fA("Blanket Purchase Order Summary Report","bl_po_summ_rpt.htm");
P.fA("Blanket Purchase Order Expiration Report","bl_po_exp_rpt.htm");
P.fA("Blanket Purchase Order Inquiry","blank_po_inq.htm");
P.fA("Purchasing Reports","Purchasing_Reports.10.1.htm");
P.fA("Purchase Order / Vendor Report","open_po_pline_rpt.htm");
P.fA("Open Purchase Order Detail Report","open_po_rpt.htm");
P.fA("Open On The Water Purchase Order Detail Report","open_otw_po_rpt.htm");
P.fA("Overdue Purchase Order Report","over_po_rpt.htm");
P.fA("Purchase Order Log Report","po_log_rpt.htm");
P.fA("P/O Vendor Exception Report","po_vend_except_rpt.htm");
P.fA("Company Wide Product Analysis Report","po_import_rpt.htm");
P.fA("Deleted Purchase Orders Report","deleted_po_rpt.htm");
P.fA("P/O Inventory Shortage Report","inv_short_rpt.htm");
P.fA("P/O Extended Evaluation Report","poev_rpt.htm");
P.fA("Surplus Report","surplus_rpt.htm");
P.fA("Surplus Inventory Audit Report","surplus_audit_rpt.htm");
P.fA("Sourcing Variance Report","src_var_rpt.htm");
P.fA("Surplus Report with On Order Merchandise","surplus_onord_rpt.htm");
P.fA("Inventory Analysis Report","inventory_anal_rpt.htm");
P.fA("Service Level Measurement Report","service_level_rpt.htm");
P.fA("Frozen Control Thaw Date Report","frz_thaw_rpt.htm");
P.fA("Vendor Return Rules Report","returns_rpt.htm");
P.fA("Confirmed/Expedite Date Exception Report","cfm_except_rpt.htm");
P.fA("Vendor Line Turns Report","new_vend_line_turn_rpt.htm");
P.fA("Vendor Line Turn By Buyer Report","vend_line_summ_rpt.htm");
P.fA("Turns Report By Warehouse","vend_turn_whse_rpt.htm");
P.fA("Turns Report By Product Line/Warehouse","vend_turn_pline_rpt.htm");
P.fA("Turns Report By Vendor/Warehouse","vend_turn_vend_rpt.htm");
P.fA("Emergency Purchasing Requirements Report","emg_po_req_rpt.htm");
P.fA("Vendor Maintenance Audit Report by User Id","vend_audit_rpt.htm");
P.fA("Vendor Maintenance Audit Report by Vendor","vend_audit_vn_rpt.htm");
P.fA("Lead Time Trends Report","lead_time_trend_rpt.htm");
P.fA("Fill Rate Summary Report by Buyer/Planner","ord_fill_rate_hdr_rpt.htm");
P.fA("Fill Rate Detail Report","ord_fill_rate_det_rpt.htm");
P.fA("Fill Rate by Product Report","fill_rate_pn_rpt.htm");
P.fA("Fill Rate by Product Line Report","fill_rate_pline_rpt.htm");
P.fA("Fill Rate Report By Vendor","fill_rate_vend_rpt.htm");
P.fA("Customer Fill Rate Report","cust_fill_rate_rpt.htm");
P.fA("Vendor Rebate Report","vend_reb_det_rpt.htm");
P.fA("Field Definitions by screen","pre_header_add_info.htm");
P.fA("Add\u2019l Qty screen","vrfq_det_info_add_qty.htm");
P.fA("Alternate Buyer Screen","alternate_buyer.htm");
P.fA("Alternate Buyer Assignment Screen","alt_buyer.htm");
P.fA("Authorized Warehouses screen","vsfm_auth_whses.htm");
P.fA("Blanket P/O Availability screen","blank_po_avail.htm");
P.fA("Blanket P/O Detail Information screen","bpoe_det_info.htm");
P.fA("Blanket P/O Header screen","bpoe_header.htm");
P.fA("Blanket P/O Release Inq screen","blank_po_rel_inq.htm");
P.fA("Blanket Purchase Order Entry screen","bpoe.htm");
P.fA("Blanket Purchase Order Print screen","blank_po_print.htm");
P.fA("Blanket Purchase Order Review screen","blank_po_rev.htm");
P.fA("Buyer Maintenance screen","bm.htm");
P.fA("Comment Description Entry screen","poe_comment_desc_entry.htm");
P.fA("Contacts Maintenance screen","contacts_maint.htm");
P.fA("Daily Processing screen","dp.htm");
P.fA("Daily Processing Execute Report List screen","dp_execute_rpt_list.htm");
P.fA("Daily Purchasing Process screen","daily_process.htm");
P.fA("Deleted Reason Code screen","poe_del_reason_code.htm");
P.fA("Delivery Log Entry screen","del_inq.htm");
P.fA("Delivery Log Entry screen (F6-New Entry)","field_def.11.21.htm");
P.fA("Detail Information Screen","po_req_ent_line.htm");
P.fA("Discount Break Table Maintenance screen","dbtm.htm");
P.fA("Discount Table - Percent screen","dbtm_break_table_percent.htm");
P.fA("Discount Table - Dollar screen","dbtm_break_table_price.htm");
P.fA("Duplicate Blanket P/O screen","bpoe_dup.htm");
P.fA("Emergency/Direct Buyer Inquiry Review screen","emg_dir_buyer_inq_rev.htm");
P.fA("Freight Closeout screen","freight_closeout.htm");
P.fA("Freight Closeout Display screen","freight_closeout_disp.htm");
P.fA("Freight Invoice Detail Inquiry screen","freight_inv_det_inq.htm");
P.fA("Freight Matrix Maintenance screen","fmm.htm");
P.fA("Freight Terms Code Maintenance screen","freight_terms_code_mnt.htm");
P.fA("Freight Tracking screen","po_frt_trk_ent.htm");
P.fA("Generate P/O\u2019s For Vendor RFQ screen","vrfq_conv_gen_po.htm");
P.fA("Generate Purchase Orders screen","emg_dir_bi_gen_po.htm");
P.fA("Import Codes screen","poe_import_codes.htm");
P.fA("Import Cost Factor Maintenance screen","import_cost_factor_mnt.htm");
P.fA("Letter of Credit Display screen","loc_display.htm");
P.fA("Line Item Quality Control screen","line_item_quality_control.htm");
P.fA("Mass W/O Conversion screen","mass_wo_conv.htm");
P.fA("Merge With Suspended P/O screen","poe_merge_susp_po.htm");
P.fA("New Vendor Number screen","new_vendor_number.htm");
P.fA("Nightly Processing Execute Report List screen","np_execute_rpt_list.htm");
P.fA("Nightly Processing screen","np.htm");
P.fA("Nightly Purchasing Process screen","nightly_process.htm");
P.fA("P/O Additional Info screen","poe_det_info_add_info.htm");
P.fA("P/O Additional Information screen","poe_header_add_info.htm");
P.fA("P/O Deletion Reason Code Maintenance screen","po_del_reason_code_mnt.htm");
P.fA("P/O Detail Information screen","poe_det_info.htm");
P.fA("P/O Duplication Entry screen","poe_dup_entry.htm");
P.fA("P/O History Duplication Entry screen","poe_history_dup_entry.htm");
P.fA("PO Split Lines screen","poe_split_lines.htm");
P.fA("P/O Vendor Line Evaluation screen","po_vendor_line_evaluation.htm");
P.fA("Purchase Order Conversion Entry screen","po_conv_entry.htm");
P.fA("Purchase Order Display screen","po_display.htm");
P.fA("Purchase Order Entry screen","poe.htm");
P.fA("Purchase Order Header screen","poe_header.htm");
P.fA("Purchase Order History Display screen","po_history_display.htm");
P.fA("Purchase Order Linkage screen","poe_linkage.htm");
P.fA("Purchase Order Linkage Deletion screen","poe_linkage_del.htm");
P.fA("Purchase Requisition Entry screen","pre.htm");
P.fA("Purchase Order Requisition Header screen","pre_header.htm");
P.fA("Purchase Order Review screen","po_review.htm");
P.fA("Quote Entry Detail screen","qoe_detail.htm");
P.fA("Quote RFQ Vendor Selection screen","quote_rfq_vendor_selection.htm");
P.fA("Recommended P/O Inquiry screen","rec_po_inq.htm");
P.fA("Request for Quotation Entry screen","qoe_det_request_for_quote.htm");
P.fA("Request for Quote Inquiry screen","vrfq_inq.htm");
P.fA("RFQ Detail Information screen","qoe_rfq_det_info.htm");
P.fA("RFQ Header screen","qoe_rfq_header.htm");
P.fA("Ship-From Address screen","ship_from_address.htm");
P.fA("Ship-To Address screen","ship_to_address.htm");
P.fA("Target Information screen","po_conversion_target_info.htm");
P.fA("Transfer Conversion Entry screen","tc_ent.htm");
P.fA("Transfer Entry Detail screen","tc_ent_line.htm");
P.fA("Vendor Detail Information screen","vrfq_conversion_vend_det.htm");
P.fA("Vendor Discount Code Maintenance screen","vdcm.htm");
P.fA("Vendor History Detail Information screen","vend_hist_det_info.htm");
P.fA("Vendor ISO Information screen","vendor_iso_info.htm");
P.fA("Vendor Keyword Maintenance screen","vend_keyword_mnt.htm");
P.fA("Vendor Performance Rebuild screen","vend_perf_rebuild.htm");
P.fA("Vendor Product Type Maintenance screen","vend_prod_types_mnt.htm");
P.fA("Vendor Request For Quote screen","vrfq.htm");
P.fA("Vendor RFQ Conversion screen","vrfq_conversion.htm");
P.fA("Vendor RFQ Employee Inquiry","vrfq_wb_inq.htm");
P.fA("Vendor RFQ Printing screen","vrfq_print.htm");
P.fA("Vendor RFQ Response Entry screen","vrfq_response_entry.htm");
P.fA("Vendor Type Code Maintenance screen","vend_type_code_mnt.htm");
P.fA("Vendor Verification screen","vendor_verify.htm");
P.fA("VRFQ Additional Information screen","vrfq_det_info_add_info.htm");
P.fA("VRFQ Detail Information screen","vrfq_det_info.htm");
P.fA("VRFQ Duplicate screen","vrfq_duplicate.htm");
P.fA("VRFQ Header Information screen","vrfq_header.htm");
P.fA("VRFQ Release Header screen","vrfq_response_header.htm");
P.fA("VRFQ Release History Inquiry screen","vrfq_release_hist_inq.htm");
P.fA("VRFQ Response Detail Information screen","vrfq_response_det_info.htm");
}
