function  WWHBookData_Files(P)
{
P.fA("Overview","tpcx_ovr.1.1.htm");
P.fA("What is Trading Partner Connect?","tpcx_ovr.1.2.htm");
P.fA("How Does TPCx Work?","tpcx_ovr.1.3.htm");
P.fA("Creating Trading Partner Relationships","tpcx_ovr.1.4.htm");
P.fA("Rationalizing Items","tpcx_ovr.1.5.htm");
P.fA("Using Prelude with TPCx","tpcx_prelude.2.1.htm");
P.fA("Setting Up Prelude","tpcx_prelude.2.2.htm");
P.fA("Company Maintenance","company_tpcx.htm");
P.fA("Web User Maintenance","tpcx_prelude.2.4.htm");
P.fA("Warehouse Maintenance","tpcx_info_wm.htm");
P.fA("Product Maintenance","tpcx_info_pm.htm");
P.fA("Customer Maintenance","tpcx_info_cm.htm");
P.fA("Vendor Maintenance","tpcx_info_vm.htm");
P.fA("Viewing Availability on the Hub","tpcx_pa_loc.htm");
P.fA("Buying Stock from the Hub","tpcx_pa_ent.htm");
P.fA("Sharing Data with TPCx","tpcx_prelude.2.11.htm");
P.fA("Defining TPCx Partners","tpcx_prelude.2.12.htm");
P.fA("Sending and Receiving TPCx Data","tpcx_prelude.2.13.htm");
P.fA("Uploading Dead Stock to the Hub","tpcx_prelude.2.14.htm");
P.fA("Selecting Dead Stock","tpcx_dead_stock_rpt.htm");
P.fA("Viewing Dead Stock","tpcx_dead_stock.htm");
P.fA("Using the TPCx Website","tpcx_website.3.1.htm");
P.fA("Sign In","tpcx_website.3.2.htm");
P.fA("Home Page","tpcx_website.3.3.htm");
P.fA("Company Profile","tpcx_website.3.4.htm");
P.fA("Relationships","tpcx_website.3.5.htm");
P.fA("Document Tracking","tpcx_website.3.6.htm");
P.fA("Inventory","tpcx_website.3.7.htm");
P.fA("Item Rationalization","tpcx_website.3.8.htm");
P.fA("Rationalizing Items","tpcx_website.3.9.htm");
P.fA("Reviewing Rationalization Results","tpcx_website.3.10.htm");
P.fA("Pricing &amp; Availability","tpcx_website.3.11.htm");
P.fA("Reporting","tpcx_website.3.12.htm");
P.fA("Dead Stock","tpcx_website.3.13.htm");
P.fA("Dead Stock Search","tpcx_website.3.14.htm");
P.fA("Data Mining Report","tpcx_website.3.15.htm");
P.fA("Unpost Dead Stock","tpcx_website.3.16.htm");
P.fA("Reporting","tpcx_website.3.17.htm");
P.fA("Searching Online Help","tpcx_website.3.18.htm");
P.fA("Frequently Asked Questions","tpcx_faqs.htm");
}
