function FileData_Pairs(x)
{
x.t("contact","activant");
x.t("greets","first");
x.t("visit","trading");
x.t("sign","sign");
x.t("sign","page");
x.t("tpcx","website");
x.t("first","visit");
x.t("issues","using");
x.t("trading","partner");
x.t("partner","connect");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("assigned","activant");
x.t("website",":sign");
x.t("website","passwords");
x.t("page","greets");
x.t(":sign","activant");
x.t("activant","contact");
x.t("activant","solutions");
x.t("activant","password");
x.t("866-878-0574","972-403-3150");
x.t("connect","website");
x.t("passwords","assigned");
x.t("using","tpcx");
x.t("password","issues");
}
