function FileData_Pairs(x)
{
x.t("user","maintenance");
x.t("customer","maintenance");
x.t("product","maintenance");
x.t("web","user");
x.t("tpcx","setup");
x.t("tpcx",":setting");
x.t("tpcx","data");
x.t("prelude","tpcx");
x.t("prelude","prelude");
x.t("prelude","activant");
x.t("prelude","setting");
x.t("setup","data");
x.t("maintenance","customer");
x.t("maintenance","product");
x.t("maintenance","web");
x.t("maintenance","show");
x.t("maintenance","vendor");
x.t("maintenance","warehouse");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t(":setting","prelude");
x.t("show","tpcx");
x.t("data","using");
x.t("data","company");
x.t("activant","solutions");
x.t("866-878-0574","972-403-3150");
x.t("setting","prelude");
x.t("vendor","maintenance");
x.t("using","prelude");
x.t("company","maintenance");
x.t("warehouse","maintenance");
}
