function FileData_Pairs(x)
{
x.t("available","www.tpcx.com");
x.t("profitability","trading");
x.t("refer","overview");
x.t("events","using");
x.t("overview","important");
x.t("potential","profitability");
x.t("account","information");
x.t("tpcx","website");
x.t("regarding","importance");
x.t("www.tpcx.com","website");
x.t("trading","partner");
x.t("partner","relationships");
x.t("partner","connect");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("section","refer");
x.t("important","information");
x.t("upcoming","events");
x.t("login","account");
x.t("website","available");
x.t("website","login");
x.t("website","read");
x.t("website","activant");
x.t("website","using");
x.t("importance","trading");
x.t("read","section");
x.t("information","regarding");
x.t("information","trading");
x.t("activant","solutions");
x.t("relationships","potential");
x.t("866-878-0574","972-403-3150");
x.t("using","tpcx");
x.t("connect","trading");
x.t("connect","upcoming");
x.t("connect","website");
}
