function FileData_Pairs(x)
{
x.t("example","create");
x.t("create","user");
x.t("create","web");
x.t("user","spoke01");
x.t("user","maintenance");
x.t("user","spoke");
x.t("e-commerce","via");
x.t("sure","include");
x.t("via","web");
x.t("spoke01","sure");
x.t("web","user");
x.t("web","user\u2019s");
x.t("tpcx","system");
x.t("tpcx","setting");
x.t("number","company");
x.t("prelude","tpcx");
x.t("prelude",":web");
x.t("maintenance","example");
x.t("maintenance","create");
x.t("maintenance","web");
x.t("maintenance","activant");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("spoke","e-commerce");
x.t("include","tpcx");
x.t(":web","user");
x.t("activant","solutions");
x.t("system","number");
x.t("866-878-0574","972-403-3150");
x.t("using","prelude");
x.t("setting","prelude");
x.t("company","maintenance");
x.t("user\u2019s","using");
}
