function FileData_Pairs(x)
{
x.t("available","items");
x.t("refer","setting");
x.t("once","license");
x.t("items","share");
x.t("items","buy");
x.t("license","tpcx");
x.t("availability","hub");
x.t("tpcx","once");
x.t("tpcx","prelude");
x.t("tpcx","view");
x.t("tpcx","information");
x.t("tpcx","activant");
x.t("tpcx","using");
x.t("sharing","data");
x.t("prelude","tpcx");
x.t("prelude","viewing");
x.t("prelude","work");
x.t("viewing","availability");
x.t("share","data");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("view","information");
x.t("information","available");
x.t("information","refer");
x.t("data","tpcx");
x.t("buying","stock");
x.t("hub","sharing");
x.t("hub","buying");
x.t("buy","items");
x.t("activant","solutions");
x.t("work","tpcx");
x.t("stock","hub");
x.t("866-878-0574","972-403-3150");
x.t("using","prelude");
x.t("setting","prelude");
}
