function FileData_Pairs(x)
{
x.t("inquiries","display");
x.t("inquiries","shop");
x.t("inquiries","activant");
x.t("inquiries","following");
x.t(":shop","repair");
x.t("open","quote");
x.t("inquiry","quote");
x.t("inquiry","shop");
x.t("quotes","open");
x.t("display","information");
x.t("quote","inquiries");
x.t("quote","subsystem");
x.t("quote","repair");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("shop","quote");
x.t("shop","repair");
x.t("subsystem",":shop");
x.t("information","shop");
x.t("history","inquiry");
x.t("activant","solutions");
x.t("repair","inquiry");
x.t("repair","quotes");
x.t("repair","quote");
x.t("repair","history");
x.t("following","inquiries");
x.t("866-878-0574","972-403-3150");
}
