function FileData_Pairs(x)
{
x.t("refer","following");
x.t("job","adding");
x.t("line","items");
x.t(":entering","shop");
x.t("editing","line");
x.t("editing","shop");
x.t("items","changing");
x.t("entering","job");
x.t("entering","quote");
x.t("entering","shop");
x.t("procedures","information");
x.t("quote","refer");
x.t("quote","entering");
x.t("quote","starting");
x.t("quote","subsystem");
x.t("quote","activant");
x.t("quote","adding");
x.t("starting","editing");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("shop","quote");
x.t("shop","repair");
x.t("changing","totals");
x.t("saving","quote");
x.t("totals","saving");
x.t("subsystem",":entering");
x.t("information","entering");
x.t("taxes","shop");
x.t("activant","solutions");
x.t("repair","quote");
x.t("fees","taxes");
x.t("following","procedures");
x.t("866-878-0574","972-403-3150");
x.t("adding","editing");
x.t("adding","fees");
}
