function FileData_Pairs(x)
{
x.t("shop/repair","manager");
x.t("taking","payment");
x.t("refer","following");
x.t(":completing","order");
x.t("once","repair");
x.t("user","maintenance");
x.t("orders",":completing");
x.t("complete","refer");
x.t("complete","procedures");
x.t("completing","jobs");
x.t("completing","order");
x.t("procedures","shop/repair");
x.t("payment","order");
x.t("maintenance","shop");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("steps","information");
x.t("shop","repair");
x.t("(optional)","complete");
x.t("manager","user");
x.t("information","completing");
x.t("taxes","taking");
x.t("jobs","adding");
x.t("activant","solutions");
x.t("repair","orders");
x.t("repair","work");
x.t("work","complete");
x.t("fees","taxes");
x.t("order","once");
x.t("order","completing");
x.t("order","(optional)");
x.t("order","activant");
x.t("following","steps");
x.t("866-878-0574","972-403-3150");
x.t("adding","fees");
}
