function FileData_Pairs(x)
{
x.t("clock","inquiries");
x.t("clock","entry");
x.t("shop/repair","timeclock");
x.t("inquiries","shop");
x.t("inquiries","activant");
x.t("inquiries","following");
x.t("technician","job");
x.t(":shop","repair");
x.t("billing",":shop");
x.t("billing","inquiry");
x.t("job","billing");
x.t("time","clock");
x.t("inquiry","technician");
x.t("inquiry","time");
x.t("entry","billing");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("reports","view");
x.t("timeclock","inquiry");
x.t("timeclock","information");
x.t("shop","repair");
x.t("view","timeclock");
x.t("inquires","reports");
x.t("information","shop/repair");
x.t("activant","solutions");
x.t("repair","time");
x.t("following","inquires");
x.t("866-878-0574","972-403-3150");
}
