function  WWHBookData_Files(P)
{
P.fA("Overview","overview.1.1.htm");
P.fA("Setting Marketing Maintenance Options","mnt.2.1.htm");
P.fA("Setting Marketing Option Parameters","mnt.2.2.htm");
P.fA("Selecting Files to Update","mnt.2.3.htm");
P.fA("Assigning Job Titles to Contacts","mnt.2.4.htm");
P.fA("Using Potential Codes","mnt.2.5.htm");
P.fA("Identifying Source Codes","mnt.2.6.htm");
P.fA("Using SICs","mnt.2.7.htm");
P.fA("Assigning Territory Codes","mnt.2.8.htm");
P.fA("Maintaining Sales Representatives","mnt.2.9.htm");
P.fA("Sales Representative Maintenance screen","srm.htm");
P.fA("Salesman Performance Planning screen","srm_perf_plan.htm");
P.fA("Identifying Diary Codes","mnt.2.12.htm");
P.fA("Establishing Product Views","mnt.2.13.htm");
P.fA("Setting up Competitor Codes","mnt.2.14.htm");
P.fA("Establishing Custom Fields","mnt.2.15.htm");
P.fA("Setting Up Catalogs/Literature Codes","mnt.2.16.htm");
P.fA("Creating Activity Codes","mnt.2.17.htm");
P.fA("Maintaining Form Letters","mnt.2.18.htm");
P.fA("Setting Up Activity Defaults","mnt.2.19.htm");
P.fA("Setting up Prospects and Contacts","prospects_contacts.3.1.htm");
P.fA("Setting up Prospect Accounts","prospects_contacts.3.2.htm");
P.fA("Prospect Maintenance screen","tme.htm");
P.fA("Prospect Additional Info Screen","tme_add_info.htm");
P.fA("Prospect Keywords screen","tme_keywords.htm");
P.fA("Competitor Information screen","tme_competitor.htm");
P.fA("Sales Potential screen","tme_sales_potential.htm");
P.fA("Product Line Objectives screen","tme_pline_obj.htm");
P.fA("Major Group Objectives screen","tme_mgp_obj.htm");
P.fA("Form &amp; Literature Activity History screen","tme_frm_lit_hist.htm");
P.fA("Marketing Notification List screen","tme_mkt_not.htm");
P.fA("Updating Prospects from a Campaign Saved List","prospects_contacts.3.12.htm");
P.fA("Setting up Customer Contacts","prospects_contacts.3.13.htm");
P.fA("Customer Contact Management Maintenance screen","ccmm.htm");
P.fA("Contact Additional Information screen","ccmm_add_info.htm");
P.fA("Customer Contact Keywords screen","ccmm_keywords.htm");
P.fA("ANI Numbers screen","ccmm_ani.htm");
P.fA("Mailing Address screen","ccmm_mailing_addr.htm");
P.fA("Contact Statistics screen","ccmm_cont_stat.htm");
P.fA("Product Line Objectives Information screen","ccmm_pline_obj.htm");
P.fA("Major Group Objectives Information screen","ccmm_mgp_obj.htm");
P.fA("Web User Maintenance screen","ccmm_web_user.htm");
P.fA("Linking Contacts","univ_link.htm");
P.fA("Copying a Contact to Another Customer","prospects_contacts.3.24.htm");
P.fA("Merging Contact Information","prospects_contacts.3.25.htm");
P.fA("Viewing Customer Contact Statistics and Performance","prospects_contacts.3.26.htm");
P.fA("Customer Contact Performance Summary Inquiry","ccpsi.htm");
P.fA("Contact Management Statistics Inquiry","cmsi.htm");
P.fA("Prospect Contact Report","pros_cont_rpt.htm");
P.fA("Contact Maintenance Audit Report by User ID","cont_audit_rpt.htm");
P.fA("Contact Maintenance Audit Customer/Contact Report","cont_audit_cn_rpt.htm");
P.fA("Tracking Marketing Activities","activities.4.1.htm");
P.fA("Entering a Marketing Activity","activities.4.2.htm");
P.fA("Sending Literature","activities.4.3.htm");
P.fA("Sending a Form Letter","activities.4.4.htm");
P.fA("Scheduling a Recurring Activity","activities.4.5.htm");
P.fA("Creating a Diary Entry","activities.4.6.htm");
P.fA("Viewing Open Marketing Activities","activities.4.7.htm");
P.fA("Marketing Activity Inquiry","mai.htm");
P.fA("Marketing Activity Contact Inquiry","maci.htm");
P.fA("Marketing Manager Inquiry","mkt_mgr_inq.htm");
P.fA("Prospect Activity Report","activity_rpt.htm");
P.fA("Send Literature Report","send_lit_rpt.htm");
P.fA("Batch Printing Form Letters","activities.4.13.htm");
P.fA("Viewing Activity History","activities.4.14.htm");
P.fA("Prospect Activity History Inquiry","pahi.htm");
P.fA("Contact Activity History Inquiry","cahi.htm");
P.fA("Contact Diary Inquiry","mhcdi.htm");
P.fA("Contact Diary Report","mhcdr.htm");
P.fA("Closed Prospect Activity Report","closed_activity_rpt.htm");
P.fA("Activity Performance Report by User/Date","mkt_act_perf_rpt.htm");
P.fA("Activity Performance Report by User/Date/Activity","mkt_act_perf_as_rpt.htm");
P.fA("Creating Marketing Campaigns","campaigns.5.1.htm");
P.fA("Creating Campaign Lists","campaigns.5.2.htm");
P.fA("Building a Campaign List","campaigns.5.3.htm");
P.fA("By SIC Code","campaigns.5.4.htm");
P.fA("By City, State, or ZIP","campaigns.5.5.htm");
P.fA("By Source Code","campaigns.5.6.htm");
P.fA("By Campaign Code","campaigns.5.7.htm");
P.fA("By Priority Code","campaigns.5.8.htm");
P.fA("By Other Sales Criteria","campaigns.5.9.htm");
P.fA("By Sales Rep","campaigns.5.10.htm");
P.fA("By User-Selected Criteria","campaigns.5.11.htm");
P.fA("By a TCL Select Statement","campaigns.5.12.htm");
P.fA("Merging Campaign Lists","campaigns.5.13.htm");
P.fA("Deleting a Campaign List","campaigns.5.14.htm");
P.fA("Exporting a Campaign List","campaigns.5.15.htm");
P.fA("Assigning Products and Lists to a Campaign","campaigns.5.16.htm");
P.fA("Adding Campaign Lists to a Campaign","campaigns.5.17.htm");
P.fA("Adding Products","campaigns.5.18.htm");
P.fA("Adding a Campaign List to an Existing Campaign","campaigns.5.19.htm");
P.fA("Viewing Campaign Information","campaigns.5.20.htm");
P.fA("Campaign List Inquiry","campaigns.5.21.htm");
P.fA("Customers/Prospects on a Campaign List","campaigns.5.22.htm");
P.fA("Campaign List Report","campaign_list_rpt.htm");
P.fA("Broadcast Emailing and Faxing","broadcast.6.1.htm");
P.fA("Selecting a Broadcast List","broadcast.6.2.htm");
P.fA("Exporting a Broadcast List","broadcast.6.3.htm");
P.fA("Broadcast Emailing","broadcast.6.4.htm");
P.fA("Broadcast Faxing","broadcast.6.5.htm");
P.fA("Copying a Broadcast Email or Fax","broadcast.6.6.htm");
P.fA("Field Definitions","acm.htm");
P.fA("Automated Prospect Maintenance screen","atme.htm");
P.fA("Campaign List Build screen","camp_list_build.htm");
P.fA("Campaign List Deletion screen","camp_list_delete.htm");
P.fA("Campaign List Merge screen","camp_list_merge.htm");
P.fA("Campaign Lists screen","mcm_lists.htm");
P.fA("Campaign Lists (Net Sales) screen","mcm_net_sales.htm");
P.fA("Campaign Lists By Campaign Code screen","camp_list_camp_code.htm");
P.fA("Campaign Lists by City/State/ZIP screen","camp_list_city_state_zip.htm");
P.fA("Campaign Lists by Other Criteria screen","camp_list_other.htm");
P.fA("Campaign Lists by Priority screen","camp_list_priority.htm");
P.fA("Campaign Lists by Sales Rep screen","camp_list_sales_rep.htm");
P.fA("Campaign Lists By SIC Codes screen","camp_list_sic.htm");
P.fA("Campaign Lists By Source Code screen","camp_list_source_code.htm");
P.fA("Campaign Lists By User Selected Criteria screen","camp_list_user_sel.htm");
P.fA("Campaign Prospect List screen","camp_pros_list.htm");
P.fA("Campaign Update Procedure screen","camp_upd.htm");
P.fA("Catalog Literature Information screen","mae_send_lit.htm");
P.fA("Catalog Literature Maintenance screen","clm.htm");
P.fA("Change Dates screen","mae_change_dates.htm");
P.fA("Change View screen","cmsi_change_view.htm");
P.fA("Competitor Code Maintenance screen","cpcm.htm");
P.fA("Contact Diary Code Maintenance screen","cdcm.htm");
P.fA("Contact Diary Entry screen","mhcde.htm");
P.fA("Contact List screen","contact_list.htm");
P.fA("Contact Management Detail Inquiry","cmsi_detail.htm");
P.fA("Contact Merge Process screen","contact_merge.htm");
P.fA("Contact Move screen","contact_move.htm");
P.fA("Contact Title Maintenance screen","ctm.htm");
P.fA("Copy Email/Fax screen","brdcst_copy.htm");
P.fA("Create EMail Lists screen","brdcst_create_list.htm");
P.fA("DOS Save of Campaign List screen","camp_list_dos_save.htm");
P.fA("Export Lists screen","export_lists.htm");
P.fA("Form Letter screen","mae_send_form_letter.htm");
P.fA("Form Letter Batch Print screen","flbp.htm");
P.fA("Form Letter Maintenance screen","flrm.htm");
P.fA("Manually enter customers/vendors/etc. screen","brdcst_manual_entry.htm");
P.fA("Marketing Activity Contact Entry screen","mace.htm");
P.fA("Marketing Activity Entry screen","mae.htm");
P.fA("Marketing Campaign Maintenance screen","mcm.htm");
P.fA("Potential Code Maintenance screen","pcm.htm");
P.fA("Product Detail screen","mcm_products.htm");
P.fA("CMSI Product Detail screen","cmsi_products.htm");
P.fA("Prospect Mnt Custom Field Descriptions screen","custom_field_mnt.htm");
P.fA("Recurring Marketing Events screen","mae_recurring.htm");
P.fA("Send Broadcast Email screen","brdcst_email.htm");
P.fA("Send broadcast fax screen","brdcst_fax.htm");
P.fA("SIC Number Maintenance screen","sicm.htm");
P.fA("Source Code Maintenance screen","scm.htm");
P.fA("Territory Maintenance screen","terr_mnt.htm");
P.fA("View Definition Maintenance screen","view_def_mnt.htm");
P.fA("View Items in List screen","view_list.htm");
P.fA("View Maintenance screen","cvm.htm");
}
