function FileData_Pairs(x)
{
x.t("method","end-of-period");
x.t("end-of-period","end-of-year");
x.t("billing","records");
x.t("schedules","items");
x.t("calculation","method");
x.t("items","billing");
x.t("items","fixed");
x.t("track","maintenance");
x.t("assets","depreciation");
x.t("assets","(v17)");
x.t("assets","module");
x.t("maintain","records");
x.t("books","company");
x.t("allows","maintain");
x.t("records","fixed");
x.t("records","leased");
x.t("depreciation","calculation");
x.t("depreciation","books");
x.t("fixed","assets");
x.t("reporting","track");
x.t("maintenance","schedules");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("leased","items");
x.t("(v17)","fixed");
x.t("(v17)","activant");
x.t("module","allows");
x.t("choose","depreciation");
x.t("taxes","reporting");
x.t("activant","solutions");
x.t("866-878-0574","972-403-3150");
x.t("company","choose");
x.t("end-of-year","taxes");
}
