function FileData_Pairs(x)
{
x.t("refer","following");
x.t("credit","collections");
x.t("necessary","prelude");
x.t("menu","necessary");
x.t("collections","refer");
x.t("collections","programs");
x.t("collections","activity");
x.t("collections","types");
x.t("collections","subsystem");
x.t("collections","activant");
x.t("collections","setting");
x.t("creating","credit");
x.t("codes","sequencing");
x.t("programs","credit");
x.t("defining","credit");
x.t("collection","activities");
x.t("prelude","credit");
x.t("activity","codes");
x.t("maintenance","menu");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("types","creating");
x.t("follow-up","collection");
x.t(":setting","credit");
x.t("subsystem","maintenance");
x.t("subsystem",":setting");
x.t("activities","credit");
x.t("activant","solutions");
x.t("following","defining");
x.t("866-878-0574","972-403-3150");
x.t("setting","credit");
x.t("sequencing","follow-up");
}
