function FileData_Pairs(x)
{
x.t("statements","generating");
x.t("generating","service");
x.t("customer","maintenance");
x.t("customer","invoices");
x.t("receivable","parameters");
x.t("parameters","customer");
x.t("parameters","additional");
x.t("charges","activant");
x.t("charges","following");
x.t("charges","setting");
x.t("charges","accounts");
x.t("programs","calculate");
x.t("calculate","service");
x.t("options","service");
x.t("maintenance","customer");
x.t("maintenance","programs");
x.t("maintenance","options");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("option","parameters");
x.t(":setting","maintenance");
x.t("additional","option");
x.t("charge","invoices");
x.t("activant","solutions");
x.t("service","charges");
x.t("service","charge");
x.t("following","maintenance");
x.t("866-878-0574","972-403-3150");
x.t("setting","maintenance");
x.t("accounts","receivable");
x.t("invoices","statements");
x.t("invoices",":setting");
}
