function FileData_Pairs(x)
{
x.t("statements","generating");
x.t("statements","maintenance");
x.t("statements","customers");
x.t("statements","activant");
x.t("statements","following");
x.t("generating","statements");
x.t("statement","options");
x.t("customer","maintenance");
x.t("customer","invoices");
x.t("receivable","parameters");
x.t("parameters","customer");
x.t("programs","choose");
x.t("options","statements");
x.t("options","accounts");
x.t("maintenance","customer");
x.t("maintenance","programs");
x.t("maintenance","options");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("customers",":maintenance");
x.t("choose","statement");
x.t(":maintenance","options");
x.t("activant","solutions");
x.t("following","maintenance");
x.t("866-878-0574","972-403-3150");
x.t("accounts","receivable");
x.t("invoices","statements");
}
