function FileData_Pairs(x)
{
x.t("customers/invoices","include");
x.t("credit","collections");
x.t("credit","collection");
x.t("customer","maintenance");
x.t("collections","determine");
x.t("collections","defining");
x.t("collections","subsystem");
x.t("collections","activant");
x.t("collections","following");
x.t("receivable","parameters");
x.t(":defining","customers/invoices");
x.t("parameters","customer");
x.t("parameters","additional");
x.t("determine","include");
x.t("defining","customers/invoices");
x.t("collection","options");
x.t("options","accounts");
x.t("maintenance","credit");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("customers","credit");
x.t("option","parameters");
x.t("include","credit");
x.t("include","customers");
x.t("additional","option");
x.t("subsystem",":defining");
x.t("activant","solutions");
x.t("following","credit");
x.t("866-878-0574","972-403-3150");
x.t("accounts","receivable");
}
