function  WWHBookData_Files(P)
{
P.fA("General Ledger Overview","overview.1.1.htm");
P.fA("General Ledger Chart of Accounts","general_ledger_%20table_%20maintenance.2.1.htm");
P.fA("Setting up the General Ledger Hierarchy","general_ledger_%20table_%20maintenance.2.2.htm");
P.fA("Maintaining the General Ledger Chart of Accounts","general_ledger_%20table_%20maintenance.2.3.htm");
P.fA("Chart of Accounts Maintenance","general_ledger_%20table_%20maintenance.2.4.htm");
P.fA("General Ledger Table Maintenance","gltable_mnt.htm");
P.fA("Default Chart of Accounts","general_ledger_%20table_%20maintenance.2.6.htm");
P.fA("Additional Files for General Ledger Accounts","general_ledger_%20table_%20maintenance.2.7.htm");
P.fA("Interfacing a G/L Account With Other Modules","general_ledger_%20table_%20maintenance.2.8.htm");
P.fA("Changing a G/L Account Description","general_ledger_%20table_%20maintenance.2.9.htm");
P.fA("Duplicating a Single G/L Account","general_ledger_%20table_%20maintenance.2.10.htm");
P.fA("Duplicating a Chart of Accounts","general_ledger_%20table_%20maintenance.2.11.htm");
P.fA("Rebuilding Chart of Account Prefixes","rebuild_cadf_prefix.htm");
P.fA("Moving a G/L Balance to a new G/L Prefix","general_ledger_%20table_%20maintenance.2.13.htm");
P.fA("Redistributing a General Ledger Balance","general_ledger_%20table_%20maintenance.2.14.htm");
P.fA("G/L Redistribution Maintenance","general_ledger_%20table_%20maintenance.2.15.htm");
P.fA("Redistributing a G/L Balance by Percent","general_ledger_%20table_%20maintenance.2.16.htm");
P.fA("Redistributing a G/L Balance by Proportion","general_ledger_%20table_%20maintenance.2.17.htm");
P.fA("G/L Redistribution Update Process","general_ledger_%20table_%20maintenance.2.18.htm");
P.fA("General Ledger Chart of Account Inquiries","general_ledger_%20table_%20maintenance.2.19.htm");
P.fA("Chart of Account Inquiry","general_ledger_%20table_%20maintenance.2.20.htm");
P.fA("Chart Detail Display","chart_detail.htm");
P.fA("General Ledger Account Balance Inquiry","gl_acct_num_scr.htm");
P.fA("Chart of Accounts Balance Inquiry","ca_bal_inq.htm");
P.fA("Expanded G/L Summary Inquiry","exp_sum_gl_ent.htm");
P.fA("Expanded Trial Balance Inquiry","exp_mc_tb_inq.htm");
P.fA("Project ID Tracking","TrackingGLprojects.3.1.htm");
P.fA("Maintenance Requirements for Project Tracking","TrackingGLprojects.3.2.htm");
P.fA("Creating Valid Responses for Project ID Codes.","TrackingGLprojects.3.3.htm");
P.fA("Setting a G/L Account to Require a Project ID","TrackingGLprojects.3.4.htm");
P.fA("Entry Programs that use Project IDs","TrackingGLprojects.3.5.htm");
P.fA("Project G/L Inquiry","proj_gl_inq.htm");
P.fA("General Ledger Balancing","general_ledger_balancing.4.1.htm");
P.fA("Posting to the General Ledger","post_sub.htm");
P.fA("General Ledger Module Code Definitions","general_ledger_balancing.4.3.htm");
P.fA("A/P Check Disbursements (AC)","general_ledger_balancing.4.4.htm");
P.fA("A/P Manual Checks (AM)","general_ledger_balancing.4.5.htm");
P.fA("Accounts Payable (AP)","general_ledger_balancing.4.6.htm");
P.fA("A/P Voided Checks (AV)","general_ledger_balancing.4.7.htm");
P.fA("Cost Adjustments (CA)","general_ledger_balancing.4.8.htm");
P.fA("Crib Replenishment (CB)","general_ledger_balancing.4.9.htm");
P.fA("Cash Receipts (CR)","general_ledger_balancing.4.10.htm");
P.fA("Equipment (EQ)","general_ledger_balancing.4.11.htm");
P.fA("Fixed Assets (FA)","general_ledger_balancing.4.12.htm");
P.fA("Job Accounting (JA)","general_ledger_balancing.4.13.htm");
P.fA("Journal Entry","general_ledger_balancing.4.14.htm");
P.fA("Linkage Adjustments (LA)","general_ledger_balancing.4.15.htm");
P.fA("Letters of Credit (LC)","general_ledger_balancing.4.16.htm");
P.fA("Lease Contract (LS)","general_ledger_balancing.4.17.htm");
P.fA("A/R Manual Invoice (MI)","general_ledger_balancing.4.18.htm");
P.fA("Order Processing (OE)","general_ledger_balancing.4.19.htm");
P.fA("Physical Inventory (PH)","general_ledger_balancing.4.20.htm");
P.fA("Payroll (PR)","general_ledger_balancing.4.21.htm");
P.fA("Point-of-Sale (PS)","general_ledger_balancing.4.22.htm");
P.fA("Inventory Adjustments (SA)","general_ledger_balancing.4.23.htm");
P.fA("Service Charge (SC)","general_ledger_balancing.4.24.htm");
P.fA("Stock Receipts (SR)","general_ledger_balancing.4.25.htm");
P.fA("Stock Transfer (ST)","general_ledger_balancing.4.26.htm");
P.fA("Vendor Claims (VC)","general_ledger_balancing.4.27.htm");
P.fA("Work Order (WO)","general_ledger_balancing.4.28.htm");
P.fA("Warranty Replacements (WR)","general_ledger_balancing.4.29.htm");
P.fA("Using Reports/Inquiries to Balance the General Ledger","general_ledger_balancing.4.30.htm");
P.fA("Detecting Inventory Discrepancies","general_ledger_balancing.4.31.htm");
P.fA("Balancing by Location","general_ledger_balancing.4.32.htm");
P.fA("Journal Entries","journal_entry.5.1.htm");
P.fA("Adjusting a General Ledger Account","journal_entry.5.2.htm");
P.fA("Journal Entry","journal_entry.5.3.htm");
P.fA("Journal Entry Proof Report","je_rpt.htm");
P.fA("Journal Entry Inquiry","journal_entry.5.5.htm");
P.fA("Open Journal Entry Inquiry","open_je_inq.htm");
P.fA("Creating Recurring Adjustments to General Ledger Accounts","journal_entry.5.7.htm");
P.fA("Recurring Journal Entry","journal_entry.5.8.htm");
P.fA("Recurring Journal Entry Proof Report","rje_rpt.htm");
P.fA("Posting Recurring Entries","journal_entry.5.10.htm");
P.fA("Bank Reconciliation","bank_reconciliation.6.1.htm");
P.fA("Reconciling Checks and Deposits","bank_reconciliation.6.2.htm");
P.fA("A/P Reconciliation Outstanding Checks Report","ap_rec_out_rpt.htm");
P.fA("Bank Reconciliation Outstanding Deposits Report","ar_rec_out_rpt.htm");
P.fA("End-of-Month/End-of-Year Closing","eom_eoy.7.1.htm");
P.fA("End-of-Month Closing Procedures","eom_eoy.7.2.htm");
P.fA("Constructing the Fiscal Period Table","eom_eoy.7.3.htm");
P.fA("Viewing Fiscal Period Changes","fiscal_period_audit.htm");
P.fA("Saving Inventory Balances for Month-End","me_inv_bal.htm");
P.fA("Saving Customer A/R Aging Balances for Month-End","me_ar_aging.htm");
P.fA("Revaluating Multiple Currency for Month-End","eom_eoy.7.7.htm");
P.fA("Saving Vendor A/P Aging Balances for Month-End","me_ap_aging.htm");
P.fA("End-of-Year Closing Procedures","eom_eoy.7.9.htm");
P.fA("Closing Accounts Receivable for Year-End","eom_eoy.7.10.htm");
P.fA("Closing Accounts Payable for Year-End","eom_eoy.7.11.htm");
P.fA("Closing the General Ledger for Year End","year_end_close.htm");
P.fA("Closing Fixed Assets for Year-End","eom_eoy.7.13.htm");
P.fA("Financial Report Manager","financial_report_%20manager.8.1.htm");
P.fA("Creating Financial Report Groups","financial_report_%20manager.8.2.htm");
P.fA("Maintaining Report Column Descriptions","financial_report_%20manager.8.3.htm");
P.fA("Designing Financial Reports","financial_report_%20manager.8.4.htm");
P.fA("Calculating Lines","financial_report_%20manager.8.5.htm");
P.fA("Choosing Basis Accounts","financial_report_%20manager.8.6.htm");
P.fA("Printing Financial Reports","financial_report_%20manager.8.7.htm");
P.fA("Optional Financial Features","optional_features.9.1.htm");
P.fA("Using Multiple Fiscal Periods","optional_features.9.2.htm");
P.fA("Maintenance Options for Multiple Fiscal Periods","optional_features.9.3.htm");
P.fA("Setting up Fiscal Accounts","optional_features.9.4.htm");
P.fA("Using Multiple Currency","optional_features.9.5.htm");
P.fA("Maintenance Requirements for Multiple Currency","optional_features.9.6.htm");
P.fA("Activating Multiple Currency","optional_features.9.7.htm");
P.fA("Assigning Exchange Rates for Monthly G/L Reports","optional_features.9.8.htm");
P.fA("Assigning Native Currency","optional_features.9.9.htm");
P.fA("Creating Currency Types","optional_features.9.10.htm");
P.fA("Maintaining Currency Exchange Rates","optional_features.9.11.htm");
P.fA("Assigning Default G/L Currency Types","optional_features.9.12.htm");
P.fA("Creating G/L Accounts for Multiple Currencies","optional_features.9.13.htm");
P.fA("Assigning Currency Information to Customers","optional_features.9.14.htm");
P.fA("Assigning Currency Information to Vendors","optional_features.9.15.htm");
P.fA("Assigning Currency Types to Bank Codes","optional_features.9.16.htm");
P.fA("Entry Programs Affected by Multiple Currency","optional_features.9.17.htm");
P.fA("Using Standard Cost","optional_features.9.18.htm");
P.fA("Setting Your Company to use Standard Cost","optional_features.9.19.htm");
P.fA("Posting Standard Cost","optional_features.9.20.htm");
P.fA("General Ledger Reports","gl_reports.10.1.htm");
P.fA("Detail General Ledger Report","det_gl_rpt.htm");
P.fA("Detail General Ledger Source Report","det_gl_src_rpt.htm");
P.fA("G/L Summary Posting Report","gl_post_rpt.htm");
P.fA("Trial Balance Report","call_print_tb.htm");
P.fA("Suspense Account Posting Report","susp_rpt.htm");
P.fA("Unposted General Ledger Summary Report","glp_unpost_rpt.htm");
P.fA("Unposted G/L Detail Report","unpost_det_rpt.htm");
P.fA("Unposted G/L Error Report","glp_post_err_rpt.htm");
P.fA("Chart of Accounts Balance Report","ca_bal_rpt.htm");
P.fA("Current Inventory Value Report - Average","gl_reports.10.11.htm");
P.fA("Inventory Received Not Invoiced Report","ib_rec_not_inv.htm");
P.fA("Open Vendor Claim Receivers - Regular Inventory Report","ib_open_vc_inv_rcv.htm");
P.fA("Direct Ship Inventory Report","ib_dir_inv_rpt.htm");
P.fA("A/P Suspended Direct Ship Receivers Report","ib_ap_sus_dir_rpt.htm");
P.fA("Current Inventory Value Report - Linked","gl_reports.10.16.htm");
P.fA("Linked Inventory Received Not Invoiced Report","ib_ns_accrual_rpt.htm");
P.fA("Current Inventory Value Report - Damaged","gl_reports.10.18.htm");
P.fA("Stock Transfer In-Transit Report","stock_intrans_rpt.htm");
P.fA("Warranty Stock Transfer In-Transit Report","wty_stock_intrans_rpt.htm");
P.fA("Current Consigned (P/O Type) Value Report","cons_val_rpt.htm");
P.fA("Consignment Order Release Report By Shipping Warehouse","cons_ord_rpt_shp.htm");
P.fA("Work In Process Report","work_in_proc_rpt.htm");
P.fA("Wty Tags With Open GL - Type R Report","ib_wty_tag_r.htm");
P.fA("Wty Tags With Open GL - Type S Report","ib_wty_tag_s.htm");
P.fA("Open Vendor Claims Accrual - Tag Type R Report","ib_opn_vdr_clm_tag_r.htm");
P.fA("Open Vendor Claims Accrual - Tag Type S Report","ib_opn_vdr_clm_tag_s.htm");
P.fA("Accounts Payables Accrual - Vendor Claims Report","ib_opn_ap_vc_acc.htm");
P.fA("Vendor Claim Freight Report","ib_vc_frt_rpt.htm");
P.fA("Processed Vendor Claims - Misc Entries Report","ib_opn_vdr_clm_misc.htm");
P.fA("Processed Vendor Claims - Cost Difference Accrual Report","ib_opn_vdr_clm_cost_diff.htm");
P.fA("Reconciled Vendor Claims - Cost Difference Report","ib_hist_vdr_clm_cost_diff.htm");
P.fA("Reconciled Vendor Claims - Quantity Disallowed Report","ib_hist_vdr_clm_qty_dis.htm");
P.fA("Warranty Replacements - Cost Difference Report","ib_hist_wty_rep_cost_diff.htm");
P.fA("Products With Negative Average Cost Report","ib_neg_avg_cost.htm");
P.fA("Products With Negative On Hands Report","ib_neg_onhand.htm");
P.fA("Out of Balance - Total OH vs Linked OH Report","ib_onhand_bal.htm");
P.fA("Out of Balance - Negative Linked On Hand Report","ib_neg_link_onhand.htm");
P.fA("Out Of Balance - Negative Linked Value Report","ib_neg_link_value.htm");
P.fA("Stock Inventory Accrual - Currency Report","ib_rec_not_inv_curr.htm");
P.fA("Linked Inventory Accrual - Currency Report","ib_ns_accrual_rpt_curr.htm");
P.fA("Accounts Payables Accrual - Vendor Claims - Currency Report","ib_opn_ap_vc_acc_curr.htm");
P.fA("A/P Suspended Direct Ship Receivers Report - Currency","ib_ap_sus_dir_rpt_curr.htm");
P.fA("Stock Inventory Accrual - Currency (Daily) Report","ib_rec_not_inv_curr_dly.htm");
P.fA("Linked Inventory Accrual - Currency (Daily) Report","ib_ns_accrual_rpt_curr_dly.htm");
P.fA("Accounts Payables Accrual - Vendor Claims - Currency Daily Report","ib_opn_ap_vc_acc_curr_dly.htm");
P.fA("A/P Suspended Direct Ship Receivers - Currency (Daily) Report","ib_ap_sus_dir_rpt_curr_dly.htm");
P.fA("General Ledger Field Definitions","field_definitions_gl.11.1.htm");
P.fA("Add a Fiscal Period screen","fiscal_period_mnt_add_info.htm");
P.fA("Bank Reconciliation Entry screen","bank_recon_ent.htm");
P.fA("Chart Budget Maintenance screen","chart_budget_mnt.htm");
P.fA("Chart Of Account Description Maintenance screen","chart_desc_mnt.htm");
P.fA("Chart of Accounts Maintenance screen","chart_mstr_mnt.htm");
P.fA("Create New G/L Accounts screen","chart_copy_mnt.htm");
P.fA("Currency Roll Forward Posting screen","currency_roll_prompt.htm");
P.fA("Delete a Fiscal Year screen","fiscal_period_mnt_del_info.htm");
P.fA("Duplicate Existing COA screen","coa_dup.htm");
P.fA("Entity Include/Exclude Entry screen","finrpt_incexc.htm");
P.fA("Expanded G/L Detail Inquiry screen","exp_det_gl_ent.htm");
P.fA("Financial Report Basis Maintenance screen","finrpt_basis_ent.htm");
P.fA("Financial Report G/L Acct Entry screen","finrpt_gl_ent.htm");
P.fA("Financial Report Group Maintenance screen","finrpt_group_mnt.htm");
P.fA("Financial Report Master Maintenance screen","finrpt_master_maint.htm");
P.fA("Financial Report Printing screen","finrpt_print.htm");
P.fA("Financial Rpt Column Maintenance screen","finrpt_col_mnt.htm");
P.fA("Fiscal Period Maintenance screen","fiscal_period_mnt.htm");
P.fA("Function Operation Entry screen","finrpt_funct_ent.htm");
P.fA("G/L Redistribution Maintenance screen","gl_dist_mnt.htm");
P.fA("G/L Redistribution Percentages screen","gl_dist_perc.htm");
P.fA("G/L Redistribution Proportion screen","gl_dist_prop.htm");
P.fA("G/L Redistribution Update Process screen","gl_dist_upd_scr.htm");
P.fA("G/L Summary Transaction Inquiry screen","gl_sum_inq.htm");
P.fA("General Ledger Hierarchy Move screen","gl_move_loc_ent.htm");
P.fA("Journal Entry Routine screen","journal_entry.htm");
P.fA("Maintain Annual Budget Distribution screen","chart_budget_annual.htm");
P.fA("Maintain Open? screen","fiscal_period_mnt_open.htm");
P.fA("Maintain Repeatings Budget Distribution screen","chart_budget_repeat.htm");
P.fA("Module Interface Options screen","field_definitions_gl.11.31.htm");
P.fA("Recurring Journal Entry screen","recurring_je.htm");
P.fA("Report Printing Parameters screen","finrpt_print_params.htm");
P.fA("Report Title Maintenance screen","finrpt_master_titles.htm");
P.fA("Summary of Chart Posting screen","chart_summary_detail.htm");
P.fA("Financial Report Generator","finrpt_cons.htm");
}
