function  WWHBookData_Files(P)
{
P.fA("V20 New Features","v20_new_features.1.1.htm");
P.fA("General Topics","v20_new_features.1.2.htm");
P.fA("Order Processing","v20_new_features.1.3.htm");
P.fA("Purchasing","v20_new_features.1.4.htm");
P.fA("Inventory","v20_new_features.1.5.htm");
P.fA("Accounts Receivable","v20_new_features.1.6.htm");
P.fA("Accounts Payable","v20_new_features.1.7.htm");
P.fA("General Ledger","v20_new_features.1.8.htm");
P.fA("Sales Analysis","v20_new_features.1.9.htm");
P.fA("Work Orders","v20_new_features.1.10.htm");
P.fA("Rental","v20_new_features.1.11.htm");
P.fA("Shop Repair","v20_new_features.1.12.htm");
P.fA("Warehousing","v20_new_features.1.13.htm");
P.fA("Marketing","v20_new_features.1.14.htm");
P.fA("Job Billing","v20_new_features.1.15.htm");
P.fA("TPCx","v20_new_features.1.16.htm");
P.fA("V19 New Features","v19_new_features.2.1.htm");
P.fA("Accounts Receivable","v19_new_features.2.2.htm");
P.fA("Bills of Material/Work Orders","v19_new_features.2.3.htm");
P.fA("Forecasting","v19_new_features.2.4.htm");
P.fA("General Ledger","v19_new_features.2.5.htm");
P.fA("Inventory","v19_new_features.2.6.htm");
P.fA("Miscellaneous","v19_new_features.2.7.htm");
P.fA("Order Processing","v19_new_features.2.8.htm");
P.fA("Purchasing","v19_new_features.2.9.htm");
P.fA("Rental","v19_new_features.2.10.htm");
P.fA("Shop Repair","v19_new_features.2.11.htm");
P.fA("Systems","v19_new_features.2.12.htm");
P.fA("Warehousing","v19_new_features.2.13.htm");
P.fA("V18 New Features","v18_new_features.3.1.htm");
P.fA("Accounts Payable","v18_new_features.3.2.htm");
P.fA("Accounts Receivable","v18_new_features.3.3.htm");
P.fA("Inventory","v18_new_features.3.4.htm");
P.fA("Forecasting","v18_new_features.3.5.htm");
P.fA("General Ledger","v18_new_features.3.6.htm");
P.fA("Job Accounting","v18_new_features.3.7.htm");
P.fA("EDI","v18_new_features.3.8.htm");
P.fA("Marketing","v18_new_features.3.9.htm");
P.fA("Order Processing","v18_new_features.3.10.htm");
P.fA("Purchasing","v18_new_features.3.11.htm");
P.fA("Rental","v18_new_features.3.12.htm");
P.fA("Shop Repair","v18_new_features.3.13.htm");
P.fA("Systems","v18_new_features.3.14.htm");
P.fA("Bill of Material/Work Orders","v18_new_features.3.15.htm");
P.fA("Warehousing","v18_new_features.3.16.htm");
P.fA("V17 New Features","v17_new_features.4.1.htm");
P.fA("Bill of Material/Work Order","v17_new_features.4.2.htm");
P.fA("General Ledger","v17_new_features.4.3.htm");
P.fA("Inventory","v17_new_features.4.4.htm");
P.fA("Order Processing","v17_new_features.4.5.htm");
P.fA("Purchasing","v17_new_features.4.6.htm");
P.fA("Rental","v17_new_features.4.7.htm");
P.fA("Sales Analysis","v17_new_features.4.8.htm");
P.fA("Shop/Repair","v17_new_features.4.9.htm");
P.fA("Service","v17_new_features.4.10.htm");
P.fA("System Parameters","v17_new_features.4.11.htm");
P.fA("Warehousing","v17_new_features.4.12.htm");
P.fA("V16 New Features","v16_new_features.5.1.htm");
P.fA("New Sales Analysis Features","v16_new_features.5.2.htm");
P.fA("New Purchasing Features","v16_new_features.5.3.htm");
P.fA("Inventory","v16_new_features.5.4.htm");
P.fA("Accounts Receivable","v16_new_features.5.5.htm");
P.fA("General Ledger","v16_new_features.5.6.htm");
P.fA("Accounts Payable","v16_new_features.5.7.htm");
P.fA("System Parameters","v16_new_features.5.8.htm");
P.fA("Bill of Material/Work Order","v16_new_features.5.9.htm");
P.fA("E-Commerce","v16_new_features.5.10.htm");
P.fA("Marketing","v16_new_features.5.11.htm");
P.fA("Rental","v16_new_features.5.12.htm");
P.fA("Service","v16_new_features.5.13.htm");
P.fA("Warehousing","v16_new_features.5.14.htm");
P.fA("V15 New Features","v15_new_features.6.1.htm");
P.fA("New Purchasing Features","v15_new_features.6.2.htm");
P.fA("Inventory","v15_new_features.6.3.htm");
P.fA("Accounts Receivable","v15_new_features.6.4.htm");
P.fA("General Ledger","v15_new_features.6.5.htm");
P.fA("Rental","v15_new_features.6.6.htm");
P.fA("System","v15_new_features.6.7.htm");
P.fA("New Marketing Features","v15_new_features.6.8.htm");
P.fA("New Warehousing Features","v15_new_features.6.9.htm");
P.fA("Bill of Material/Work Order","v15_new_features.6.10.htm");
P.fA("V14 New Features","v14_new_features.7.1.htm");
P.fA("Order Processing","v14_new_features.7.2.htm");
P.fA("Purchasing","v14_new_features.7.3.htm");
P.fA("Inventory","v14_new_features.7.4.htm");
P.fA("Bill of Materials/Work Order","v14_new_features.7.5.htm");
P.fA("Warehousing","v14_new_features.7.6.htm");
P.fA("Accounts Receivable/Accounts Payable","v14_new_features.7.7.htm");
P.fA("General Ledger","v14_new_features.7.8.htm");
P.fA("System Parameters","v14_new_features.7.9.htm");
}
