function  WWHBookData_Files(P)
{
P.fA("Order Processing Overview","introduction.1.1.htm");
P.fA("Customer Accounts","Customer_records.2.1.htm");
P.fA("Customer Maintenance","Customer_records.2.2.htm");
P.fA("Customer Maintenance Screen","cust_mnt.htm");
P.fA("Additional Customer Information Screen","cust_add_info.htm");
P.fA("Additional Keywords Screen","cust_keywords.htm");
P.fA("Customer Sales Tax Entry Screen","cust_sls_tax.htm");
P.fA("Sales Tax Certificate Information Screen","Customer_records.2.7.htm");
P.fA("A/R Information Screen","cust_ar_info.htm");
P.fA("Additional A/R Information Screen","cust_add_ar_info.htm");
P.fA("Credit Card Information Screen","cust_cc_info.htm");
P.fA("Bill To Information Screen","cc_bill_info.htm");
P.fA("Floor Planning Maintenance Screen","floor_plan_mnt.htm");
P.fA("Financial References Screen","fin_refers.htm");
P.fA("Order Information Screen","cust_ord_info.htm");
P.fA("Acct Code Pattern Match Screen","cust_acct_codes.htm");
P.fA("Customer Blanket P/O Numbers Screen","cust_blanket_po.htm");
P.fA("PO Pattern Match Screen","cust_pattern_po.htm");
P.fA("Additional Order Information Screen","cust_add_ord_info.htm");
P.fA("Rental Module Screen","cust_rent_info.htm");
P.fA("Warehousing Information Screen","cust_whs_info.htm");
P.fA("Customer Permit Information Screen","cust_permits.htm");
P.fA("Freight Information Screen","cust_frt_info.htm");
P.fA("Incompatible Ship Via Maintenance Screen","cust_ord_inv_ship_via.htm");
P.fA("Alternate Shipping Warehouse Screen","cust_split_whse_info.htm");
P.fA("EDI Transmission Info Screen","cust_edi_info.htm");
P.fA("Government Information Screen","cust_govt_info.htm");
P.fA("Order Source Matrix Screen","ord_src_mat_ent.htm");
P.fA("Order Types Screen","order_types.htm");
P.fA("Customer Route Maintenance Screen","cust_rte_mnt.htm");
P.fA("Customer Contacts Screen","cust_cont_info.htm");
P.fA("Customer Employees Screen","cust_empl_info.htm");
P.fA("Customer Authorized Purchasing Agents Screen","cust_agents_info.htm");
P.fA("Customer Statistics Screen","cust_stats.htm");
P.fA("Customer Labels Information Screen","cust_labels.htm");
P.fA("Customer Service Information Screen","cust_serv_info.htm");
P.fA("Instructions Entry Screen","instructions.htm");
P.fA("Authorized List of SalesRep #1 Screen","valid_salesrep.htm");
P.fA("Authorized List of SalesRep #2 Screen","valid_salesrep_2.htm");
P.fA("Marketing Notification List Screen","mkt_notify_mnt.htm");
P.fA("Prospect Conversion Screen","pros_cust_conv.htm");
P.fA("Customer Maintenance Copy Screen","Customer_records.2.41.htm");
P.fA("Customer Ship-To Maintenance","Customer_records.2.42.htm");
P.fA("Customer Ship-To Maintenance Screen","shipto_mnt.htm");
P.fA("Ship-To Additional Information Screen","shipto_add_info.htm");
P.fA("Permit Information Screen","shipto_permits.htm");
P.fA("Incompatible Ship Via Maintenance Screen","shipto_inc_ship_via.htm");
P.fA("Freight Information Screen","shipto_frt_info.htm");
P.fA("Ship To Route Maintenance Screen","shipto_rte_mnt.htm");
P.fA("Rental Information Screen","shipto_rent_info.htm");
P.fA("Ship-To Tax Information Screen","cust_sls_tax_2.htm");
P.fA("Customer Purchase Orders Screen","shipto_blanket_po.htm");
P.fA("Customer Job Maintenance","Customer_records.2.52.htm");
P.fA("Customer Job Maintenance Screen","custjob_mnt.htm");
P.fA("Customer Job Additional Information Screen","custjob_add_info.htm");
P.fA("Customer Job Sales Tax Maintenance Screen","custjob_sls_tax.htm");
P.fA("Lien / Bond Information Screen","lien_info_mnt.htm");
P.fA("A/R Information Screen","ar_info.htm");
P.fA("Job Summary Info Screen","job_summary_inq.htm");
P.fA("Job Billing Info Screen","job_bill_info.htm");
P.fA("Customer Job History Inquiry Screen","custjob_hist_inq.htm");
P.fA("Job Site Information Screen","custjob_job_addr.htm");
P.fA("General Contractor Information Screen","custjob_gc_addr.htm");
P.fA("Subcontractor Information Screen","custjob_sc_addr.htm");
P.fA("Owner Information Screen","custjob_own_addr.htm");
P.fA("Lender Information Screen","custjob_lend_addr.htm");
P.fA("Bond Company Information Screen","custjob_bc_addr.htm");
P.fA("Progress Billing Screen","custjob_prog_bill.htm");
P.fA("Maintenance Codes for Customer Records","Customer_records.2.68.htm");
P.fA("Sales Representative Maintenance Screen","slsm_mnt.htm");
P.fA("Salesman Performance Planning Screen","slsm_perform.htm");
P.fA("Ship Via Maintenance Screen","shipvia_mnt.htm");
P.fA("Warehousing Information Screen","ship_via_whs_info.htm");
P.fA("Ship Via Freight Info Screen","shipvia_frt_info.htm");
P.fA("Freight Surcharge Table Screen","surcharge_table.htm");
P.fA("Ship Via Additional Charge Screen","addcharge_table.htm");
P.fA("PSS Manifest Interface Screen","pss_interface.htm");
P.fA("Via Overrides Screen","via_overrides.htm");
P.fA("Ship Via Family Code Maintenance Screen","sv_family_mnt.htm");
P.fA("Customer Price Group Maintenance Screen","cust_grp_mnt.htm");
P.fA("Customer Type Maintenance Screen","cust_type_mnt.htm");
P.fA("Freight Terms Maintenance Screen","frt_terms_mnt.htm");
P.fA("Territory Maintenance Screen","terr_mnt.htm");
P.fA("Route Maintenance Screen","route_mnt.htm");
P.fA("Route Code Group Maintenance Screen","route_grp_mnt.htm");
P.fA("Customer Rebate Maintenance Screen","coop_mnt.htm");
P.fA("Rebate Table Maintenance Screen","reb_table_mn.htm");
P.fA("Source Code Maintenance Screen","osource_mnt.htm");
P.fA("Restricted Usage Code Maintenance Screen","res_usg_code_mnt.htm");
P.fA("Customer Job Type Maintenance Screen","cust_job_type_mnt.htm");
P.fA("Sales Region Maintenance Screen","sls_reg_mnt.htm");
P.fA("Customer Tax Codes and Jurisdictions","Customer_records.2.91.htm");
P.fA("State Abbreviation Maintenance Screen","state_abbr_mnt.htm");
P.fA("Tax Jurisdiction Maintenance Screen","tax_jur_mnt.htm");
P.fA("Additional Tax Jurisdiction Information Screen","tax_addit_info.htm");
P.fA("Geographic Code Maintenance Screen","geo_code_mnt.htm");
P.fA("Geographical County/City Lines Screen","geo_code_xref.htm");
P.fA("Sales Tax Matrix Maintenance Screen","sls_tax_mat_mnt.htm");
P.fA("Sales Tax Exempt Code Maintenance Screen","sls_tax_exempt_mnt.htm");
P.fA("Universal Customer Replacement Merge","Customer_records.2.99.htm");
P.fA("Merging/Replacing Customer Accounts","Customer_records.2.100.htm");
P.fA("Universal Customer Replacement /Merge Preview Report","cust_repl_prev_rpt.htm");
P.fA("Universal Customer Replacement /Merge Update","cust_replace_process.htm");
P.fA("Customer Replacement / Merge Audit Report","convert_data_report_cust_merge.htm");
P.fA("Clearing the Cross Reference File","cust_replace_clear.htm");
P.fA("Optional Order Entry Features","Maintenance.3.1.htm");
P.fA("Tracking Lost Sales","Maintenance.3.2.htm");
P.fA("Creating Order Cancellation Reason Codes","Maintenance.3.3.htm");
P.fA("Creating Lost Sales Reason Codes","Maintenance.3.4.htm");
P.fA("Manually Recording Lost Sales Orders","Maintenance.3.5.htm");
P.fA("Creating Standard Instructions","Maintenance.3.6.htm");
P.fA("Using Floor Plan Financing","Maintenance.3.7.htm");
P.fA("Setting up a Customer to use Floor Plan Financing","Maintenance.3.8.htm");
P.fA("Creating Floor Plan Numbers","Maintenance.3.9.htm");
P.fA("Entering a Floor Plan Sales Order","Maintenance.3.10.htm");
P.fA("Defining Order Source Codes","Maintenance.3.11.htm");
P.fA("Creating Reason Codes for Price Overrides","Maintenance.3.12.htm");
P.fA("Creating Discount Reason Codes","Maintenance.3.13.htm");
P.fA("Setting Up Customer Product Numbers","Maintenance.3.14.htm");
P.fA("Restricting Products for a State or Zip Code","Maintenance.3.15.htm");
P.fA("Overriding Shipping Locations for Products","Maintenance.3.16.htm");
P.fA("Creating Package Inserts","Maintenance.3.17.htm");
P.fA("Creating the Package Insert Product","Maintenance.3.18.htm");
P.fA("Creating the Package Insert Codes","Maintenance.3.19.htm");
P.fA("Assigning the Package Insert Code to a Customer","Maintenance.3.20.htm");
P.fA("Using Crib Warehouses","Maintenance.3.21.htm");
P.fA("Setting up a Crib Warehouse","Maintenance.3.22.htm");
P.fA("Maintaining Customer Department File Information","Maintenance.3.23.htm");
P.fA("Cross Referencing Customer Crib Orders","Maintenance.3.24.htm");
P.fA("Setting up Crib Information for a Product/Warehouse","Maintenance.3.25.htm");
P.fA("Setting up and Tracking Prescriptions","Maintenance.3.26.htm");
P.fA("Setting Prescription and Facility Counter Numbers","Maintenance.3.27.htm");
P.fA("Setting up Facility Information","Maintenance.3.28.htm");
P.fA("Setting up Physician Information","Maintenance.3.29.htm");
P.fA("Identifying Maximum RX Months by State","Maintenance.3.30.htm");
P.fA("Creating Valid Species Responses","Maintenance.3.31.htm");
P.fA("Creating Prescription Groups","Maintenance.3.32.htm");
P.fA("Identifying a Product as a Prescription","Maintenance.3.33.htm");
P.fA("Creating a Customer Prescription","Maintenance.3.34.htm");
P.fA("Prescription Quantities","cust_rx_qty_adj.htm");
P.fA("Prescription History","rx_hist_inq.htm");
P.fA("Monthly Prescription Report","mth_rx_rpt.htm");
P.fA("Expiring Prescription Report","exp_rx_rpt.htm");
P.fA("Sales Order Entry &amp; Printing","Sales%20Order%20Entry.4.1.htm");
P.fA("Sales Order Types","Sales%20Order%20Entry.4.2.htm");
P.fA("Entering a Sales Order","Sales%20Order%20Entry.4.3.htm");
P.fA("Selecting a Customer","Sales%20Order%20Entry.4.4.htm");
P.fA("Entering Sales Order Header Information","Sales%20Order%20Entry.4.5.htm");
P.fA("Order Additional Information Screen","ord_add_info.htm");
P.fA("Ship-To Address Screen","ord_ship_to.htm");
P.fA("Tax Jurisdiction Information Screen","ord_tax_jur_info.htm");
P.fA("Credit Information Screen","Sales%20Order%20Entry.4.9.htm");
P.fA("Entering Sales Order Line Items","Sales%20Order%20Entry.4.10.htm");
P.fA("Entering Stock Products","Sales%20Order%20Entry.4.11.htm");
P.fA("Entering Non-Stock Products","Sales%20Order%20Entry.4.12.htm");
P.fA("Entering a Miscellaneous Product","Sales%20Order%20Entry.4.13.htm");
P.fA("Sourcing a Backorder to an Existing Purchase Order","Sales%20Order%20Entry.4.14.htm");
P.fA("Creating Products in Sales Order Entry","Sales%20Order%20Entry.4.15.htm");
P.fA("Re-Pricing an Entire Sales Order","Sales%20Order%20Entry.4.16.htm");
P.fA("Splitting Line Items for Delivery Dates","Sales%20Order%20Entry.4.17.htm");
P.fA("Shipping Split Quantities out of Other Warehouses","Sales%20Order%20Entry.4.18.htm");
P.fA("Entering Comments","Sales%20Order%20Entry.4.19.htm");
P.fA("Adding Accessory Products to an Order","Sales%20Order%20Entry.4.20.htm");
P.fA("Entering Upsell Products","Sales%20Order%20Entry.4.21.htm");
P.fA("Viewing Product Complements","Sales%20Order%20Entry.4.22.htm");
P.fA("Entering Kit Parent Products","Sales%20Order%20Entry.4.23.htm");
P.fA("Using a Control Product","Sales%20Order%20Entry.4.24.htm");
P.fA("Entering Rationed Products","Sales%20Order%20Entry.4.25.htm");
P.fA("Entering Prescription Products","Sales%20Order%20Entry.4.26.htm");
P.fA("Re-Allocating Available Backorders","Sales%20Order%20Entry.4.27.htm");
P.fA("Finishing the Sales Order","Sales%20Order%20Entry.4.28.htm");
P.fA("Using the Sales Order Completion Screen","Sales%20Order%20Entry.4.29.htm");
P.fA("Taking Payment for an Order","Sales%20Order%20Entry.4.30.htm");
P.fA("Duplicating Sales Orders","Sales%20Order%20Entry.4.31.htm");
P.fA("Duplicating a Sales Order for Multiple Addresses","Sales%20Order%20Entry.4.32.htm");
P.fA("Duplicating a Sales Order for One Ship-To","Sales%20Order%20Entry.4.33.htm");
P.fA("Deleting Sales Orders","Sales%20Order%20Entry.4.34.htm");
P.fA("Manually Deleting a Sales Order","Sales%20Order%20Entry.4.35.htm");
P.fA("Automatically Cancelling a Backorder","Sales%20Order%20Entry.4.36.htm");
P.fA("Setting an Auto Cancellation Date at the Header Level","Sales%20Order%20Entry.4.37.htm");
P.fA("Setting an Auto Cancellation Date by Line Item","Sales%20Order%20Entry.4.38.htm");
P.fA("Printing Pick Tickets","Sales%20Order%20Entry.4.39.htm");
P.fA("Setting Pick Ticket Rules","Sales%20Order%20Entry.4.40.htm");
P.fA("Printing Pick Tickets by Batch","PTPR.htm");
P.fA("Sending Acknowledgements","Sales%20Order%20Entry.4.42.htm");
P.fA("Setting Maintenance Options for Acknowledgements","Sales%20Order%20Entry.4.43.htm");
P.fA("Sending Acknowledgements by Batch","ack_print_prompts.htm");
P.fA("Printing Backorder Notices","Sales%20Order%20Entry.4.45.htm");
P.fA("Linking a Purchase Order to a Backorder","Sales%20Order%20Entry.4.46.htm");
P.fA("Linking a Transfer to a Backorder","Sales%20Order%20Entry.4.47.htm");
P.fA("Shipping Sales Orders Complete","Sales%20Order%20Entry.4.48.htm");
P.fA("Entering a Tag &amp; Hold Sales Order","Sales%20Order%20Entry.4.49.htm");
P.fA("Using Warehouse Hold Areas for Tag &amp; Hold Orders","Sales%20Order%20Entry.4.50.htm");
P.fA("Creating a Warehouse Hold Area","Sales%20Order%20Entry.4.51.htm");
P.fA("Assigning a Warehouse Hold Area to a Sales Order","Sales%20Order%20Entry.4.52.htm");
P.fA("Releasing Tag &amp; Hold Sales Orders","ord_ent_th.htm");
P.fA("Entering a Direct Ship Order","Sales%20Order%20Entry.4.54.htm");
P.fA("Entering a Direct Ship Sales Order","Sales%20Order%20Entry.4.55.htm");
P.fA("Entering a Direct Ship Purchase Order","Sales%20Order%20Entry.4.56.htm");
P.fA("Using Consignment Sales Orders","Sales%20Order%20Entry.4.57.htm");
P.fA("Entering a Consignment Order","Sales%20Order%20Entry.4.58.htm");
P.fA("Billing Consignment Orders","Sales%20Order%20Entry.4.59.htm");
P.fA("Automatically Billing Consignment Orders","Sales%20Order%20Entry.4.60.htm");
P.fA("Manually Billing Consignment Orders","Sales%20Order%20Entry.4.61.htm");
P.fA("Using Manufacturer Rep Sales Orders","Sales%20Order%20Entry.4.62.htm");
P.fA("Product Pricing","pricing.5.1.htm");
P.fA("Pricing Hierarchy","pricing.5.2.htm");
P.fA("Price Source Codes","pricing.5.3.htm");
P.fA("Discount Break Tables","pricing.5.4.htm");
P.fA("Sum &amp; Reprice and Quantity Break Discounts","pricing.5.5.htm");
P.fA("Price Matrices","pricing.5.6.htm");
P.fA("Setting System Options for Price Matrices","pricing.5.7.htm");
P.fA("Creating a Price Matrix","pricing.5.8.htm");
P.fA("Calculating Prices","pricing.5.9.htm");
P.fA("Calculating Rebates","pricing.5.10.htm");
P.fA("Defining Purchasing Cost","pricing.5.11.htm");
P.fA("Overriding Commission Cost","pricing.5.12.htm");
P.fA("Assigning Vendor Information to a Contract","pricing.5.13.htm");
P.fA("Copying Price Matrices","pricing.5.14.htm");
P.fA("Copying a Single Price Matrix","pricing.5.15.htm");
P.fA("Copying Multiple Price Matrices","pricing.5.16.htm");
P.fA("Copying all Price Matrices for a Product","pricing.5.17.htm");
P.fA("Modifying Multiple Matrices for a Customer","qme.htm");
P.fA("Creating a Price Matrix From a Quote or Sales Order","pricing.5.19.htm");
P.fA("Retail Price Matrices","pricing.5.20.htm");
P.fA("Setting System Options for Retail Price Matrices","pricing.5.21.htm");
P.fA("Creating a Retail Price Matrix","pricing.5.22.htm");
P.fA("Copying a Retail Price Matrix","pricing.5.23.htm");
P.fA("Rounding Prices for Retail Matrices","pricing.5.24.htm");
P.fA("Contract Pricing","pricing.5.25.htm");
P.fA("Creating a Customer Price Contract","pricing.5.26.htm");
P.fA("Manually Entering Contract Ship-To Information","pricing.5.27.htm");
P.fA("Copying a Contract","pricing.5.28.htm");
P.fA("Copying a Customer Contract","pricing.5.29.htm");
P.fA("Copying a Customer Contract by Product","pricing.5.30.htm");
P.fA("Contract Price Usage Report","contr_prc_usg_rpt.htm");
P.fA("Contract Price Ship-To Usage Report","contr_st_usg_rpt.htm");
P.fA("Blanket Contracts","pricing.5.33.htm");
P.fA("Creating a Blanket Contract","pricing.5.34.htm");
P.fA("Copying a Blanket Contract","bcm_cpn_update.htm");
P.fA("Tracking Blanket P/O Information for a Customer","pricing.5.36.htm");
P.fA("Promotional Price Matrices","pricing.5.37.htm");
P.fA("Setting System Options for Promotional Price Matrices","pricing.5.38.htm");
P.fA("Creating a Promotion Price Matrix by Product","pricing.5.39.htm");
P.fA("Excluding/Including Customers in a Promotion Matrix","pricing.5.40.htm");
P.fA("Excluding or Including Product Lines on a Matrix","pricing.5.41.htm");
P.fA("Creating a Promotion Price Matrix by Order Total","pricing.5.42.htm");
P.fA("Customer Promotion Matrix Inquiry","pricing.5.43.htm");
P.fA("Price Labels","pricing.5.44.htm");
P.fA("Formatting Price Labels","pricing.5.45.htm");
P.fA("Assigning Price Label Information to Customers","pricing.5.46.htm");
P.fA("Assigning Price Label Information to Products","pricing.5.47.htm");
P.fA("Catalog ID Codes","pricing.5.48.htm");
P.fA("Creating a Catalog ID Code","pricing.5.49.htm");
P.fA("Duplicating a Catalog ID Code","pricing.5.50.htm");
P.fA("Release Confirmation &amp; Shipping","Shipping_Confirming_Orders.6.1.htm");
P.fA("Assigning Order Picker Abbreviations","Shipping_Confirming_Orders.6.2.htm");
P.fA("Confirming Releases","Shipping_Confirming_Orders.6.3.htm");
P.fA("Sending Shipping Confirmations","Shipping_Confirming_Orders.6.4.htm");
P.fA("Setting Shipping Confirmation Maintenance Options","Shipping_Confirming_Orders.6.5.htm");
P.fA("Transmitting Shipping Confirmations by Batch","shcp.htm");
P.fA("Text Emailing an Individual Shipping Confirmation","Shipping_Confirming_Orders.6.7.htm");
P.fA("Printing Packing Lists","Shipping_Confirming_Orders.6.8.htm");
P.fA("Setting Packing List Maintenance Options","Shipping_Confirming_Orders.6.9.htm");
P.fA("Printing Packing Lists by Batch","pack_print_prompts.htm");
P.fA("Printing Packing Lists for Non-Confirmed Releases","Shipping_Confirming_Orders.6.11.htm");
P.fA("Using Serial Shipping Container Codes","Shipping_Confirming_Orders.6.12.htm");
P.fA("Maintenance Requirements for SSCCs","Shipping_Confirming_Orders.6.13.htm");
P.fA("Assigning Serial Shipping Container Codes","Shipping_Confirming_Orders.6.14.htm");
P.fA("Printing Shipping Labels","Shipping_Confirming_Orders.6.15.htm");
P.fA("Printing a Bill of Lading","Shipping_Confirming_Orders.6.16.htm");
P.fA("Invoicing","Invoicing.7.1.htm");
P.fA("Setting Maintenance Options for Invoices","Invoicing.7.2.htm");
P.fA("Previewing Invoices","inv_prev_rpt.htm");
P.fA("Printing Invoices","ip.htm");
P.fA("Re-Printing Invoices","Invoicing.7.5.htm");
P.fA("Re-Printing One Invoice","ir.htm");
P.fA("Re-Printing Multiple Invoices","Invoicing.7.7.htm");
P.fA("Printing Summary Invoices","Invoicing.7.8.htm");
P.fA("Printing Consolidated Invoices","coipr.htm");
P.fA("Printing DD250 Invoices","Invoicing.7.10.htm");
P.fA("Setting Maintenance Flags for DD250 Form Printing","Invoicing.7.11.htm");
P.fA("Creating Administered-By Codes","Invoicing.7.12.htm");
P.fA("Creating Payment-By Codes","Invoicing.7.13.htm");
P.fA("Entering a Sales Order that Requires a DD250 Invoice","Invoicing.7.14.htm");
P.fA("Confirming a Release that Requires a DD250 Invoice","Invoicing.7.15.htm");
P.fA("Printing Invoices Using the DD250 Form","Invoicing.7.16.htm");
P.fA("Printing Installment Invoice Memos","mip.htm");
P.fA("Voiding an Invoice","Invoicing.7.18.htm");
P.fA("Updating Sales Statistics (\u2018B\u2019 Update)","bupdate_process.htm");
P.fA("Credit Memos &amp; RGAs","credit_memos.8.1.htm");
P.fA("Creating Credit Reason Codes","credit_memos.8.2.htm");
P.fA("Entering an RGA","credit_memos.8.3.htm");
P.fA("Printing RGAs","rgap.htm");
P.fA("Setting Maintenance Options for RGAs","credit_memos.8.5.htm");
P.fA("Printing RGAs by Batch","credit_memos.8.6.htm");
P.fA("Converting an RGA into a Credit","credit_memos.8.7.htm");
P.fA("Entering a Credit Memo","credit_memos.8.8.htm");
P.fA("Creating Warranty Tags for Returned Products","credit_memos.8.9.htm");
P.fA("Credit Cards","Credit_Card_Processing.9.1.htm");
P.fA("Setting up Your System for Credit Cards","Credit_Card_Processing.9.2.htm");
P.fA("Activating Protobase for a Warehouse","Credit_Card_Processing.9.3.htm");
P.fA("Masking Credit Cards for a User","Credit_Card_Processing.9.4.htm");
P.fA("Setting up Credit Card Payment Terms","Credit_Card_Processing.9.5.htm");
P.fA("Assigning Credit Card Information to a Customer","Credit_Card_Processing.9.6.htm");
P.fA("Using Administrative Order Hold for Credit Cards","Credit_Card_Processing.9.7.htm");
P.fA("Using Administrative Invoice Hold for Credit Cards","Credit_Card_Processing.9.8.htm");
P.fA("Integrating Protobase with Prelude","Credit_Card_Processing.9.9.htm");
P.fA("Calculating the Order Total for Credit Card Orders","Credit_Card_Processing.9.10.htm");
P.fA("Adding a Markup to the Pre-Authorization Amount","Credit_Card_Processing.9.11.htm");
P.fA("Assigning Credit Bureau Codes","Credit_Card_Processing.9.12.htm");
P.fA("Pre-Authorizing a Sales Order","Credit_Card_Processing.9.13.htm");
P.fA("Manually Adding an Authorization Code","Credit_Card_Processing.9.14.htm");
P.fA("Sales Orders With No Credit Card Authorization Report","Credit_Card_Processing.9.15.htm");
P.fA("Credit Card Authorization Batch Report","cc_auth_batch_rpt.htm");
P.fA("Post-Authorizing Credit Card Transactions","Credit_Card_Processing.9.17.htm");
P.fA("Credit Card Post Authorization Approval Report","post_auth_appr_reprint.htm");
P.fA("Credit Card Post Authorization Rejection Report","post_auth_reject_reprint.htm");
P.fA("Removing Rejected Credit Card Transactions","Credit_Card_Processing.9.20.htm");
P.fA("Changing an Expiration Date","Credit_Card_Processing.9.21.htm");
P.fA("Deleting Rejected Transactions","Credit_Card_Processing.9.22.htm");
P.fA("Closing a Credit Card Batch","cc_man_batch_close.htm");
P.fA("Gift Certificates","Gift_Certificates.10.1.htm");
P.fA("Setting System Options for Gift Certificates","Gift_Certificates.10.2.htm");
P.fA("Creating Reason Codes for Gift Certificates","Gift_Certificates.10.3.htm");
P.fA("Creating Gift Certificates","Gift_Certificates.10.4.htm");
P.fA("Creating a Gift Certificate in Sales Order Entry","Gift_Certificates.10.5.htm");
P.fA("Creating a Gift Certificate in Gift Certificate Maintenance","Gift_Certificates.10.6.htm");
P.fA("Applying a Gift Certificate to a Sales Order","Gift_Certificates.10.7.htm");
P.fA("Quotation Subsystem","Quotes.11.1.htm");
P.fA("Entering a Quote","Quotes.11.2.htm");
P.fA("Entering a Quick Quotation","Quotes.11.3.htm");
P.fA("Creating a Vendor RFQ from a Quote","Quotes.11.4.htm");
P.fA("Printing Quotes","Quotes.11.5.htm");
P.fA("Setting Maintenance Options for Printing Quotes","Quotes.11.6.htm");
P.fA("Printing Quotes by Batch","qop.htm");
P.fA("Converting Quotes into Sales Orders","Quotes.11.8.htm");
P.fA("Converting a Quote to a Sales Order","Quotes.11.9.htm");
P.fA("Converting Line Items from Quotes","Quotes.11.10.htm");
P.fA("Converting Standing Quotes","qte_convert_stand_ord.htm");
P.fA("Deleting Quotes","Quotes.11.12.htm");
P.fA("Creating Quote Disposition Codes","Quotes.11.13.htm");
P.fA("Deleting a Quote","Quotes.11.14.htm");
P.fA("Duplicating Quotes","Quotes.11.15.htm");
P.fA("Quotation Inquiries","Quotes.11.16.htm");
P.fA("Quote Order Inquiry","qte_inq.htm");
P.fA("Quote/Product Inquiry","qte_prod_inq.htm");
P.fA("Quote/Date Inquiry","qte_date_inq.htm");
P.fA("Quote Written By Inquiry","qte_wb_inq.htm");
P.fA("Quote Follow Up Inquiry","qte_fu_inq.htm");
P.fA("Quote Order History Inquiry","qte_hist_inq.htm");
P.fA("Quote History Product Inquiry","qte_hist_prod_inq.htm");
P.fA("Quote Log Inquiry","quote_log_inq.htm");
P.fA("Quotation Reports","Quotes.11.25.htm");
P.fA("Open Quotation Report","open_qte_rpt.htm");
P.fA("Quote Follow Up Report","quote_follow_up_rpt.htm");
P.fA("Quote Price Override Audit Report","qte_pr_ovr_rpt.htm");
P.fA("Quotation Disposition Detail Report","quote_disp_rpt.htm");
P.fA("Quotation Disposition Summary Report","Quotes.11.30.htm");
P.fA("Commission Subsystem","commission.12.1.htm");
P.fA("Calculating Commission Rates","commission.12.2.htm");
P.fA("Setting System Parameters for Commission","commission.12.3.htm");
P.fA("Company Maintenance","commission.12.4.htm");
P.fA("Order Processing Parameters","commission.12.5.htm");
P.fA("Commission Matrix Types &amp; Sequence","commission.12.6.htm");
P.fA("Accounts Payable Parameters","commission.12.7.htm");
P.fA("Additional Option Parameters","commission.12.8.htm");
P.fA("File Update Parameters","commission.12.9.htm");
P.fA("Setting Commission Rates by Salesrep","commission.12.10.htm");
P.fA("Assigning Salesreps to a Customer","commission.12.11.htm");
P.fA("Setting Commission Rates for a Product","commission.12.12.htm");
P.fA("Creating a Gross Profit Table","commission.12.13.htm");
P.fA("Creating a Commission Matrix","commission_matrix_info.htm");
P.fA("Overriding Commission","commission.12.15.htm");
P.fA("Overriding Commission Cost using a Price Matrix","commission.12.16.htm");
P.fA("Overriding Commission in Sales Order Entry","commission.12.17.htm");
P.fA("Overriding Commission For a Salesrep","commission.12.18.htm");
P.fA("Overriding Commission for One Line Item","commission.12.19.htm");
P.fA("Splitting Commission Between Salesreps","commission.12.20.htm");
P.fA("Updating &amp; Adjusting Commission","commission.12.21.htm");
P.fA("Updating and Paying Commission","commission.12.22.htm");
P.fA("Salesman Commission Report","slsm_comm_rpt.htm");
P.fA("Salesman A/R Commission Report","ar_comm_rpt.htm");
P.fA("Adjusting Commission After Invoicing","commission.12.25.htm");
P.fA("Adjusting Commission for a Line Item","commission.12.26.htm");
P.fA("Changing the Salesrep on an Invoice","commission.12.27.htm");
P.fA("Adjusting the Commission Percent","commission.12.28.htm");
P.fA("Adding Charges to an Invoice","commission.12.29.htm");
P.fA("Salesrep Commission Inquiry","slsm_comm_inq.htm");
P.fA("Manufacturer\u2019s Rep Subsystem","manufacturers_rep.13.1.htm");
P.fA("Entering a Manufacturer\u2019s Rep Order","manufacturers_rep.13.2.htm");
P.fA("Completing a Manufacturers\u2019s Rep Order","manufacturers_rep.13.3.htm");
P.fA("Updating a Manufacturer Rep Order","manufacturers_rep.13.4.htm");
P.fA("Manufacturer\u2019s Rep Inquiries","manufacturers_rep.13.5.htm");
P.fA("Manufacturer Rep Inquiry","rep_inq.htm");
P.fA("Manufacturer Rep/Customer Inquiry","rep_cust_inq.htm");
P.fA("Manufacturer Rep/Product Inquiry","rep_pn_inq.htm");
P.fA("Manufacturer Rep/History Inquiry","rep_hist_inq.htm");
P.fA("Manufacturer Rep/Customer History Inquiry","rep_cust_hist_inq.htm");
P.fA("Manufacturer Rep/Product History Inquiry","manufacturers_rep.13.11.htm");
P.fA("Manufacturer\u2019s Rep Reports","manufacturers_rep.13.12.htm");
P.fA("Monthly M/R Register","mly_mr_rpt.htm");
P.fA("Monthly M/R Register By Sales Rep 1","mly_mr_rep1_rpt.htm");
P.fA("Open Manufacture Rep Order Detail Report","open_mr_order_rpt.htm");
P.fA("Open M/R Summary Report","open_mr_sum_rpt.htm");
P.fA("M/R Invoice/Shipped Report","mr_inv_rpt.htm");
P.fA("M/R Preview Report","mr_prev_sum_rpt.htm");
P.fA("Quality Inspection Subsystem","quality_inspection.14.1.htm");
P.fA("Maintenance Setup for Quality Inspection","quality_inspection.14.2.htm");
P.fA("Activating the Quality Inspection Subsystem","quality_inspection.14.3.htm");
P.fA("Assigning Inspection Procedures for Products","quality_inspection.14.4.htm");
P.fA("Authorizing Users to Release Products","quality_inspection.14.5.htm");
P.fA("Creating Quality Agent Codes","quality_inspection.14.6.htm");
P.fA("Setting Acceptable Quality Levels for Inspection Procedures","quality_inspection.14.7.htm");
P.fA("Assigning Default Procedures to Inspection Types","quality_inspection.14.8.htm");
P.fA("Setting up Inspection Levels for Sample Sizes","quality_inspection.14.9.htm");
P.fA("Using Single Sampling Tables","quality_inspection.14.10.htm");
P.fA("Normal Inspection Table","quality_inspection.14.11.htm");
P.fA("Tightened Inspection Table","quality_inspection.14.12.htm");
P.fA("Reduced Inspection Table","quality_inspection.14.13.htm");
P.fA("Tracking Quality Control Information","quality_inspection.14.14.htm");
P.fA("Recording a Product Complaint","quality_inspection.14.15.htm");
P.fA("Quality Feedback Entry","quality_inspection.14.16.htm");
P.fA("Quality Feedback Report","feedback_rpt.htm");
P.fA("Collecting Quality Control Incident Information","quality_inspection.14.18.htm");
P.fA("Quality Incident Entry","quality_inspection.14.19.htm");
P.fA("Quality Incident Report","incident_rpt.htm");
P.fA("Recording Corrective Actions","quality_inspection.14.21.htm");
P.fA("Quality Corrective Action Entry","quality_inspection.14.22.htm");
P.fA("Quality Corrective Action Report","corr_action_rpt.htm");
P.fA("Recording Inspection Results","quality_inspection.14.24.htm");
P.fA("Quality Control Inspection Inquiry","quality_inspection.14.25.htm");
P.fA("Inspection Results Entry","quality_inspection.14.26.htm");
P.fA("Inspection Results History Inquiry","ir_inq.htm");
P.fA("Administrative Hold Inquiries","Administrative_Holds.15.1.htm");
P.fA("Branch Release Inquiry","Administrative_Holds.15.2.htm");
P.fA("Defining System Options for Branch Hold","Administrative_Holds.15.3.htm");
P.fA("Branch Hold for Sales Orders","Administrative_Holds.15.4.htm");
P.fA("Branch Hold for Transfers","Administrative_Holds.15.5.htm");
P.fA("Releasing Orders from Branch Hold","brch_rel_inq.htm");
P.fA("Administrative Order Inquiry","Administrative_Holds.15.7.htm");
P.fA("Defining Options for Administrative Order Hold","Administrative_Holds.15.8.htm");
P.fA("System Level Administrative Order Hold Options","Administrative_Holds.15.9.htm");
P.fA("User Level Administrative Order Hold Options","Administrative_Holds.15.10.htm");
P.fA("Customer Level Administrative Order Hold Options","Administrative_Holds.15.11.htm");
P.fA("Product Line Level Administrative Order Hold Options","Administrative_Holds.15.12.htm");
P.fA("Product Level Administrative Order Hold Options","Administrative_Holds.15.13.htm");
P.fA("Manually Placing Orders on Administrative Order Hold","Administrative_Holds.15.14.htm");
P.fA("Releasing Orders from Administrative Order Hold","adm_ord_inq.htm");
P.fA("Administrative Invoice Inquiry","Administrative_Holds.15.16.htm");
P.fA("Defining Options for Administrative Invoice Hold","Administrative_Holds.15.17.htm");
P.fA("System Level Administrative Invoice Hold Options","Administrative_Holds.15.18.htm");
P.fA("User Level Administrative Invoice Hold Options","Administrative_Holds.15.19.htm");
P.fA("Customer Level Administrative Invoice Hold Options","Administrative_Holds.15.20.htm");
P.fA("Manually Placing Orders on Administrative Invoice Hold","Administrative_Holds.15.21.htm");
P.fA("Releasing Orders from Administrative Invoice Hold","adm_inv_inq.htm");
P.fA("Administrative Quote Inquiry","Administrative_Holds.15.23.htm");
P.fA("Defining Options for Administrative Quote Hold","Administrative_Holds.15.24.htm");
P.fA("System Level Administrative Quote Hold Options","Administrative_Holds.15.25.htm");
P.fA("User Level Administrative Quote Hold Options","Administrative_Holds.15.26.htm");
P.fA("Customer Level Administrative Quote Hold Options","Administrative_Holds.15.27.htm");
P.fA("Product Level Administrative Quote Hold Options","Administrative_Holds.15.28.htm");
P.fA("Manually Placing Quotes on Hold","Administrative_Holds.15.29.htm");
P.fA("Releasing Orders from Administrative Quote Hold","adm_qte_inq.htm");
P.fA("Order Processing Inquiries","inquiries.16.1.htm");
P.fA("Sales Order Inquiry","open_order_inq.htm");
P.fA("Sales Order History Inquiry","hist_order_inq.htm");
P.fA("Order Log Inquiry","order_log_inq.htm");
P.fA("Consignment Order History Inquiry","ord_cons_inq.htm");
P.fA("Suspended Order Inquiry","save_oord_inq.htm");
P.fA("Open Release Inquiry","open_release_inq.htm");
P.fA("Consignment Release Inquiry","cons_release_inq.htm");
P.fA("Release History Inquiry","release_inq.htm");
P.fA("Crib History Inquiry","hist_crib_inq.htm");
P.fA("RF Scanned Orders Inquiry","rf_order_inq.htm");
P.fA("Written By Order Inquiry","wb_bo_inq.htm");
P.fA("Serial Shipping Container Inquiry","pkg_content_inq.htm");
P.fA("Open Order Release Inquiry","open_ord_rel_inq.htm");
P.fA("Customer Price Inquiry","cus_price_inq.htm");
P.fA("Customer Price/Availability Inquiry","cus_avail_inq.htm");
P.fA("Last Price Paid Inquiry","last_price_pd_inq.htm");
P.fA("Customer Product Cross-Reference Inquiry","cpn_xref_inq.htm");
P.fA("Master Account Inquiry","child_inq.htm");
P.fA("Progress Billing Inquiry","prog_bill_inq.htm");
P.fA("Customer Compatible Ship Vias Inquiry","cust_whse_comp_shipvias.htm");
P.fA("Customer Rationing Inquiry","prod_cust_ration_inq.htm");
P.fA("Customer Sales History Inquiry","cust_sls_hist_inq.htm");
P.fA("Customer/Product History Inquiry","cust_prod_inq.htm");
P.fA("Product Sales History Inquiry - Selling Warehouse","prod_sls_inq.htm");
P.fA("Product Sales History Inq-Shipping Warehouse","prod_sls_whse_in.htm");
P.fA("Employee Queue Inquiry","slsm_queue_inq.htm");
P.fA("Employee Order Message Inquiry","slsm_msg_inq.htm");
P.fA("Employee Quote Message Inquiry","msg_qte_inq.htm");
P.fA("Linked Sales Order Inquiry","link_ord_inq.htm");
P.fA("Universal Inquiry","univ_inq.htm");
P.fA("Sales Hits Inquiry","sls_hits_inq.htm");
P.fA("Accessory Inquiry","prod_act_inq.htm");
P.fA("Universal Order Inquiry","univ_ord_inq.htm");
P.fA("Order Pad Inquiry","order_pad.htm");
P.fA("Linked Sales Order Manager Inquiry","link_mgr_ord_inq.htm");
P.fA("Customer Backorder Inquiry","bo_inq.htm");
P.fA("Product Backorder Inquiry","pboi.htm");
P.fA("Customer/Product Warranty Inquiry","cust_wty_inq.htm");
P.fA("Product/Customer Warranty Inquiry","prod_wty_inq.htm");
P.fA("order_processing_ reports.17.1.htm","order_processing_%20reports.17.1.htm");
P.fA("Order Processing Reports","order_processing_%20reports.17.2.htm");
P.fA("Daily Order Detail Reports","order_processing_%20reports.17.3.htm");
P.fA("Open Sales Order Detail Report","open_order_rpt.htm");
P.fA("Overdue Sales Order Detail Report","overdue_rpt.htm");
P.fA("Open Backorder Detail Report","backorder_rpt.htm");
P.fA("Gross Profit Exception Report","open_sales_below_gp_rpt.htm");
P.fA("Price Override Audit Report","pr_except_rpt.htm");
P.fA("Cost Override Audit Report","cost_ov_rpt.htm");
P.fA("Interbranch S/O Hold Report","inter_hold_rpt.htm");
P.fA("Orders in Process (Picking) Report","ord_in_proc_rpt.htm");
P.fA("Direct Ship Lines to Invoice Report","dir_ord_ship_rpt.htm");
P.fA("Customer Orders On Credit Hold Report","cust_credit_rpt.htm");
P.fA("Zero Price/Cost Report","zero_salesdet_rpt.htm");
P.fA("Consignment Reports","order_processing_%20reports.17.15.htm");
P.fA("Consignment Order Release Report","cons_ord_rel_rpt.htm");
P.fA("Consignment Review Date Report","consign_ord_rev_rpt.htm");
P.fA("Consignment Order Release Report By Ship Whse","cons_ord_rpt_shp.htm");
P.fA("Open Order Buyout Not Linked Report","opn_buy_link_rpt.htm");
P.fA("Fill Rate Detail Report","fill_rate_det_rpt.htm");
P.fA("Sending Check Cancellation Date Report","send_check_canc_rpt.htm");
P.fA("Wire Transfer Review Report","wire_trans_review_rpt.htm");
P.fA("Order/Quote Profitability Report","ord_qte_prof_rpt.htm");
P.fA("Open Gift Certificates Report","open_gift_cert_rpt.htm");
P.fA("Open Sales Order Aging Report","opn_ord_age_rpt.htm");
P.fA("Daily Order Summary Reports","order_processing_%20reports.17.26.htm");
P.fA("Open Sales Order Summary Report","open_sales_sum_rpt.htm");
P.fA("Daily Business Statistics","order_processing_%20reports.17.28.htm");
P.fA("Daily Business Update","dbs_upd.htm");
P.fA("Daily Business Statistics Report","dbs_rpt.htm");
P.fA("Customer Job Summary Report","job_summary_rpt.htm");
P.fA("Fill Rate Summary Report","fill_rate_sum_rpt.htm");
P.fA("Pending Orders Report","pend_ord_rpt.htm");
P.fA("Open Backorder Detail Report By Vendor","bo_vend_rpt.htm");
P.fA("Daily Accounting Reports","order_processing_%20reports.17.35.htm");
P.fA("Daily Invoice Register","dly_inv_reg_rpt.htm");
P.fA("Daily Credit Memo Register","dly_cm_reg_rpt.htm");
P.fA("Daily Cash Sales Register","dly_cs_rpt.htm");
P.fA("Daily Consignment Register","dly_cons_reg_rpt.htm");
P.fA("Daily Consigned Invoice Register","dly_cons_inv_reg_rpt.htm");
P.fA("Open Consignment Detail Report","open_cons_det_rpt.htm");
P.fA("Daily Manufacturer\u2019s Rep Invoice Register","dly_mfr_rep_reg_rpt.htm");
P.fA("Daily Lease Contract Invoice Register","dly_lct_inv_reg_rpt.htm");
P.fA("Daily Credit Card Sales Register","dly_cc_rpt.htm");
P.fA("Daily Gift Certificates Register","dly_cert_rpt.htm");
P.fA("Daily COD Sales Register","dly_cod_reg_rpt.htm");
P.fA("Cash Sales Breakdown Register","cash_sls_brkdown_reg.htm");
P.fA("Daily Gross Profit Reports","order_processing_%20reports.17.48.htm");
P.fA("Daily Gross Profit Report by Salesrep1","dly_gp_rep_one_rpt.htm");
P.fA("Daily Gross Profit Report by Salesrep2","dly_gp_rep_two_rpt.htm");
P.fA("Daily Gross Profit Report by Written-By","dly_gp_wb_rpt.htm");
P.fA("Daily Gross Profit Report by Customer","dly_gp_cust_rpt.htm");
P.fA("Daily Gross Profit Report by Selling Warehouse","dly_gp_sell_rpt.htm");
P.fA("Daily Sales Tax Reports","order_processing_%20reports.17.54.htm");
P.fA("Daily Sales Tax Detail Report","dly_tax_det_rpt.htm");
P.fA("Daily Sales Tax Summary Report","dly_tax_sum_rpt.htm");
P.fA("Daily Sales Tax Adjustment Detail Report","dly_tax_adj_det_rpt.htm");
P.fA("Daily Sales Tax Adjustment Summary Report","dly_tax_adj_sum_rpt.htm");
P.fA("Daily Bookings Report","dly_book_rpt.htm");
P.fA("Daily Deposit Register","dly_dep_rpt.htm");
P.fA("Tax Exempt Expiration Report - Customer","tax_exmp_exp_rpt.htm");
P.fA("Tax Exempt Expiration Report-Ship To","tax_exmp_exp_rpt2.htm");
P.fA("Deposit Balance Report","dep_bal_rpt.htm");
P.fA("Daily Deposit Received Report","dly_dep_post_rpt.htm");
P.fA("Monthly Detail Reports","order_processing_%20reports.17.65.htm");
P.fA("Monthly Cost Override Audit Report","mly_cost_ov_rpt.htm");
P.fA("Monthly Lost Sales Report","mly_lost_sls_rpt.htm");
P.fA("Monthly Lost Sales by Vendor Report","mly_vnd_lost_sls_rpt.htm");
P.fA("Catalog Order History Report","cat_ord_rpt.htm");
P.fA("Monthly Accounting Reports","order_processing_%20reports.17.70.htm");
P.fA("Monthly Invoice Register","mly_inv_reg_rpt.htm");
P.fA("Monthly Invoice &amp; C/M Sequence Register","mly_inv_cm_rpt.htm");
P.fA("Monthly Credit Memo Register","mly_cm_reg_rpt.htm");
P.fA("Monthly Cash Sales Register","mly_cs_rpt.htm");
P.fA("Monthly Consignment Register","mly_cons_reg_rpt.htm");
P.fA("Monthly Consignment Invoice Register","mly_cons_inv_reg_rpt.htm");
P.fA("Monthly Manufacturer\u2019s Rep Invoice Register","mly_mfr_rep_reg_rpt.htm");
P.fA("Monthly Lease Contract Register","mly_lct_inv_reg_rpt.htm");
P.fA("Monthly Credit Card Register","mly_cc_rpt.htm");
P.fA("Monthly Gift Certificates Register","mly_cert_rpt.htm");
P.fA("Monthly COD Sales Register","mly_cod_reg_rpt.htm");
P.fA("Monthly Cash Sales Breakdown Register","mly_cash_sls_brkdown_reg.htm");
P.fA("Monthly G/P Reports","order_processing_%20reports.17.83.htm");
P.fA("Monthly Gross Profit Report by Salesrep1","mly_gp_rep_one_rpt.htm");
P.fA("Monthly Gross Profit Report by Salesrep2","mly_gp_rep_two_rpt.htm");
P.fA("Monthly Gross Profit Report By Written By","mly_gp_wb_rpt.htm");
P.fA("Monthly Gross Profit Report By Customer","mly_gp_cust_rpt.htm");
P.fA("Monthly Gross Profit Report by Sell Warehouse","mly_gp_sell_rpt.htm");
P.fA("Monthly Gross Profit Report by Catalog/Customer","mly_gp_cat_cust_rpt.htm");
P.fA("Monthly Gross Profit Report by Catalog/Prod Line","mly_gp_cat_pline_rpt.htm");
P.fA("Monthly Sales Tax Reports","order_processing_%20reports.17.91.htm");
P.fA("Monthly Sales Tax Detail Report","mly_tax_det_rpt.htm");
P.fA("Monthly Sales Tax Summary Report","mly_tax_sum_rpt.htm");
P.fA("Monthly Sales Tax Adjustment Detail Report","mly_tax_adj_det_rpt.htm");
P.fA("Monthly Sales Tax Adjustment Summary Report","mly_tax_adj_sum_rpt.htm");
P.fA("Monthly Deposit Register","mly_dep_rpt.htm");
P.fA("Monthly Consigned Sold Report (Product Type)","mly_consign_sold_rpt.htm");
P.fA("Monthly Consigned Sold Report (P/O Type)","cons_sold_rpt.htm");
P.fA("Monthly Bookings Report","mly_book_rpt.htm");
P.fA("Miscellaneous Reports","order_processing_%20reports.17.100.htm");
P.fA("Order Log Report","order_log_rpt.htm");
P.fA("Credit Authorization Report","cr_auth_rpt.htm");
P.fA("Rebate Report","rebate_rpt.htm");
P.fA("Deleted Orders Report","deleted_orders_rpt.htm");
P.fA("Nonstock (Buyout) Report","buyout_det_rpt.htm");
P.fA("Pick Error Report","pick_error_rpt.htm");
P.fA("Monthly Credit Reason Report","mly_cred_rsn_rpt.htm");
P.fA("Historical Percentage Credit Reason Report","hist_cred_rsn_rpt.htm");
P.fA("Monthly Job Tracking Report","job_tracking_rpt.htm");
P.fA("Lien / Bond Reports","order_processing_%20reports.17.110.htm");
P.fA("Pending Lien/Bond Report","pend_exp_jobs_rpt.htm");
P.fA("Notice of Commencement Report","noc_letter.htm");
P.fA("Notice of Furnishing Report","nof_letter.htm");
P.fA("Negative Availability Override Report","neg_avail_rpt.htm");
P.fA("Expected Date Change Notification Report","expect_date_chg_rpt.htm");
P.fA("Tag &amp; Hold Report","tag_hold_rpt.htm");
P.fA("Customer/Ship-To Reports","order_processing_%20reports.17.117.htm");
P.fA("Customer Ranking Report","cust_rank_rpt.htm");
P.fA("Customer P/O Percentage Report","cust_po_pct_rpt.htm");
P.fA("Customer On-Time Shipments/Quality Report","cust_ontime_ship_rpt.htm");
P.fA("Customer Rebate Detail Report","cust_reb_det_rpt.htm");
P.fA("Customer Rebate Summary Report","cust_reb_sum_rpt.htm");
P.fA("Customer Rebate Detail Report (Table)","cust_due_reb_det_rpt.htm");
P.fA("Customer Rebate Summary Report (Table)","cust_due_reb_sum_rpt.htm");
P.fA("Rebate Change Conversion","rebate_chg_convert.htm");
P.fA("Customer Maintenance Audit Report by User Id","cust_audit%20_rpt.htm");
P.fA("Customer Maint Audit Report by Customer","cust_audit_cn_rpt.htm");
P.fA("Ship-to Maintenance Audit Report by UserId","shipto_audit_rpt.htm");
P.fA("Ship-To Maintenance Audit Report by Customer","shipto_audit_cn_rpt.htm");
P.fA("Point of Sale","order_processing_%20reports.17.130.htm");
P.fA("Point of Sale Report Build","build_pos_scr.htm");
P.fA("Point of Sale Report","pos_rpt_scr.htm");
P.fA("Pricing Reports","order_processing_%20reports.17.133.htm");
P.fA("Price Listing All Products Report","price_list.htm");
P.fA("Price Listing All Products - Excel","price_list_export.htm");
P.fA("Price Listing Warehouse Specific","price_list_whse.htm");
P.fA("Price Listing for Products Previously Bought","price_list_cphi.htm");
P.fA("Price Maintenance Audit Report by User Id","price_audit_rpt.htm");
P.fA("Price Maintenance Audit Report by Type","price_audit_type_rpt.htm");
P.fA("Core Reports","order_processing_%20reports.17.140.htm");
P.fA("Pending Cores Due Report","pending_cores_rpt.htm");
P.fA("Core Returns Due Aging Report","core_aging_rpt.htm");
P.fA("Core (Issues) Sold on Exchange Report","core_iss_rpt.htm");
P.fA("Late Sales Order Report","late_so_anal_rpt.htm");
P.fA("Late Sales Order Detail Report","late_so_dtl_rpt.htm");
P.fA("Progress Billing Summary Report","prog_bill_sum_rpt.htm");
P.fA("Freight Comparison Report","frt_comp_rpt.htm");
P.fA("Customer Tax Exemptions Expiration Report","cust_tax_exempt_exp_rpt.htm");
P.fA("Customer Tax Certificates Report","cust_tax_cert_rpt.htm");
P.fA("Customer Job Analysis Report","custjob_analysis_rpt.htm");
P.fA("Order Processing Field Definitions","ar_comm_line_mnt.htm");
P.fA("Acceptable Quality Levels screen","aql_mnt.htm");
P.fA("Accessory Product Order Selection screen","prod_acc_ord_ent.htm");
P.fA("Additional Check Information screen","ord_check_addit.htm");
P.fA("Additional Credit Card Information screen","ord_credit_addit.htm");
P.fA("Additional Gift Certificate Information screen","ord_cert_addit.htm");
P.fA("Additional Information screen","qte_add_dtl_info.htm");
P.fA("Additional Information screen","agent_add_info.htm");
P.fA("Additional Options screen","insert_addit_opt.htm");
P.fA("Administered By Maintenance screen","adminby_mnt.htm");
P.fA("Allocate Backorders To Existing P/O\u2019s screen","so_po_link.htm");
P.fA("Auto Consignment Billing Update screen","auto_consign_bill_scr.htm");
P.fA("Auto Order Split screen","ord_auto_split_ent.htm");
P.fA("Auto Reverse Order screen","void_sale_ent.htm");
P.fA("Backorder Reallocation Availability screen","ord_realloc_scr.htm");
P.fA("Bill Of Lading Print screen","bl_print_prompts.htm");
P.fA("Blanket Contract Copy screen","bcm_copy.htm");
P.fA("Blanket Contract Customers screen","bl_ct_cn.htm");
P.fA("Blanket Contract Detail screen","bl_ct_mnt_line.htm");
P.fA("Blanket Contract Maintenance screen","bl_ct_mnt.htm");
P.fA("Branch Release Display screen","ord_brch_rel_disp.htm");
P.fA("Campaign Priority Code","campaign_priority.htm");
P.fA("Cash Application screen","ord_cash_appl.htm");
P.fA("Cash Customer Information screen","ord_cash_ent.htm");
P.fA("Catalog ID Code Maintenance screen","catalog_id_code_mnt.htm");
P.fA("Change \u2018All\u2019 Sales Rep\u2019s screen","ar_comm_chg_rep.htm");
P.fA("Change Credit Card Exp Date screen","cc_exp_date.htm");
P.fA("Commission Charges Entry screen","comm_chrg_ent.htm");
P.fA("Commission Cost Entry screen","commission_cost.htm");
P.fA("Commission Header Override screen","comm_ov.htm");
P.fA("Commission Maintenance screen","ar_comm_mnt.htm");
P.fA("Commission Matrix Input screen","comm_input.htm");
P.fA("Commission Matrix Maintenance screen","comm_mnt.htm");
P.fA("Commission Percent Change screen","ar_comm_chg_per.htm");
P.fA("Commission Splits screen","comm_split.htm");
P.fA("Component Entry screen","rel_accum_kit_ent.htm");
P.fA("Consignment Order Detail screen","ord_ent_line_cons.htm");
P.fA("Consignment Order History Inquiry screen","ord_cons_inq_2.htm");
P.fA("Consignment Types screen","ord_consign_type.htm");
P.fA("Consolidation Order View screen","cons_view_disp.htm");
P.fA("Consolidation Release Confirmation Entry screen","cons_rel_ent.htm");
P.fA("Contract Price Maintenance screen","contr_price_mnt.htm");
P.fA("Copy Contract Price screen","copy_contr_price.htm");
P.fA("Copy Contracts screen","mult_copy_contr_price.htm");
P.fA("Copy Existing Catalogs screen","prod_copy_catalog_mnt.htm");
P.fA("Credit Bureau Maintenance screen","service_bureau_mnt.htm");
P.fA("Credit Card Authorization Rejection Maintenance screen","cc_post_rej_mnt.htm");
P.fA("Credit Information screen","ord_cred_info.htm");
P.fA("Credit Memo Entry screen","field_definitions_ois.18.49.htm");
P.fA("Credit Reason Maintenance screen","credit_reason_mnt.htm");
P.fA("Crib to Warehouse Cross Reference Maintenance screen","crib_whse_mnt.htm");
P.fA("Currency Info screen","rel_exch_rate_scr.htm");
P.fA("Customer Department File Maintenance screen","cust_dept_mnt.htm");
P.fA("Customer Matrix Copy screen","copy_matrix_cnm1.htm");
P.fA("Customer Prescription Maintenance screen","cust_rx_mnt.htm");
P.fA("Customer Prescription Product Maintenance screen","cust_rx_prod_mnt.htm");
P.fA("Customer Price Group Copy screen","field_definitions_ois.18.57.htm");
P.fA("Customer Product Number Maintenance screen","cpnm.htm");
P.fA("Customer Ranking Procedure screen","cust_rank.htm");
P.fA("Customer Ship-To Verification screen","ord_cust_shipto_disp.htm");
P.fA("DD250 Invoice Printing screen","dd20_print_prompts.htm");
P.fA("Deletion Process For Expired Catalogs screen","prod_alt_xref_clear_mnt.htm");
P.fA("Discount Break Table Maintenance screen","disc_mnt.htm");
P.fA("Discount Reason Code Maintenance screen","disc_reas_code_mnt.htm");
P.fA("Discount Table - Percent screen","disc_perc.htm");
P.fA("Discount Table - Dollar screen","disc_amt.htm");
P.fA("Facility Maintenance screen","fac_mnt.htm");
P.fA("Floor Plan Number Maintenance screen","fp_mnt.htm");
P.fA("Force Duplicate Authorization screen","cc_batch_force.htm");
P.fA("Freight Cost screen","rel_frt_cst.htm");
P.fA("Future Commitment Override screen","ord_fut_commit_ov.htm");
P.fA("Generate P/Os for Backorders screen","ord_update_gen_pos.htm");
P.fA("Gift Certificate Maintenance screen","gift_cert_mnt.htm");
P.fA("Gross Profit Range Maintenance screen","gp_range_mnt.htm");
P.fA("Header Information screen","bl_ct_hdr.htm");
P.fA("IC Verify Batch Inquiry screen","cc_icv_batch_inq.htm");
P.fA("Insert Code Product Lines screen","insert_code_pline_mnt.htm");
P.fA("Insert Code Product Numbers screen","insert_code_pn_mnt.htm");
P.fA("Inspection Procedures screen","field_definitions_ois.18.79.htm");
P.fA("Inspection Results Entry screen","inspection_ent.htm");
P.fA("Inspections Summary Statistics screen","inspection.sum.htm");
P.fA("Instruction Messages Maintenance screen","intrnal_msgs_mnt.htm");
P.fA("Invoice Print Prompts screen","inv_print_prompts.htm");
P.fA("Invoice Reprint Entry screen","inv_batch_reprint.htm");
P.fA("Kit Entry screen","ord_kit_ent.htm");
P.fA("Line Item Credit Detail screen","ord_ent_line_cred.htm");
P.fA("Line Item Detail Additional Information screen","ord_add_dtl_info.htm");
P.fA("Line Item Detail screen","ord_ent_line.htm");
P.fA("Location Retrieval screen","selling_prompt.htm");
P.fA("Lost Quote Reasons screen","qte_disp_reas.htm");
P.fA("Lost Sales Entry screen","lost_sale_ent.htm");
P.fA("Lost Sales Reason Maintenance screen","lost_sls_mnt.htm");
P.fA("M/R Completion screen","rep_complete.htm");
P.fA("M/R Detail Information screen","rep_dtl_line.htm");
P.fA("M/R Display screen","rep_ent_disp.htm");
P.fA("M/R Order Header screen","rep_hdr.htm");
P.fA("M/R Process Routine screen","rep_prompts.htm");
P.fA("M/R Ship-To Address screen","rep_ship_to.htm");
P.fA("Manual Administrative Hold screen","manual_adm_hold.htm");
P.fA("Manual Credit Hold Status Procedure screen","ord_credit_hold.htm");
P.fA("Manufacturer Rep Order Entry screen","rep_ent.htm");
P.fA("Maximum RX Month Maintenance screen","max_rx_mth.htm");
P.fA("Miscellaneous Amount Entry screen","misc_gl_ent.htm");
P.fA("Miscellaneous Reason Code Maintenance screen","misc_reas_code_mnt.htm");
P.fA("Order Cancellation Reason Maintenance screen","ord_del_mnt.htm");
P.fA("Order Dates screen","ord_dates.htm");
P.fA("Order Duplication Entry screen","ord_dup_ent.htm");
P.fA("Order Duplication History Entry Screen","ord_hist_%20dup_ent.htm");
P.fA("Order History Inquiry Display screen","ord_hist_ent_disp.htm");
P.fA("Order Line Split screen","ord_split_line.htm");
P.fA("Order Route Information screen","ord_rte_info.htm");
P.fA("Order Source Code Maintenance screen","ord_src_mnt.htm");
P.fA("Order Totals screen","ord_totals.htm");
P.fA("Other Sales Rep Input screen","comm_add_rep_input.htm");
P.fA("Override Shipping Whse Matrix screen","shp_whse_matrix_mnt.htm");
P.fA("Package Insert Code Maintenance screen","insert_code_mnt.htm");
P.fA("Payment By Maintenance screen","payment_by_mnt.htm");
P.fA("Pick Ticket Printing screen","pck_print_prompts.htm");
P.fA("Picker Maintenance screen","picker_mnt.htm");
P.fA("Price Label Format Maintenance screen","prc_lab_mnt.htm");
P.fA("Price Matrix Input screen","price_input.htm");
P.fA("Price Matrix Maintenance screen","price_mnt.htm");
P.fA("Price Matrix Mass Copy screen","pmm_copy_mnt.htm");
P.fA("Price Matrix Mass Update screen","pmm_upd_mnt.htm");
P.fA("Price Override Reason Code Mnt screen","rsn_code_mnt.htm");
P.fA("Print B/O Notice screen","print_bo_notice_scr.htm");
P.fA("Product Number/State Entry screen","prod_num_ent.htm");
P.fA("Product/State Entry screen","prod_line_ent.htm");
P.fA("Product Substitutes Inquiry screen","prod_sub_inq.htm");
P.fA("Progress Billing Entry screen","progress_billing_entry.htm");
P.fA("Promotional Product Pricing screen","promo_prod_price.htm");
P.fA("Promotion Exception Maintenance screen","promo_exc_mnt.htm");
P.fA("Promotion Matrix Maintenance Header screen","promo_hdr.htm");
P.fA("Promotion Product Exception Maintenance screen","promo_prd_exc_mnt.htm");
P.fA("Promotion Type Matrix Maintenance screen","promo_mnt.htm");
P.fA("Purchase Cost screen","price_purch_cst.htm");
P.fA("Quality Agent Maintenance screen","agent_mnt.htm");
P.fA("Quality Corrective Action Entry screen","corr_action_ent.htm");
P.fA("Quality Feedback Entry screen","feedback_ent.htm");
P.fA("Quality Incident Entry screen","incident_ent.htm");
P.fA("Quality Inspection Procedure Maintenance screen","insp_proc_mnt.htm");
P.fA("Quality Inspection Default Maintenance screen","aql_def_mnt.htm");
P.fA("Quick Matrix Entry/Product Line screen","qme_pline_scr.htm");
P.fA("Quick Matrix Entry Product/Number screen","qme_pn_scr.htm");
P.fA("Quotation Additional Information screen","qte_add_info.htm");
P.fA("Quotation Completion screen","qte_complete.htm");
P.fA("Quotation Display screen","qte_ent_disp.htm");
P.fA("Quotation Header screen","qte_hdr.htm");
P.fA("Quote Order Entry screen","qte_ent.htm");
P.fA("Quote Conversion screen","qte_conv.htm");
P.fA("Quote Disposition Maintenance screen","qte_disp_mnt.htm");
P.fA("Quote Entry Detail screen","qte_ent_line.htm");
P.fA("Quote Line Item Conversion screen","ord_ql_conv.htm");
P.fA("Quote/Order Created Price Matrix screen","qte_created_price_matrix.htm");
P.fA("Rate Shop Results screen","rateshop_window.htm");
P.fA("Release Confirmation Entry screen","rel_ent.htm");
P.fA("Release Header screen","rel_hdr.htm");
P.fA("Release Shipment Data screen","rel_ship_boxes.htm");
P.fA("Repair Order Type Screen","ord_repair_type.htm");
P.fA("Repair Type Screen","qte_repair_type.htm");
P.fA("Request for Quotation Entry Screen","rfq_ent.htm");
P.fA("Request For Quotation Print Screen","rfq_print_prompts.htm");
P.fA("Restocking Fee Ranges screen","rstk_fee_mnt.htm");
P.fA("Restricted Product Matrix Maintenance screen","rstr_prd_mat_mnt.htm");
P.fA("Restricted Product Matrix Input screen","rstr_prd_pl.htm");
P.fA("Retail Price Matrix Input screen","ret_price_input.htm");
P.fA("Retail Price Matrix Maintenance screen","ret_price_mnt.htm");
P.fA("Retail Price Rounding Maintenance screen","rtl_prc_rnd_mnt.htm");
P.fA("RX Counter Range Setup screen","rx_ctr_setup.htm");
P.fA("RX Group Maintenance screen","rx_grp_mnt.htm");
P.fA("RX Physician Maintenance screen","phys_mnt.htm");
P.fA("Sales Order Completion screen","ord_complete.htm");
P.fA("Sales Order Credit Card Authorization Entry screen","ord_cc_auth_ent.htm");
P.fA("Sales Order Display screen","ord_ent_disp_exp.htm");
P.fA("Sales Order Duplication screen","user_sales_ord_dup.htm");
P.fA("Sales Order Entry screen","ord_ent.htm");
P.fA("Sales Order Header screen","ord_hdr.htm");
P.fA("Sales Tax Flags Entry screen","ord_ent_tax_flags.htm");
P.fA("Sales Tax Jurisdictions screen","ord_complete_ent_tax.htm");
P.fA("Sample Size Code Letter Maintenance screen","aql_insp_level.htm");
P.fA("Serial Shipping Container Entry screen","pkg_ent.htm");
P.fA("Service Additional Information screen","srv_addit_info.htm");
P.fA("Shipping Consolidation screen","ord_shp_consol_scr.htm");
P.fA("Shipping Label Printing screen","lbl_print_prompts.htm");
P.fA("Shipping Warehouse Entry screen","ship_whse_ent.htm");
P.fA("Skeleton Product Maintenance screen","new_prod_mnt.htm");
P.fA("Stand-Alone Email Shipping Notice screen","standalone_email_ship_notice.htm");
P.fA("Standard Carrier Alpha Code Maintenance screen","scac_mnt.htm");
P.fA("Standing Order Maintenance screen","qte_stand_type.htm");
P.fA("Summary Invoice Detail Reprint screen","field_definitions_ois.18.190.htm");
P.fA("Summary Invoice Printing screen","sum_inv_print_prompts.htm");
P.fA("Universal Customer Merge Entry screen","cust_repl_xref_build_merge.htm");
P.fA("Upsell Entry screen","prod_upsell_ord_ent.htm");
P.fA("Vendor Information screen","vend_info.htm");
P.fA("Vendor/Selling Warehouse Entry screen","vend_sell_ent.htm");
P.fA("Via Retail Info Maintenance screen","sam_via_info.htm");
P.fA("Warehouse Exclusions screen","whse_excl_scr.htm");
P.fA("Warehouse Hold Area Maintenance screen","whse_hold_area_mnt.htm");
P.fA("Zip Exclusions screen","zip_excl_scr.htm");
}
