function FileData_Pairs(x)
{
x.t("example","http://www.prelude.com/ivia8/vialauncher.jsp");
x.t("categoriesexample","http://www.prelude.com/ivia8/");
x.t("pages","products");
x.t("vialauncher.jsp","targetpage=http://www.prelude.com/ivia8/viauserdoc.jsp");
x.t("product","example");
x.t("product","categoriesexample");
x.t("url","links");
x.t("via","website");
x.t("via","launcher");
x.t("products","via");
x.t("direct","users");
x.t("&modifier=search","&reqtitle=title_viaproductlookup");
x.t("&searchtext=handtools","&reqtitle=title_viauserdoclist");
x.t("http://www.prelude.com/ivia8/vialauncher.jsp","targetpage=http://");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("targetpage=http://","www.prelude.com/ivia8/vialistproducts.jsp");
x.t("website","product");
x.t("&reqtitle=title_viauserdoclist","product");
x.t("www.prelude.com/ivia8/vialistproducts.jsp","&searchtext=1y125");
x.t("targetpage=http://www.prelude.com/ivia8/viauserdoc.jsp","&searchtext=handtools");
x.t("&reqtitle=title_viaproductlookup","via");
x.t("&searchtext=1y125","&modifier=search");
x.t("launcher","url");
x.t("launcher","via");
x.t("launcher","activant");
x.t("users","pages");
x.t("activant","solutions");
x.t("http://www.prelude.com/ivia8/","vialauncher.jsp");
x.t("links","direct");
x.t("866-878-0574","972-403-3150");
}
