function FileData_Pairs(x)
{
x.t("provide","status");
x.t("summary","report");
x.t("open","quotation");
x.t("price","override");
x.t("status","information");
x.t("quotation","disposition");
x.t("quotation","report");
x.t("quotation","reports");
x.t("quotation","subsystem");
x.t("quotes","open");
x.t("disposition","summary");
x.t("disposition","detail");
x.t("quote","price");
x.t("quote","follow");
x.t("report","quotation");
x.t("report","quote");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("reports","quotation");
x.t("reports","activant");
x.t("reports","following");
x.t("follow","report");
x.t("override","audit");
x.t("subsystem","provide");
x.t("subsystem",":quotation");
x.t("information","quotes");
x.t("activant","solutions");
x.t("audit","report");
x.t("following","reports");
x.t("866-878-0574","972-403-3150");
x.t(":quotation","reports");
x.t("detail","report");
}
