function FileData_Pairs(x)
{
x.t("deleting","quotes");
x.t("deleting","quote");
x.t("refer","following");
x.t("delete","quote");
x.t("entering","disposition");
x.t("creating","quote");
x.t("codes","deleting");
x.t("quotation","subsystem");
x.t("quotes","deleting");
x.t("quotes","delete");
x.t("quotes","creating");
x.t("quotes","activant");
x.t("disposition","codes");
x.t("disposition","code");
x.t("quote","quotation");
x.t("quote","disposition");
x.t("quote","lost");
x.t("quote","update");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("explain","quote");
x.t("lost","refer");
x.t("lost","quotations");
x.t("code","explain");
x.t("subsystem",":deleting");
x.t("information","deleting");
x.t("activant","solutions");
x.t("following","information");
x.t("866-878-0574","972-403-3150");
x.t(":deleting","quotes");
x.t("update","lost");
x.t("quotations","entering");
}
