function FileData_Pairs(x)
{
x.t("product","complaint");
x.t("product","complaints");
x.t("entry","quality");
x.t("record","review");
x.t("inspection","subsystem");
x.t("recording","product");
x.t("quality","inspection");
x.t("quality","control");
x.t("quality","feedback");
x.t("review","product");
x.t("control","information");
x.t("report","quality");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("complaint","recording");
x.t("complaint","activant");
x.t("complaint","following");
x.t("subsystem","tracking");
x.t("information",":recording");
x.t("feedback","entry");
x.t("feedback","report");
x.t("activant","solutions");
x.t("following","record");
x.t("866-878-0574","972-403-3150");
x.t("tracking","quality");
x.t("complaints","quality");
x.t(":recording","product");
}
