function FileData_Pairs(x)
{
x.t("provide","detail");
x.t(":monthly","detail");
x.t("sales","report");
x.t("sales","information");
x.t("sales","vendor");
x.t("month","monthly");
x.t("monthly","cost");
x.t("monthly","lost");
x.t("monthly","detail");
x.t("catalog","order");
x.t("cost","override");
x.t("processing","reports");
x.t("report","monthly");
x.t("report","catalog");
x.t("report","order");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("lost","sales");
x.t("reports","provide");
x.t("reports",":monthly");
x.t("reports","monthly");
x.t("reports","activant");
x.t("reports","following");
x.t("override","audit");
x.t("information","month");
x.t("history","report");
x.t("activant","solutions");
x.t("audit","report");
x.t("order","processing");
x.t("order","history");
x.t("following","reports");
x.t("866-878-0574","972-403-3150");
x.t("vendor","report");
x.t("detail","sales");
x.t("detail","reports");
}
