function FileData_Pairs(x)
{
x.t("provide","detail");
x.t("summary","report");
x.t("tax","summary");
x.t("tax","reports");
x.t("tax","information");
x.t("tax","adjustment");
x.t("tax","detail");
x.t(":monthly","sales");
x.t("sales","tax");
x.t("month","monthly");
x.t("monthly","sales");
x.t("monthly","accounting");
x.t("processing","reports");
x.t("report","monthly");
x.t("report","order");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("reports","provide");
x.t("reports",":monthly");
x.t("reports","monthly");
x.t("reports","activant");
x.t("reports","following");
x.t("accounting","reports");
x.t("information","month");
x.t("activant","solutions");
x.t("order","processing");
x.t("following","reports");
x.t("866-878-0574","972-403-3150");
x.t("adjustment","summary");
x.t("adjustment","detail");
x.t("detail","sales");
x.t("detail","report");
}
