function FileData_Pairs(x)
{
x.t("salesreps","customers");
x.t(":overriding","commission");
x.t("refer","following");
x.t("calculations","may");
x.t("default","commission");
x.t("price","matrix");
x.t("entry","refer");
x.t("entry","commission");
x.t("products","override");
x.t("sales","order");
x.t("overriding","commission");
x.t("cost","using");
x.t("may","salesreps");
x.t("maintenance","sales");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("customers","products");
x.t("override","commission");
x.t("matrix","overriding");
x.t("matrix","maintenance");
x.t("subsystem",":overriding");
x.t("although","default");
x.t("information","overriding");
x.t("activant","solutions");
x.t("order","entry");
x.t("following","information");
x.t("866-878-0574","972-403-3150");
x.t("using","price");
x.t("commission","calculations");
x.t("commission","price");
x.t("commission","sales");
x.t("commission","overriding");
x.t("commission","cost");
x.t("commission","subsystem");
x.t("commission","although");
x.t("commission","activant");
}
