function FileData_Pairs(x)
{
x.t("just","single");
x.t("create","new");
x.t("refer","following");
x.t("once","price");
x.t("copying","multiple");
x.t("copying","single");
x.t("copying","price");
x.t("multiple","price");
x.t("product","product");
x.t("product","pricing");
x.t("single","price");
x.t("single","matrix");
x.t("new","similar");
x.t("price","matrices");
x.t("price","matrix");
x.t("group","matrices");
x.t("matrices","just");
x.t("matrices","refer");
x.t("matrices","once");
x.t("matrices","copying");
x.t("matrices","product");
x.t("matrices","activant");
x.t("matrices","copy");
x.t("matrices",":copying");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("pricing","price");
x.t("matrix","create");
x.t("matrix","copying");
x.t("similar","price");
x.t("activant","solutions");
x.t("copy","group");
x.t("following","copying");
x.t("866-878-0574","972-403-3150");
x.t(":copying","price");
}
