function FileData_Pairs(x)
{
x.t("inquiries","available");
x.t("inquiries","manufacturer\u2019s");
x.t("inquiries","activant");
x.t("inquiries","following");
x.t("available","prelude");
x.t("inquiry","manufacturer");
x.t("inquiry","manufacturer\u2019s");
x.t("prelude","manufacturer");
x.t("rep/history","inquiry");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("manufacturer","rep/history");
x.t("manufacturer","rep");
x.t("manufacturer","rep/customer");
x.t("manufacturer","rep/product");
x.t("rep","inquiries");
x.t("rep","inquiry");
x.t("rep","subsystem");
x.t("manufacturer\u2019s","rep");
x.t("subsystem",":manufacturer\u2019s");
x.t("rep/customer","inquiry");
x.t("rep/customer","history");
x.t("history","inquiry");
x.t("activant","solutions");
x.t(":manufacturer\u2019s","rep");
x.t("following","manufacturer\u2019s");
x.t("866-878-0574","972-403-3150");
x.t("rep/product","inquiry");
x.t("rep/product","history");
}
