function FileData_Pairs(x)
{
x.t("provide","tax");
x.t("day","daily");
x.t("summary","report");
x.t("orders","day");
x.t("tax","summary");
x.t("tax","reports");
x.t("tax","information");
x.t("tax","adjustment");
x.t("tax","detail");
x.t("sales","orders");
x.t("sales","tax");
x.t("processing","reports");
x.t("report","daily");
x.t("report","order");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("reports","provide");
x.t("reports","activant");
x.t("reports","daily");
x.t("reports","following");
x.t("reports",":daily");
x.t("accounting","reports");
x.t("information","sales");
x.t("activant","solutions");
x.t("daily","sales");
x.t("daily","accounting");
x.t("order","processing");
x.t("following","reports");
x.t(":daily","sales");
x.t("866-878-0574","972-403-3150");
x.t("adjustment","summary");
x.t("adjustment","detail");
x.t("detail","report");
}
