function FileData_Pairs(x)
{
x.t("refer","following");
x.t("line","items");
x.t("customer","entering");
x.t(":entering","sales");
x.t("sections","information");
x.t("items","finishing");
x.t("finishing","sales");
x.t("printing",":entering");
x.t("entering","sales");
x.t("entry","printing");
x.t("sales","order");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("header","information");
x.t("selecting","customer");
x.t("information","entering");
x.t("activant","solutions");
x.t("order","refer");
x.t("order","line");
x.t("order","entering");
x.t("order","entry");
x.t("order","sales");
x.t("order","header");
x.t("order","selecting");
x.t("order","activant");
x.t("following","sections");
x.t("866-878-0574","972-403-3150");
}
