function FileData_Pairs(x)
{
x.t("ship","whse");
x.t(":consignment","reports");
x.t("sales","order");
x.t("display","daily");
x.t("review","date");
x.t("processing","reports");
x.t("report","ship");
x.t("report","consignment");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("release","report");
x.t("reports",":consignment");
x.t("reports","display");
x.t("reports","activant");
x.t("reports","daily");
x.t("reports","following");
x.t("reports","consignment");
x.t("whse","order");
x.t("information","consignment");
x.t("date","report");
x.t("activant","solutions");
x.t("daily","order");
x.t("daily","consignment");
x.t("order","processing");
x.t("order","release");
x.t("order","information");
x.t("order","detail");
x.t("following","reports");
x.t("866-878-0574","972-403-3150");
x.t("consignment","sales");
x.t("consignment","review");
x.t("consignment","reports");
x.t("consignment","order");
x.t("detail","reports");
}
