function FileData_Pairs(x)
{
x.t("miscellaneous","reports");
x.t("available","reports");
x.t("summary","reports");
x.t("menu","order");
x.t("monthly","accounting");
x.t("monthly","detail");
x.t("processing","reports");
x.t("processing","module");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("reports","miscellaneous");
x.t("reports","available");
x.t("reports","menu");
x.t("reports","monthly");
x.t("reports","activant");
x.t("reports","daily");
x.t("reports","order");
x.t("reports","following");
x.t("groups","reports");
x.t("accounting","reports");
x.t("module","daily");
x.t("activant","solutions");
x.t("daily","accounting");
x.t("daily","order");
x.t("order","summary");
x.t("order","processing");
x.t("order","detail");
x.t("following","groups");
x.t("866-878-0574","972-403-3150");
x.t("detail","reports");
}
