function FileData_Pairs(x)
{
x.t("action","information");
x.t("product","quality");
x.t("entry","quality");
x.t("inspection","subsystem");
x.t("quality","inspection");
x.t("quality","control");
x.t("quality","incident");
x.t("collect","review");
x.t("review","feedback");
x.t("corrective","action");
x.t(":collecting","quality");
x.t("control","information");
x.t("control","incident");
x.t("report","quality");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("subsystem","tracking");
x.t("information","product");
x.t("information",":collecting");
x.t("information","collecting");
x.t("information","activant");
x.t("information","following");
x.t("collecting","quality");
x.t("feedback","corrective");
x.t("incident","entry");
x.t("incident","report");
x.t("incident","information");
x.t("activant","solutions");
x.t("following","collect");
x.t("866-878-0574","972-403-3150");
x.t("tracking","quality");
}
