function FileData_Pairs(x)
{
x.t("cancelling","backorder");
x.t("deleting","sales");
x.t("refer","following");
x.t("required","date");
x.t("backorder","sales");
x.t("orders","deleting");
x.t("orders","delete");
x.t("orders","activant");
x.t("orders","manually");
x.t("delete","sales");
x.t("product","received");
x.t("automatically","cancelling");
x.t("printing",":deleting");
x.t("cancellation","date");
x.t("entry","printing");
x.t("entry","automatic");
x.t("sales","orders");
x.t("sales","order");
x.t("backordered","product");
x.t("automatic","cancellation");
x.t("reason","sales");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("received","required");
x.t("date","refer");
x.t("date","sales");
x.t("activant","solutions");
x.t("order","automatically");
x.t("order","entry");
x.t("order","backordered");
x.t("order","reason");
x.t("following","deleting");
x.t("866-878-0574","972-403-3150");
x.t("manually","deleting");
x.t(":deleting","sales");
}
