function FileData_Pairs(x)
{
x.t("included","contract");
x.t("just","product");
x.t("refer","following");
x.t("copying","customer");
x.t("copying","contract");
x.t("customer","new");
x.t("customer","contract");
x.t("customer","products");
x.t("copied","copy");
x.t("product","refer");
x.t("product","product");
x.t("product","pricing");
x.t("contract","copying");
x.t("contract","customer");
x.t("contract","copied");
x.t("contract","product");
x.t("contract","pricing");
x.t("contract","information");
x.t("contract","activant");
x.t("contract","copy");
x.t("new","customer");
x.t("products","included");
x.t("entire","contract");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("pricing","contract");
x.t("pricing",":copying");
x.t("information","just");
x.t("activant","solutions");
x.t("copy","contract");
x.t("copy","entire");
x.t("following","copying");
x.t("866-878-0574","972-403-3150");
x.t(":copying","contract");
}
