function FileData_Pairs(x)
{
x.t("email","transmission");
x.t("refer","following");
x.t("re-email","invoice");
x.t(":re-printing","invoices");
x.t("multiple","invoices");
x.t("group","invoices");
x.t("invoice","group");
x.t("invoice","re-printing");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("transmission","re-print");
x.t("fax","email");
x.t("activant","solutions");
x.t("re-printing","multiple");
x.t("re-printing","invoice");
x.t("re-printing","invoices");
x.t("printer","jammed");
x.t("following","re-printing");
x.t("866-878-0574","972-403-3150");
x.t("re-fax","re-email");
x.t("invoices","refer");
x.t("invoices","activant");
x.t("invoices","re-printing");
x.t("invoices","printer");
x.t("invoices","invoicing");
x.t("re-print","re-fax");
x.t("jammed","fax");
x.t("invoicing",":re-printing");
}
