function FileData_Pairs(x)
{
x.t("salesrep1","daily");
x.t("provide","gross");
x.t("salesrep2","daily");
x.t("day","daily");
x.t("written-by","daily");
x.t("gross","profit");
x.t("customer","daily");
x.t("selling","warehouse");
x.t("processing","reports");
x.t("report","salesrep1");
x.t("report","salesrep2");
x.t("report","written-by");
x.t("report","customer");
x.t("report","selling");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("reports","provide");
x.t("reports","activant");
x.t("reports","daily");
x.t("reports","following");
x.t("reports",":daily");
x.t("profit","report");
x.t("profit","reports");
x.t("profit","information");
x.t("accounting","reports");
x.t("information","day");
x.t("activant","solutions");
x.t("daily","gross");
x.t("daily","accounting");
x.t("order","processing");
x.t("following","reports");
x.t(":daily","gross");
x.t("866-878-0574","972-403-3150");
x.t("warehouse","order");
}
