function FileData_Pairs(x)
{
x.t("continuously","upon");
x.t("refer","following");
x.t("completion","sales");
x.t(":printing","pick");
x.t("batch","refer");
x.t("batch","sales");
x.t("queue","print");
x.t("printing",":printing");
x.t("printing","pick");
x.t("entry","printing");
x.t("ticket","rules");
x.t("tickets","continuously");
x.t("tickets","batch");
x.t("tickets","queue");
x.t("tickets","printing");
x.t("tickets","choose");
x.t("tickets","activant");
x.t("tickets","setting");
x.t("sales","order");
x.t("hold","tickets");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("upon","completion");
x.t("pick","ticket");
x.t("pick","tickets");
x.t("rules","printing");
x.t("information","printing");
x.t("choose","print");
x.t("print","batch");
x.t("print","pick");
x.t("activant","solutions");
x.t("order","entry");
x.t("order","hold");
x.t("following","information");
x.t("866-878-0574","972-403-3150");
x.t("setting","pick");
}
