function FileData_Pairs(x)
{
x.t("action","entry");
x.t("action","report");
x.t("actions","recording");
x.t("actions","taken");
x.t("actions","activant");
x.t("actions","following");
x.t("entry","quality");
x.t("inspection","subsystem");
x.t("recording","corrective");
x.t("quality","inspection");
x.t("quality","corrective");
x.t("quality","control");
x.t("corrective","action");
x.t("corrective","actions");
x.t("review","corrective");
x.t("control","information");
x.t("report","quality");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("enter","review");
x.t("taken","complaints");
x.t("subsystem","tracking");
x.t("information",":recording");
x.t("activant","solutions");
x.t("following","enter");
x.t("866-878-0574","972-403-3150");
x.t("tracking","quality");
x.t("complaints","quality");
x.t(":recording","corrective");
}
