function FileData_Pairs(x)
{
x.t("email","fax");
x.t("refer","faxing");
x.t("refer","following");
x.t("uses","term");
x.t(":printing","quotes");
x.t("customer","refer");
x.t("batch","although");
x.t("emailing","quotation");
x.t("printing","quotes");
x.t("printing","may");
x.t("printing","depending");
x.t("settings","printing");
x.t("faxing","emailing");
x.t("quotation","subsystem");
x.t("quotes","batch");
x.t("quotes","printing");
x.t("quotes","print");
x.t("quotes","activant");
x.t("options","printing");
x.t("prelude","uses");
x.t("quote","customer");
x.t("maintenance","options");
x.t("may","refer");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("term","printing");
x.t("depending","systems");
x.t("subsystem",":printing");
x.t("although","prelude");
x.t("systems","settings");
x.t("fax","quote");
x.t("print","email");
x.t("activant","solutions");
x.t("following","setting");
x.t("866-878-0574","972-403-3150");
x.t("setting","maintenance");
}
