function FileData_Pairs(x)
{
x.t("billing","flag");
x.t("billing","field");
x.t("billing","sure");
x.t("billing",":rental");
x.t("flag","path");
x.t("field","pre-billing");
x.t("(/roe)","rental");
x.t("(/roe)","activant");
x.t("change","rollup");
x.t("entry","(/roe)");
x.t("entry","rollup");
x.t("sure","rental");
x.t("path","rental");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("header","exited");
x.t("rental","rental");
x.t("rental","financials");
x.t("rental","order");
x.t("rental","rollup");
x.t("rental","pre-billing");
x.t("financials","rental");
x.t(":rental","order");
x.t("activant","solutions");
x.t("exited","change");
x.t("order","entry");
x.t("order","header");
x.t("866-878-0574","972-403-3150");
x.t("rollup","billing");
x.t("pre-billing","rental");
x.t("pre-billing","rollup");
}
