function FileData_Pairs(x)
{
x.t("defaulted","form");
x.t("billing","flag");
x.t("flag","rental");
x.t("(/roe)","rental");
x.t("(/roe)","save");
x.t("(/roe)","activant");
x.t("customer","level");
x.t("change","setting");
x.t("form","system");
x.t("pre","billing");
x.t("entry","(/roe)");
x.t("settings","change");
x.t("edit","rental");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("level","settings");
x.t("header","edit");
x.t("rental","pre");
x.t("rental","financials");
x.t("rental","information");
x.t("rental","order");
x.t("rental","pre-billing");
x.t("financials","rental");
x.t("information","defaulted");
x.t("save","rental");
x.t(":rental","order");
x.t("activant","solutions");
x.t("order","entry");
x.t("order","header");
x.t("order","pre-billing");
x.t("system","customer");
x.t("866-878-0574","972-403-3150");
x.t("setting","rental");
x.t("pre-billing","rental");
x.t("pre-billing",":rental");
}
