function FileData_Pairs(x)
{
x.t("billing","default");
x.t("billing","periodic");
x.t("billing",":rental");
x.t("field","path");
x.t("(/roe)","rental");
x.t("(/roe)","save");
x.t("(/roe)","activant");
x.t("default","field");
x.t("entry","(/roe)");
x.t("entry","rental");
x.t("path","rental");
x.t("periodic","billing");
x.t("appears","rental");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("header","screen");
x.t("rental","rental");
x.t("rental","financials");
x.t("rental","information");
x.t("rental","order");
x.t("financials","periodic");
x.t("screen","appears");
x.t("information","order");
x.t("save","rental");
x.t(":rental","order");
x.t("activant","solutions");
x.t("order","entry");
x.t("order","periodic");
x.t("order","header");
x.t("866-878-0574","972-403-3150");
}
