function  WWHBookData_Files(P)
{
P.fA("Overview","Ch1_overview.1.1.htm");
P.fA("Accounts Payable Maintenance Requirements","Ch2_AP_info.2.1.htm");
P.fA("Setting up Accounts Payable Parameters","Ch2_AP_info.2.2.htm");
P.fA("Using Accounts Payable Terms","Ch2_AP_info.2.3.htm");
P.fA("Defining A/P Terms","Ch2_AP_info.2.4.htm");
P.fA("Creating A/P Terms","Ch2_AP_info.2.5.htm");
P.fA("Creating Payable Types","Ch2_AP_info.2.6.htm");
P.fA("Establishing Cost Adjustment Reason Codes","Ch2_AP_info.2.7.htm");
P.fA("Tracking Floor Plan Inventory","Ch2_AP_info.2.8.htm");
P.fA("Creating and Assigning Vendor Discount Codes","Ch2_AP_info.2.9.htm");
P.fA("Creating On-Discount Codes","Ch2_AP_info.2.10.htm");
P.fA("Creating Off-Discount Codes","Ch2_AP_info.2.11.htm");
P.fA("Vendor Invoice Reconciliation","Ch3_vend_inv.3.1.htm");
P.fA("Reconciling Vendor Invoices","Ch3_vend_inv.3.2.htm");
P.fA("Reconciling a Vendor Invoice to a Receiver","Ch3_vend_inv.3.3.htm");
P.fA("Adjusting Discrepancies","Ch3_vend_inv.3.4.htm");
P.fA("Recosting a P/O","Ch3_vend_inv.3.5.htm");
P.fA("Posting to a G/L Discrepancy Account","Ch3_vend_inv.3.6.htm");
P.fA("Creating an Additional Invoice","Ch3_vend_inv.3.7.htm");
P.fA("Placing an Invoice on Buyer Hold","Ch3_vend_inv.3.8.htm");
P.fA("Entering a Credit or Debit Memo","Ch3_vend_inv.3.9.htm");
P.fA("Splitting a Single Receiver","Ch3_vend_inv.3.10.htm");
P.fA("Merging Receivers","Ch3_vend_inv.3.11.htm");
P.fA("Pre-Paying a Vendor","Ch3_vend_inv.3.12.htm");
P.fA("Accounts Payable Released Inquiry","apri.htm");
P.fA("Reconciling High Volume EDI Invoices","Ch3_vend_inv.3.14.htm");
P.fA("Entering High Volume Vendor Invoices","Ch3_vend_inv.3.15.htm");
P.fA("Previewing Reconciled High Volume Vendor Invoices","Ch3_vend_inv.3.16.htm");
P.fA("Reconciling High Volume Vendor Invoices","Ch3_vend_inv.3.17.htm");
P.fA("Correcting Open High-Volume Vendor Invoices","Ch3_vend_inv.3.18.htm");
P.fA("EDI Freight Invoice Second Level Inquiry","edi_freight_inq.htm");
P.fA("Paying on Receipt","pay_on_rec.htm");
P.fA("Posting Expense Invoices","Ch3_vend_inv.3.21.htm");
P.fA("Setting Up Recurring Expense Invoices","Ch3_vend_inv.3.22.htm");
P.fA("Entering a Batch of Recurring Invoices","Ch3_vend_inv.3.23.htm");
P.fA("Recurring Vendor Invoice Report","rec_vend_inv_rpt.htm");
P.fA("Posting Recurring Vendor Invoices","Ch3_vend_inv.3.25.htm");
P.fA("Manually Entering Expense Invoices","Ch3_vend_inv.3.26.htm");
P.fA("Starting a Batch of Manual Invoices","Ch3_vend_inv.3.27.htm");
P.fA("Posting Manual Invoices","Ch3_vend_inv.3.28.htm");
P.fA("Posting Manual Invoices for Assets","Ch3_vend_inv.3.29.htm");
P.fA("Correcting a Vendor Number or Invoice Number","Ch3_vend_inv.3.30.htm");
P.fA("Changing Payment Terms for Open Invoices","change_ap_terms_process.htm");
P.fA("Creating Letters of Credit","Ch3_vend_inv.3.32.htm");
P.fA("Vendor Claim Reconciliation","Ch5_vend_claims.4.1.htm");
P.fA("Reconciling a Vendor Claim with a Credit Memo","Ch5_vend_claims.4.2.htm");
P.fA("Adjusting Discrepancies","Ch5_vend_claims.4.3.htm");
P.fA("Recosting a Vendor Claim","Ch5_vend_claims.4.4.htm");
P.fA("Posting a Discrepancy to a G/L Account","Ch5_vend_claims.4.5.htm");
P.fA("Creating an Additional Debit or Credit Memo","Ch5_vend_claims.4.6.htm");
P.fA("Placing the Vendor Claim on Buyer Hold","Ch5_vend_claims.4.7.htm");
P.fA("Entering a Credit or Debit Memo","Ch5_vend_claims.4.8.htm");
P.fA("Splitting a Single Claim","Ch5_vend_claims.4.9.htm");
P.fA("Merging Vendor Claims","Ch5_vend_claims.4.10.htm");
P.fA("Vendor Payment","Ch4_checks.5.1.htm");
P.fA("Selecting Vendors/Invoices to Pay","Ch4_checks.5.2.htm");
P.fA("Automatically Selecting Invoices to Pay","Ch4_checks.5.3.htm");
P.fA("Manually Selecting Invoices to Pay","Ch4_checks.5.4.htm");
P.fA("Manually Selecting Invoices After Auto Selecting","Ch4_checks.5.5.htm");
P.fA("Accounts Payable Payment Selection Register","Ch4_checks.5.6.htm");
P.fA("Paying the Vendor","Ch4_checks.5.7.htm");
P.fA("Transferring Funds Electronically (EFT)","Ch4_checks.5.8.htm");
P.fA("Paying by Automatic Bank Deduction (ABD)","Ch4_checks.5.9.htm");
P.fA("Paying by Credit Card","Ch4_checks.5.10.htm");
P.fA("Printing Checks","print_checks.htm");
P.fA("Recording Manual Checks","Ch4_checks.5.12.htm");
P.fA("Voiding Payment","Ch4_checks.5.13.htm");
P.fA("Voiding a Payment","Ch4_checks.5.14.htm");
P.fA("Voiding Multiple Payments","Ch4_checks.5.15.htm");
P.fA("Printing Debit Memos","Ch4_checks.5.16.htm");
P.fA("1099 Forms","Ch7_1099.6.1.htm");
P.fA("Previewing 1099 Forms","form_1099_prev_rpt.htm");
P.fA("Printing 1099 Forms","Ch7_1099.6.3.htm");
P.fA("Accounts Payable Inquiries","ap_inquiries.7.1.htm");
P.fA("Accounts Payable Inquiry","api.htm");
P.fA("Vendor Invoice Inquiry","vii.htm");
P.fA("Vendor Invoice History Inquiry","vihi.htm");
P.fA("Detail Payable Aging Inquiry","dpai.htm");
P.fA("Accounts Payable Check Inquiry","apci.htm");
P.fA("Purchase Order Invoice Inquiry","poii.htm");
P.fA("Letter of Credit Inquiry","lci.htm");
P.fA("A/P Floor Plan Inquiry","afpi.htm");
P.fA("A/P Terms Inquiry","apti.htm");
P.fA("A/P Transaction Audit Inquiry","aptai.htm");
P.fA("Accounts Payable Reports","Ch8_rpts.8.1.htm");
P.fA("Vendor Invoice Reports","Ch8_rpts.8.2.htm");
P.fA("Open Invoices On Hold Report","vend_inv_onhold_rpt.htm");
P.fA("Monthly Vendor Invoice Report","mly_vend_inv_rpt.htm");
P.fA("Lost A/P Discounts Report","missed_disc_rpt.htm");
P.fA("Accounts Payable Tax Report","ap_tax_rpt.htm");
P.fA("Open Receiver Invoice Report","open_rec_inv_rpt.htm");
P.fA("Open Vendor Invoice Report","open_adjust_rpt.htm");
P.fA("Deleted Receiver/Claims Report","deleted_rec_rpt.htm");
P.fA("Purchase Price Variance Report","purchase_price_var_rpt.htm");
P.fA("A/P Floor Planned Inventory Report","ap_fp_inv_rpt.htm");
P.fA("Vendor Payment Reports","Ch8_rpts.8.12.htm");
P.fA("Daily A/P Check Register","dly_ap_chk_rpt.htm");
P.fA("Daily A/P Manual Check Report","dly_ap_manchk_rpt.htm");
P.fA("Daily A/P Void Check Report","dly_ap_voidchk_rpt.htm");
P.fA("Monthly A/P Check Register","mly_ap_chk_rpt.htm");
P.fA("Monthly A/P Manual Check Report","mly_ap_man_chk_rpt.htm");
P.fA("Monthly A/P Void Check Report","mly_ap_voidchk_rpt.htm");
P.fA("Vendor Claims Reports","Ch8_rpts.8.19.htm");
P.fA("Open Vendor Claim Report","open_claim_rpt.htm");
P.fA("Open Vendor Claim-by Warehouse Report","ap_open_claim_rpt.htm");
P.fA("Detail Claims Allowed/Disallowed Report","det_alw_dlw_rpt.htm");
P.fA("Vendor Claims Allowed/Disallowed Summary Report","sum_alw_dlw_rpt.htm");
P.fA("G/L Distribution Reports","Ch8_rpts.8.24.htm");
P.fA("Daily Vendor Invoice Distribution Register","dly_vend_inv_rpt.htm");
P.fA("Daily Vendor Invoice Merchandise Register","dly_vend_inv_merch_rpt.htm");
P.fA("Daily A/P Distribution Report","dly_ap_dist_rpt.htm");
P.fA("A/P Payment Schedule Report","ap_schedule_rpt.htm");
P.fA("A/P Replacement Equipment Schedule Report","ap_re_schedule_rpt.htm");
P.fA("Monthly A/P Distribution Register","mly_ap_dist_rpt.htm");
P.fA("A/P Aging Reports","Ch8_rpts.8.31.htm");
P.fA("Month End A/P Aging Report","me_ap_aging_rpt.htm");
P.fA("Month End Multi Currency A/P Aging Report","me_mc_ap_aging_rpt.htm");
P.fA("Letters of Credit Reports","Ch8_rpts.8.34.htm");
P.fA("Daily Letter of Credit Register","dly_loc_reg_rpt.htm");
P.fA("Letter of Credit Register","mly_loc_reg_rpt.htm");
P.fA("Open Letter of Credit Report","open_loc_rpt.htm");
P.fA("L/C Acceptance Cash Requirements Report","loc_cash_require_rpt.htm");
P.fA("Field Definitions","oap_1099.htm");
P.fA("A/P Account Number screen","ap_acct_num.htm");
P.fA("A/P Check Add Selection screen","gl_prefix_sel.htm");
P.fA("A/P Floor Planning Maintenance screen","ap_fp_mnt.htm");
P.fA("A/P Information screen","vend_ap_info.htm");
P.fA("A/P Invoice Batch Information screen","apie_batch_ent.htm");
P.fA("A/P Vendor Invoice Batch Information screen","apie_batch_inq.htm");
P.fA("A/P Installment Terms screen","ap_terms_install.htm");
P.fA("A/P Payment Manual Selection Audit screen","apps_chk_audit.htm");
P.fA("A/P Payment Manual Selection screen","apps_manual_select.htm");
P.fA("A/P Payment Selection Header screen","auto_pay_header.htm");
P.fA("A/P Terms Maintenance screen","ap_terms_mnt.htm");
P.fA("A/P-P/O Vendor Claim Cost Adjustments screen","appo_vcr_cost_adj.htm");
P.fA("Accounts Payable Manual Invoice Entry screen","invoice_entry.htm");
P.fA("Add. Invoice Information screen","appo_add_com.htm");
P.fA("Additional Flags screen","apie_addl_flags.htm");
P.fA("AP/PO Cost Adjustments screen","appo_grid_cost_adj.htm");
P.fA("AP/PO Cost Adjustment Reason Maintenance screen","stk_adj_mnt.htm");
P.fA("AP/PO Cost Adjustment Reasons screen","appo_cost_adj_reas.htm");
P.fA("AP/PO Credit Memo Entry screen","appo_cm_ent.htm");
P.fA("AP/PO Header screen","appo_hdr_1.htm");
P.fA("APPO Import Costs screen","appo_import_code_cost.htm");
P.fA("Check History screen","ap_fp_mnt_chk_hist.htm");
P.fA("Check History Inquiry screen","check_hist_inq.htm");
P.fA("Consigned Inventory screen","consigned_inventory.htm");
P.fA("Cumulative Balance Inquiry screen","cum_bal_inq.htm");
P.fA("Currency Info screen","apie_exch_rate_diff.htm");
P.fA("Debit Memo Printing screen","dm_print_prompts.htm");
P.fA("Debit Memo Reprint Entry screen","dm_reprint.htm");
P.fA("Floor Plan Shipped Information screen","ap_fp_ship_info.htm");
P.fA("Form 1099 Printing screen","form_1099_print_prompts.htm");
P.fA("G/L Accounts For Discrepancy screen","gl_acct_disc.htm");
P.fA("High Volume AP/PO Matching Entry screen","hv_appo_ent.htm");
P.fA("Invoice Detail screen","ship_imp_dtl.htm");
P.fA("High Volume Select screen","high_vol_sel_scp.htm");
P.fA("Invoice Number Change Maintenance screen","inv_chg_mnt.htm");
P.fA("Letter of Credit Account screen","loc_gl_acct.htm");
P.fA("Letter of Credit Entry screen","loc_entry.htm");
P.fA("Letter of Credit Display screen","loc_display.htm");
P.fA("Manual Check Entry screen","man_check_entry.htm");
P.fA("Miscellaneous G/L Display screen","misc_gl_disp.htm");
P.fA("Miscellaneous G/L Entry screen","misc_gl_entry.htm");
P.fA("Miscellaneous Vendor Information screen","inv_entry_misc_vend.htm");
P.fA("Month End A/P Aging screen","me_ap_aging.htm");
P.fA("Monthly Payment History screen","mly_pay_hist_inq.htm");
P.fA("Monthly Payment Check Inquiry screen","mly_pay_check_inq.htm");
P.fA("Multi Discounts screen","appo_multi_disc_inq.htm");
P.fA("Multi Discounts screen","multi_disc_inq.htm");
P.fA("Multiple Discount Levels screen","multi_disc.htm");
P.fA("Multiple Discounts screen","apie_multi_disc.htm");
P.fA("Paid For Vendor Information screen","apie_paid_for_vend.htm");
P.fA("Receiver Detail screen","shp_rec_inq.htm");
P.fA("Receiver Detail screen","rec_imp_dtl.htm");
P.fA("Recurring Vendor Invoice Entry screen","rec_inv_ent.htm");
P.fA("Recurring Vendor Invoice Update screen","rec_inv_upd.htm");
P.fA("Vendor Address Information screen","vend_addr_inq.htm");
P.fA("Vendor Claim Merge Routine screen","vcr_merge.htm");
P.fA("Vendor Claims Split screen","vcr_split.htm");
P.fA("Vendor Invoice Merge Routine screen","appo_merge.htm");
P.fA("Vendor Invoice Reconciliation Entry screen","appo_ent.htm");
P.fA("Vendor Invoice Split Routine screen","appo_split.htm");
P.fA("Vendor Payable Type Maintenance screen","vend_pay_type_mnt.htm");
P.fA("Void Check Batch Entry screen","void_chk_batch_ent.htm");
P.fA("Voided A/P Check Entry screen","void_chk_ent.htm");
P.fA("On The Water/Ship Information screen","otw_info.htm");
}
