function FileData_Pairs(x)
{
x.t("transactions","generated");
x.t(":payroll","(pr)");
x.t("party","software");
x.t("payroll","(pr)");
x.t("payroll","package");
x.t("3rd","party");
x.t("(pr)","transactions");
x.t("(pr)","payroll");
x.t("(pr)","activant");
x.t("supported","activant");
x.t("ledger","balancing");
x.t("ledger","module");
x.t("software","longer");
x.t("balancing","general");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("code","definitions");
x.t("longer","supported");
x.t("fred","davison\u2019s");
x.t("generated","company");
x.t("module","code");
x.t("activant","solutions");
x.t("activant","general");
x.t("davison\u2019s","payroll");
x.t("package","3rd");
x.t("866-878-0574","972-403-3150");
x.t("using","fred");
x.t("general","ledger");
x.t("company","using");
x.t("definitions",":payroll");
}
