function FileData_Pairs(x)
{
x.t("refer","following");
x.t("errors","general");
x.t("open","journal");
x.t("inquiry","open");
x.t("inquiry","journal");
x.t("entry","inquiry");
x.t("entry","journal");
x.t("entry","proof");
x.t("journal","entry");
x.t("journal","entries");
x.t("account","journal");
x.t("account","adjusting");
x.t("account","activant");
x.t("allow","correct");
x.t("adjusting","general");
x.t("ledger","account");
x.t("ledger","postings");
x.t("proof","report");
x.t("report","journal");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("enter","year-end");
x.t("correct","errors");
x.t("information","journal");
x.t("postings","enter");
x.t("activant","solutions");
x.t("year-end","adjustments");
x.t("following","information");
x.t("866-878-0574","972-403-3150");
x.t("general","ledger");
x.t("adjustments","refer");
x.t("entries","journal");
x.t("entries","allow");
x.t("entries",":adjusting");
x.t(":adjusting","general");
}
