function FileData_Pairs(x)
{
x.t("refer","journal");
x.t(":journal","entry");
x.t("posted","depends");
x.t("type","adjustment");
x.t("entry","journal");
x.t("entry","activant");
x.t("journal","entry");
x.t("journal","entries");
x.t("depends","type");
x.t("account","posted");
x.t("allow","manually");
x.t("adjust","general");
x.t("ledger","account");
x.t("ledger","balancing");
x.t("ledger","module");
x.t("ledger","postings");
x.t("balancing","general");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("code","definitions");
x.t("module","code");
x.t("postings","general");
x.t("activant","solutions");
x.t("866-878-0574","972-403-3150");
x.t("general","ledger");
x.t("manually","adjust");
x.t("adjustment","refer");
x.t("definitions",":journal");
x.t("entries","allow");
x.t("entries","general");
}
