function FileData_Pairs(x)
{
x.t("balance","redistributing");
x.t("balance","redistribute");
x.t("balance","activant");
x.t("balance","general");
x.t("g/l","redistribution");
x.t("redistributing","general");
x.t("account","accounts");
x.t("programs","g/l");
x.t(":redistributing","general");
x.t("ledger","balance");
x.t("ledger","account");
x.t("ledger","chart");
x.t("chart","accounts");
x.t("maintenance","g/l");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("process","general");
x.t("redistribute","balance");
x.t("activant","solutions");
x.t("following","programs");
x.t("866-878-0574","972-403-3150");
x.t("general","ledger");
x.t("accounts",":redistributing");
x.t("accounts","following");
x.t("redistribution","maintenance");
x.t("redistribution","update");
x.t("update","process");
}
