function FileData_Pairs(x)
{
x.t("end-of-month/end-of-year","closing");
x.t("balance","reconcile");
x.t("refer","following");
x.t("responsible","month-end");
x.t("end-of-month","closing");
x.t("month","year-end");
x.t("procedures","end-of-month/end-of-year");
x.t("procedures","refer");
x.t("procedures","end-of-month");
x.t("procedures","run");
x.t("procedures","end-of-year");
x.t("ledger","month");
x.t("person","company");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("smoothly","designate");
x.t("closing","end-of-month/end-of-year");
x.t("closing","balance");
x.t("closing","procedures");
x.t("closing","activant");
x.t("reconcile","general");
x.t("information","month-end");
x.t("activant","solutions");
x.t("year-end","procedures");
x.t("year-end","closing");
x.t("run","smoothly");
x.t("following","information");
x.t("866-878-0574","972-403-3150");
x.t("general","ledger");
x.t("month-end","year-end");
x.t("company","responsible");
x.t("end-of-year","closing");
x.t("designate","person");
}
