function FileData_Pairs(x)
{
x.t("available","prelude");
x.t("financial","features");
x.t("currency","using");
x.t("multiple","currency");
x.t("multiple","fiscal");
x.t("features","available");
x.t("features","optional");
x.t("features","activant");
x.t("features","following");
x.t("standard","cost");
x.t("fiscal","periods");
x.t("prelude","using");
x.t("cost","optional");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("periods","using");
x.t("optional","financial");
x.t("activant","solutions");
x.t("following","optional");
x.t("866-878-0574","972-403-3150");
x.t("using","multiple");
x.t("using","standard");
}
