function FileData_Pairs(x)
{
x.t("refer","following");
x.t("g/l","account");
x.t("responses","project");
x.t("require","project");
x.t("track","group");
x.t("group","projects");
x.t("requirements","project");
x.t("creating","valid");
x.t("account","require");
x.t("codes","general");
x.t("codes","setting");
x.t("post","general");
x.t("ledger","valid");
x.t("ledger","accounts");
x.t("maintenance","requirements");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("projects","post");
x.t("project","refer");
x.t("project","codes");
x.t("project","project");
x.t("project","tracking");
x.t("valid","responses");
x.t("valid","project");
x.t(":maintenance","requirements");
x.t("activant","solutions");
x.t("following","creating");
x.t("866-878-0574","972-403-3150");
x.t("general","ledger");
x.t("setting","g/l");
x.t("tracking","track");
x.t("tracking","maintenance");
x.t("tracking",":maintenance");
x.t("tracking","activant");
x.t("accounts","require");
}
