function FileData_Pairs(x)
{
x.t("balance","payments");
x.t("refer","following");
x.t("outstanding","checks");
x.t("outstanding","deposits");
x.t("cleared","bank");
x.t("payments","deposits");
x.t("sections","information");
x.t("checks","deposits");
x.t("checks","reconciling");
x.t("checks","report");
x.t("deposits","cleared");
x.t("deposits","report");
x.t("deposits","a/p");
x.t("allows","balance");
x.t("prelude","bank");
x.t("reconciling","checks");
x.t("bank","refer");
x.t("bank","reconciliation");
x.t("report","bank");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("process","allows");
x.t("information","reconciling");
x.t("reconciliation","outstanding");
x.t("reconciliation","prelude");
x.t("reconciliation","bank");
x.t("reconciliation","process");
x.t("reconciliation","activant");
x.t("a/p","reconciliation");
x.t("activant","solutions");
x.t("following","sections");
x.t("866-878-0574","972-403-3150");
}
