function FileData_Pairs(x)
{
x.t("posting","recurring");
x.t("refer","following");
x.t(":creating","recurring");
x.t("entry","proof");
x.t("entry","recurring");
x.t("journal","entry");
x.t("journal","entries");
x.t("creating","recurring");
x.t("account","range");
x.t("range","fiscal");
x.t("fiscal","periods");
x.t("allow","adjustment");
x.t("ledger","account");
x.t("ledger","accounts");
x.t("proof","report");
x.t("report","posting");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("periods","refer");
x.t("recurring","journal");
x.t("recurring","adjustments");
x.t("recurring","entries");
x.t("information","recurring");
x.t("activant","solutions");
x.t("following","information");
x.t("866-878-0574","972-403-3150");
x.t("adjustments","general");
x.t("general","ledger");
x.t("adjustment","general");
x.t("accounts","creating");
x.t("accounts","recurring");
x.t("accounts","activant");
x.t("entries",":creating");
x.t("entries","journal");
x.t("entries","allow");
x.t("entries","recurring");
}
