function  WWHBookData_Files(P)
{
P.fA("The Warehousing module was designed to process transactions more efficiently and with a greater level of accuracy with and without Radio Frequency (RF) units. Bin level allocation programs are available for sales orders, stock transfers, work orders, and bin replenishments. Lot controlled products are committed at the lot level. The allocation routine determines the remaining bin available quantity by using the current bin onhand quantity less the committed quantity. For example, bin level commitments are maintained allowing a bin available evaluation during transaction processing. Once inventory in a bin is completely committed then the next available bin is committed for subsequent transactions.","opt_whs.1.1.htm");
P.fA("Maintenance","opt_whs.1.2.htm");
P.fA("Warehousing Options (/WM &gt; F7 &gt; F5)","opt_whs.1.3.htm");
P.fA("Transfer Picking Options (F5)","opt_whs.1.4.htm");
P.fA("Receiving Options (F8)","opt_whs.1.5.htm");
P.fA("Bin Location Maintenance (/BLM)","opt_whs.1.6.htm");
P.fA("User Id Security Setup","opt_whs.1.7.htm");
P.fA("Entering, Picking, and Shipping Sales Orders","opt_whs.1.8.htm");
P.fA("Sales Order Picking/Shipping","opt_whs.1.9.htm");
P.fA("Sales Order Bin Allocation and Pick Ticket Printing","opt_whs.1.10.htm");
P.fA("Sales Order Picker Assignment/Unassignment by Release","opt_whs.1.11.htm");
P.fA("Sales Order Picker Assignment Listing","opt_whs.1.12.htm");
P.fA("Radio Frequency Order Picking","opt_whs.1.13.htm");
P.fA("Pick Confirmation \u2013 by Range or by Release","opt_whs.1.14.htm");
P.fA("Radio Frequency Confirmation Packing","opt_whs.1.15.htm");
P.fA("Pack Confirmation Entry","opt_whs.1.16.htm");
P.fA("Release Shipment Entry","opt_whs.1.17.htm");
P.fA("Wrist RF Order Picking","opt_whs.1.18.htm");
P.fA("Segment/Truck Route Processing","opt_whs.1.19.htm");
P.fA("Maintenance","opt_whs.1.20.htm");
P.fA("Processes","opt_whs.1.21.htm");
P.fA("Picking by Segment","opt_whs.1.22.htm");
P.fA("Wrist Picking - Batch Processing","opt_whs.1.23.htm");
P.fA("Warehouse Maintenance","opt_whs.1.24.htm");
P.fA("Batch Pick Ticket Processing","opt_whs.1.25.htm");
P.fA("RF Order Batch Queue Inquiry","opt_whs.1.26.htm");
P.fA("Wrist RF Order Picking","opt_whs.1.27.htm");
P.fA("Shipping Box Confirmation Entry","opt_whs.1.28.htm");
P.fA("Staging Order Batch Purge","opt_whs.1.29.htm");
P.fA("RF Order Batch History Inquiry","opt_whs.1.30.htm");
P.fA("Staging Order Batch History Purge","opt_whs.1.31.htm");
P.fA("Receiving and Putting Away Stock","opt_whs.1.32.htm");
P.fA("Maintenance","opt_whs.1.33.htm");
P.fA("Receiving Stock","opt_whs.1.34.htm");
P.fA("Transfers","opt_whs.1.35.htm");
P.fA("Work Orders","opt_whs.1.36.htm");
P.fA("Replenishing Bins","opt_whs.1.37.htm");
P.fA("Cycle Counting","opt_whs.1.38.htm");
P.fA("Warehousing Inquiries","opt_whs.1.39.htm");
P.fA("Checklists","opt_whs.1.40.htm");
}
