function  WWHBookData_Files(P)
{
P.fA("Accounts Receivable Overview","overview.1.1.htm");
P.fA("Accounts Receivable Maintenance Setup","setup.2.1.htm");
P.fA("Using A/R Payment Terms","setup.2.2.htm");
P.fA("Understanding Payment Terms","setup.2.3.htm");
P.fA("Setting Up A/R Payment Terms","setup.2.4.htm");
P.fA("Calculating Average Days to Pay","setup.2.5.htm");
P.fA("Creating Unearned Discount Reason Codes","setup.2.6.htm");
P.fA("Creating Charge Back Reason Codes","setup.2.7.htm");
P.fA("Setting up Financial References","setup.2.8.htm");
P.fA("Cash Receipts","cust_pmt.3.1.htm");
P.fA("Receiving Customer Payments","cust_pmt.3.2.htm");
P.fA("Beginning a Cash Receipt Batch","cust_pmt.3.3.htm");
P.fA("Applying Cash to Invoices","cust_pmt.3.4.htm");
P.fA("Manually Applying Cash to Individual Invoices","cust_pmt.3.5.htm");
P.fA("Automatically Applying Cash to Invoices","cust_pmt.3.6.htm");
P.fA("Overriding an Unearned Discount","cust_pmt.3.7.htm");
P.fA("Reconciling Partial Payments","cust_pmt.3.8.htm");
P.fA("Adjusting Tax and Freight","cust_pmt.3.9.htm");
P.fA("Issuing Charge Back Invoices","cust_pmt.3.10.htm");
P.fA("Writing off the Unpaid Balance","cust_pmt.3.11.htm");
P.fA("Reconciling Over Payments","cust_pmt.3.12.htm");
P.fA("Applying Extra Cash On-Account","cust_pmt.3.13.htm");
P.fA("Refunding a Customer Account for Over-Payment","cust_pmt.3.14.htm");
P.fA("Completing the Batch","cust_pmt.3.15.htm");
P.fA("Applying EDI Payments in High-Volume Cash Receipts","cust_pmt.3.16.htm");
P.fA("Entering a High Volume Cash Receipts Batch","cust_pmt.3.17.htm");
P.fA("Matching Cash Receipts with Open Invoices","cust_pmt.3.18.htm");
P.fA("Fast Cash Receipts Work File Report","cust_pmt.3.19.htm");
P.fA("Manually Matching and Editing Invoices","cust_pmt.3.20.htm");
P.fA("Updating a Batch","fast_cash_upd.htm");
P.fA("Fast Cash Receipts Exception Report","cust_pmt.3.22.htm");
P.fA("Purging a Batch","cust_pmt.3.23.htm");
P.fA("Receiving Credit Card Payments","cust_pmt.3.24.htm");
P.fA("Entering a Credit Card Payment Batch","cust_pmt.3.25.htm");
P.fA("Closing the A/R Credit Card Batch","cust_pmt.3.26.htm");
P.fA("ARCC Balancing Report","arcc_bal_rpt.htm");
P.fA("Recording Cash Deposited from Cash Sales","cust_pmt.3.28.htm");
P.fA("Customer Invoices and Statements","invoices.4.1.htm");
P.fA("Manually Entering an Invoice","invoices.4.2.htm");
P.fA("Editing an A/R Invoice","invoices.4.3.htm");
P.fA("Generating Customer Rebates","invoices.4.4.htm");
P.fA("Creating a Customer Rebate Program","invoices.4.5.htm");
P.fA("Assigning a Rebate Program to a Customer","invoices.4.6.htm");
P.fA("Editing Customer Invoice Rebates","invoices.4.7.htm");
P.fA("Converting Customer Rebate Information","invoices.4.8.htm");
P.fA("Printing Charge Back Invoices","invoices.4.9.htm");
P.fA("Generating Service Charge Invoices","invoices.4.10.htm");
P.fA("Setting Maintenance Options for Service Charges","invoices.4.11.htm");
P.fA("Accounts Receivable Parameters","invoices.4.12.htm");
P.fA("Additional Option Parameters","invoices.4.13.htm");
P.fA("Customer Maintenance","invoices.4.14.htm");
P.fA("Automatically Assessing Service Charges","invoices.4.15.htm");
P.fA("Manually Assessing or Editing a Service Charge","invoices.4.16.htm");
P.fA("Printing Service Charge Invoices","invoices.4.17.htm");
P.fA("Generating Statements for Customers","invoices.4.18.htm");
P.fA("Maintenance Options for Statements","invoices.4.19.htm");
P.fA("Accounts Receivable Parameters","invoices.4.20.htm");
P.fA("Customer Maintenance","invoices.4.21.htm");
P.fA("Printing Statements","invoices.4.22.htm");
P.fA("Purging Zero Balance A/R Records","invoices.4.23.htm");
P.fA("Credit Holds","credit_holds.5.1.htm");
P.fA("Defining Maintenance Options for Credit Hold","credit_holds.5.2.htm");
P.fA("File Update Parameters","credit_holds.5.3.htm");
P.fA("Accounts Receivable Parameters","credit_holds.5.4.htm");
P.fA("Order Processing Parameters","credit_holds.5.5.htm");
P.fA("Warehouse Maintenance","credit_holds.5.6.htm");
P.fA("Rental Parameters","credit_holds.5.7.htm");
P.fA("Company Maintenance","credit_holds.5.8.htm");
P.fA("Credit Authorization Code Maintenance","credit_holds.5.9.htm");
P.fA("Customer Maintenance","credit_holds.5.10.htm");
P.fA("Setting up Credit Managers","credit_holds.5.11.htm");
P.fA("Manager Maintenance","credit_holds.5.12.htm");
P.fA("Warehouse Manager Maintenance","credit_holds.5.13.htm");
P.fA("User Id Maintenance","credit_holds.5.14.htm");
P.fA("Assigning Credit Managers to a Group of Customers","credit_holds.5.15.htm");
P.fA("Automatically Placing Customers on Credit Hold","auto_cred_hold.htm");
P.fA("Manually Placing an Order on Credit Hold","credit_holds.5.17.htm");
P.fA("Releasing Orders From Credit Hold","cred_rel_inq.htm");
P.fA("Excluding Sales Orders From the Credit Limit","credit_holds.5.19.htm");
P.fA("Credit Collections Subsystem","credit_collections.6.1.htm");
P.fA("Defining Customers/Invoices to Include in Credit Collections","credit_collections.6.2.htm");
P.fA("Accounts Receivable Parameters","credit_collections.6.3.htm");
P.fA("Additional Option Parameters","credit_collections.6.4.htm");
P.fA("Customer Maintenance","credit_collections.6.5.htm");
P.fA("Setting up Credit Collections","credit_collections.6.6.htm");
P.fA("Defining Credit Collections Types","credit_collections.6.7.htm");
P.fA("Creating Credit Collections Activity Codes","credit_collections.6.8.htm");
P.fA("Sequencing Follow-Up Collection Activities","credit_collections.6.9.htm");
P.fA("Generating Credit Collections Activities","credit_collections.6.10.htm");
P.fA("Running Credit Collections Nightly Processing","ccnp.htm");
P.fA("Entering Scheduled Credit Collection Activities","credit_collections.6.12.htm");
P.fA("Generating Scheduled Collection Letters","credit_collections.6.13.htm");
P.fA("Generating Collection Letters on Demand","credit_collections.6.14.htm");
P.fA("Entering/Viewing Credit Collection Notes","credit_collections.6.15.htm");
P.fA("Entering Credit Collections Notes","credit_collections.6.16.htm");
P.fA("Credit Collections Historical Notes Maintenance","credit_collections.6.17.htm");
P.fA("Credit Collections History Inquiry","credit_collections.6.18.htm");
P.fA("Credit Collections Activity Report","cred_coll_act_rpt.htm");
P.fA("Accounts Receivable Inquiries","ar_inquiries.7.1.htm");
P.fA("Accounts Receivable Inquiry","ar_inq.htm");
P.fA("Customer Invoice Inquiry","cust_inv_inq.htm");
P.fA("Invoice Detail Inquiry","inv_inq.htm");
P.fA("Detail Aging Inquiry","det_aging_inq.htm");
P.fA("Customer Performance Summary Inquiry","cust_perform.htm");
P.fA("A/R Terms Inquiry","ar_inquiries.7.7.htm");
P.fA("Manual A/R Inquiry","man_inv_inq.htm");
P.fA("Cash Receipts History Inquiry","cash_rec_inq.htm");
P.fA("A/R Transaction Audit Inquiry","ar_audit_inq.htm");
P.fA("Accounts Receivable Reports","reports.8.1.htm");
P.fA("Open Accounts Receivable Report","daily_ar_cash_rpt.htm");
P.fA("Accounts Receivable Aging Reports","reports.8.3.htm");
P.fA("Accounts Receivable Aging Report","ar_age_rpt.htm");
P.fA("Master Customer Accounts Receivable Aging Report","mast_ar_age_rpt.htm");
P.fA("Month End A/R Aging Report","me_ar_age_rpt.htm");
P.fA("Accounts Receivable Aging Report (Original)","ar_age_orig_rpt.htm");
P.fA("Detailed Aged Accounts Receivable Report","me_ar_aging_rpt.htm");
P.fA("Detail Replacement Equipment Aged Accounts Receivable Report","re_ar_aging_rpt.htm");
P.fA("Aged A/R User Defined Dates Report","ar_aging_dte_rpt.htm");
P.fA("Overdue Accounts Receivable Report","overdue_ar_rpt.htm");
P.fA("Cash Receipts Reports","reports.8.12.htm");
P.fA("Daily Cash Receipts Report","dly_cash_rec_rpt.htm");
P.fA("Monthly Cash Receipts Report","mly_cash_rec_rpt.htm");
P.fA("Cash Receipts History Report","cr_hist_rpt.htm");
P.fA("Cash Receipts Deposit Summary Report","cash_dep_sum_rpt.htm");
P.fA("Customers With On Account Balances Report","cust_cash_on_acc_rpt.htm");
P.fA("Incomplete Cash Receipts Report","inc_cash_rec_rpt.htm");
P.fA("Unearned Cash Discounts Report","unearn_disc_rpt.htm");
P.fA("A/R Manual Invoice Report","man_inv_rpt.htm");
P.fA("Service Charge Journal","mon_srv_chg_lst.htm");
P.fA("Daily Credit Status Change Report","cr_stat_rpt.htm");
P.fA("Customer Over Credit Limit Report","over_cr_lim_rpt.htm");
P.fA("Credit Review Report","cred_rev_rpt.htm");
P.fA("Credit Manager Release Report","crd_mgr_rel_rpt.htm");
P.fA("Administrative Manager Release Report","adm_mgr_rel_rpt.htm");
P.fA("Cash Deposit Report","cash_dep_rpt.htm");
P.fA("Customer/Vendor Activity Report","cust_vend_act_rpt.htm");
P.fA("Field Definitions","ar_cc_pay_ent.htm");
P.fA("A/R Payment Terms Maintenance screen","ar_terms_mnt.htm");
P.fA("Accounts Receivable Maintenance screen","ar_mnt.htm");
P.fA("Additional Info screen","cred_coll_add_info.htm");
P.fA("Auto Service Charge Entry screen","serv_chges.htm");
P.fA("Best Match screen","fast_cash_match.htm");
P.fA("Cash Receipts Chargeback By Customer P/O Number screen","field_defs.9.7.htm");
P.fA("Cash Receipts Detail Display screen","cash_detail_inq.htm");
P.fA("Cash Receipts Entry screen","cash_receipts.htm");
P.fA("Cash Receipts Invoice Detail Entry screen","cash_detail_entry.htm");
P.fA("Cash Receipts Status Display screen","cash_rec_status.htm");
P.fA("Cash Sales Deposit Maintenance screen","cash_dep_mnt.htm");
P.fA("Charge Back Entry screen","cash_rec_chrgbck_entry.htm");
P.fA("Charge Back Invoice Entry screen","cash_rec_chrgbck_coa.htm");
P.fA("Charge Back Print screen","chrgbck_print_prompts.htm");
P.fA("Charge Back Reason Code Maintenance screen","chrg_back_mnt.htm");
P.fA("Credit Adjustment Entry screen","cash_rec_tax_credit_entry.htm");
P.fA("Credit Collections Activity Maintenance screen","cred_coll_act_mnt.htm");
P.fA("Credit Collections Customer Entry screen","cred_coll_sched_mnt.htm");
P.fA("Credit Collections Follow-Up Maintenance screen","cred_coll_follow_mnt.htm");
P.fA("Credit Collections Historical Notes Maintenance screen","cred_coll_hist_mnt.htm");
P.fA("Credit Collections Letter Generation screen","cred_coll_gen_letters.htm");
P.fA("Credit Collections Letter On Demand screen","cred_coll_gen_demand.htm");
P.fA("Credit Collections Notes Maintenance screen","cred_coll_notes_mnt.htm");
P.fA("Credit Collections Schedule Entry screen","cred_coll_sched_ent.htm");
P.fA("Credit Collections Type Maintenance screen","cred_coll_type_mnt.htm");
P.fA("Cumulative Balance Inquiry screen","cash_cum_bal_inq.htm");
P.fA("Customer Credit Manager Assignment screen","cred_mgr_asg.htm");
P.fA("Customer Invoice Rebate Maintenance screen","cust_rebate_mnt.htm");
P.fA("Customer P/O Number screen","po_num_batch_scr.htm");
P.fA("Financial Reference Maintenance screen","fin_ref_mnt.htm");
P.fA("Financial Report Column Maintenance screen","finrpt_col_mnt.htm");
P.fA("Generate Credit Balance Refund screen","gen_credit_refund.htm");
P.fA("High Volume Cash Detail Entry screen","fcr_cash_detail_entry.htm");
P.fA("High Volume Cash Detail Maintenance screen","cash_detail_mnt.htm");
P.fA("High Volume Cash Purge screen","fast_cash_purge.htm");
P.fA("High Volume Cash Receipts Entry screen","fast_cash_hdr.htm");
P.fA("High Volume Cash Receipts Maintenance screen","fast_cash_hdr_mnt.htm");
P.fA("Invoice List screen","inv_list.htm");
P.fA("Invoice Number Range Entry screen","cre_inv_num_range.htm");
P.fA("Manual Invoice Entry screen","man_inv_ent.htm");
P.fA("Manual Service Charge Entry screen","serv_chge_mnt.htm");
P.fA("Misc Cash Receipts Entry screen","cash_rec_misc_entry.htm");
P.fA("Multiple Discount Levels screen","mult_disc_mnt.htm");
P.fA("Monthly Cash Receipts History screen","mly_cr_hist.htm");
P.fA("Pending RGA Inquiry screen","open_rga_inq.htm");
P.fA("Purge Zero Balance A/R Records screen","purge_zero_bal.htm");
P.fA("Service Charge Invoice Printing screen","sc_print_prompts.htm");
P.fA("Unearned Discount screen","cash_rec_unearn_dsc.htm");
P.fA("Unearned Discount Reason Maintenance screen","udisc_mnt.htm");
}
