function FileData_Pairs(x)
{
x.t("current","sales");
x.t("shows","current");
x.t("shipping","sales");
x.t("orders",":sales");
x.t("orders","assigned");
x.t("(/ord.pick.lst)","report");
x.t("entering","picking");
x.t("assignment","listing");
x.t("path","warehousing");
x.t("sales","orders");
x.t("sales","order");
x.t(":sales","order");
x.t("listing","(/ord.pick.lst)");
x.t("listing","path");
x.t("listing","sales");
x.t("listing","activant");
x.t("processing","sales");
x.t("report","shows");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("assigned","picker");
x.t("picking","shipping");
x.t("warehousing","sales");
x.t("activant","solutions");
x.t("order","processing");
x.t("order","picker");
x.t("866-878-0574","972-403-3150");
x.t("picker","entering");
x.t("picker","assignment");
}
