function FileData_Pairs(x)
{
x.t("shipping","sales");
x.t("orders",":release");
x.t("releases","shipment");
x.t("updates","freight");
x.t("entering","picking");
x.t("entry","path");
x.t("entry","release");
x.t("entry","(/rse)");
x.t("entry","activant");
x.t("path","warehousing");
x.t(":release","shipment");
x.t("sales","orders");
x.t("sales","order");
x.t("shipment","updates");
x.t("shipment","entry");
x.t("processing","release");
x.t("solutions","866-878-0574");
x.t("972-403-3150","preludeeducation@activant.com");
x.t("release","shipment");
x.t("amount","entering");
x.t("picking","shipping");
x.t("(/rse)","process");
x.t("process","releases");
x.t("warehousing","sales");
x.t("freight","amount");
x.t("activant","solutions");
x.t("order","processing");
x.t("866-878-0574","972-403-3150");
}
