function  WWHBookData_Files(P)
{
P.fA("UniData","admin_tech.1.1.htm");
P.fA("The vi Editor","admin_tech.1.2.htm");
P.fA("Create Unidata TEST and TEST-DATA Accounts from Tape","admin_tech.1.3.htm");
P.fA("TANDEM Command","admin_tech.1.4.htm");
P.fA("AIX and UniData Software Release Policy","admin_tech.1.5.htm");
P.fA("File System Administration","admin_tech.1.6.htm");
P.fA("Record Locks","admin_tech.1.7.htm");
P.fA("PSI Copy - Copying Live to Test","admin_tech.1.8.htm");
P.fA("Prestores","admin_tech.1.9.htm");
P.fA("Background Jobs","admin_tech.1.10.htm");
P.fA("Creating New Accounts","admin_tech.1.11.htm");
P.fA("Lists","admin_tech.1.12.htm");
P.fA("Guide/Fixfile","admin_tech.1.13.htm");
P.fA("Checking the Disk Capacity of Your System","admin_tech.1.14.htm");
P.fA("Debugging BASIC Programs","admin_tech.1.15.htm");
P.fA("Cataloging","admin_tech.1.16.htm");
P.fA("Identifying Bad Record Keys","admin_tech.1.17.htm");
P.fA("Account Save/Restore","admin_tech.1.18.htm");
P.fA("How to Set Defaults for Master Files","admin_tech.1.19.htm");
P.fA("Btree (Indexes)","admin_tech.1.20.htm");
P.fA("Version 18 and Higher","admin_tech.1.21.htm");
P.fA("Version 17 and Lower","admin_tech.1.22.htm");
P.fA("SBClient","admin_tech.1.23.htm");
P.fA("Installing GUI Icons","admin_tech.1.24.htm");
P.fA("Configuring the Session","admin_tech.1.25.htm");
P.fA("Defining GUI Terminal Types and Preferences","admin_tech.1.26.htm");
P.fA("Logging In","admin_tech.1.27.htm");
P.fA("Host Library","admin_tech.1.28.htm");
P.fA("Network Setup","admin_tech.1.29.htm");
P.fA("Host to PC Download","admin_tech.1.30.htm");
P.fA("Smart Query","admin_tech.1.31.htm");
P.fA("Taking An Existing Report To Excel","admin_tech.1.32.htm");
P.fA("Windows Clipboard","admin_tech.1.33.htm");
P.fA("SBClient FAQs","admin_tech.1.34.htm");
P.fA("RF Guns","admin_tech.1.35.htm");
P.fA("Loading Files to 11 Mbit/s Series RF Guns","admin_tech.1.36.htm");
P.fA("Loading Files to 2 Mbit/s Series RF Guns","admin_tech.1.37.htm");
P.fA("Setting Up your PC to Program a MC9060 RF Gun","admin_tech.1.38.htm");
P.fA("Troubleshooting RF guns with DOS Operating Systems","admin_tech.1.39.htm");
P.fA("Using RAS2 Dataswitch (Penril) Replacement","admin_tech.1.40.htm");
P.fA("VSI-Fax","admin_tech.1.41.htm");
P.fA("VSI-Fax FAQs","admin_tech.1.42.htm");
P.fA("Faxing Documents with VSI-Fax","admin_tech.1.43.htm");
P.fA("Optio","admin_tech.1.44.htm");
P.fA("Optio","admin_tech.1.45.htm");
P.fA("Optio Fax Confirmations","admin_tech.1.46.htm");
P.fA("Printers","admin_tech.1.47.htm");
P.fA("Printer Form Feed Options","admin_tech.1.48.htm");
P.fA("Printer Administration","admin_tech.1.49.htm");
P.fA("PrleudeFTP Processing","admin_tech.1.50.htm");
P.fA("Convert Decimal Places","admin_tech.1.51.htm");
P.fA("Macros - /UK","admin_tech.1.52.htm");
P.fA("Send Page Feature","admin_tech.1.53.htm");
P.fA("Using the Scheduler","admin_tech.1.54.htm");
P.fA("Scheduler Inquiry (/SCHED.INQ)","admin_tech.1.55.htm");
P.fA("Starting and Stopping the Scheduler","admin_tech.1.56.htm");
P.fA("Scheduler Control Maintenance (/SCHED.CONTOL.MNT)","admin_tech.1.57.htm");
P.fA("Purging Data","admin_tech.1.58.htm");
P.fA("Purging Product &amp; Warehouse Data","admin_tech.1.59.htm");
P.fA("Purging Customer Data","admin_tech.1.60.htm");
P.fA("Miscellaneous","admin_tech.1.61.htm");
P.fA("UPS Testing Procedure","admin_tech.1.62.htm");
P.fA("Protobase FAQ","admin_tech.1.63.htm");
P.fA("Point-of-Sale Terminal Set-Up Parameters","admin_tech.1.64.htm");
P.fA("Logging Off of a Customer\u2019s Computer","admin_tech.1.65.htm");
}
